In [1]:
from glob import glob
import pandas as pd
from tqdm import tqdm

from locations import extract_urls
from events import parse_mmd_taxonomy, extract_events
from timespan import parse_timespan

In [2]:
root_path = "../data/schede mappatura/"

skip = {"david_ruth_FEGB_E_00007": {"rows": 6, "cols": 1}}

In [3]:
chrono_schede = glob(f"{root_path}*/chronotop*")
chrono_schede

['../data/schede mappatura/bruenn_jehoshua_IS_S_00028/chronotopoi_bruenn_jehoshua_bozza.xlsx',
 '../data/schede mappatura/david_ruth_FEGB_E_00007/chronotopi_ruth_david_FEGB_E_00007.xlsx',
 '../data/schede mappatura/bruenn_ charlotte_IS_S_00027/chronotopi_charlotte_bruenn_IS_S_00027 (file revisionato).xlsx',
 '../data/schede mappatura/bruenn_ charlotte_IS_S_00027/chronotopoi_charlotte_bruenn_IS_S_00027 (bozza).xlsx',
 '../data/schede mappatura/stern_IS_S_00142/chronotopi_josef_stern_IS_S_00142.xlsx']

## A list of individual sources for experimentation

ignored in the oveall logic

In [4]:
current = "bruenn_jehoshua_IS_S_00028/chronotopoi_bruenn_jehoshua_bozza.xlsx"
# current = "david_ruth_FEGB_E_00007/chronotopi_ruth_david_FEGB_E_00007.xlsx"
current = "bruenn_ charlotte_IS_S_00027/chronotopi_charlotte_bruenn_IS_S_00027 (file revisionato).xlsx"
current = "stern_IS_S_00142/chronotopi_josef_stern_IS_S_00142.xlsx"

overview = {}
for s in chrono_schede:
    wb = openpyxl.load_workbook(s)
    overview[s] = wb.sheetnames
overview

After identification of all sources

# Shortlist processable sources

In [5]:
overview = {
    "bruenn_jehoshua_IS_S_00028/chronotopoi_bruenn_jehoshua_bozza.xlsx": [
        "Foglio1",
    ],
    # 'david_ruth_FEGB_E_00007/chronotopi_ruth_david_FEGB_E_00007.xlsx': ['Ruth L.David',
    #  'Mutter',
    #  'Vater',
    #  'Isaak Oppenheimer',
    #  'Ernst',
    #  'Werner',
    #  'Hanna',
    #  'Michael',
    #  'Fedora',
    #  'Liese',
    #  'Herbert Aron David',
    #  'Alice Urbach'],
    "bruenn_ charlotte_IS_S_00027/chronotopi_charlotte_bruenn_IS_S_00027 (file revisionato).xlsx": [
        "Charlotte Bruenn geb. Hirsch",
        "Ludwig Hirsch",
        "Gutta Hirsch geb. Dingfelder",
        "Alice Hirsch (Estryn)",
        "Erich Hirsch",
        "Walter Hirsch",
        "Alfons Justin Hirsch",
        "Margot Hirsch",
    ],
    "stern_IS_S_00142/chronotopi_josef_stern_IS_S_00142.xlsx": [
        "Josef Stern",
        "Julius Stern",
        "Esther Stern",
        "Sonja Stern",
        "Großvater M David Kaminka",
        "Großmutter M Betty Kaminka geb.",
        "Großvater V Isaak Stern",
        "Großmutter V Auguste Stern geb ",
        "Mutter 2 Claire Stern",
    ],
}

## Put all data together

In [6]:
first = True
df_list = []
for k, v in overview.items():
    for s in v:
        name = k.split("/")[0]
        # print(k,s)
        if name in skip:
            df = pd.read_excel(
                root_path + k, sheet_name=s, skiprows=skip[name]["rows"]
            ).iloc[:, skip[name]["cols"] :]
        else:
            df = pd.read_excel(root_path + k, sheet_name=s)

        print(k, s, df.columns)
        df.columns = ["event", "location", "timespan", "notes", "links"]

        # merge columns 6+ to notes
        df["notes"] = df[["notes"] + list(df.columns[6:])].apply(
            lambda row: " ".join(row.dropna().astype(str)), axis=1
        )
        df = df.drop(df.columns[6:], axis=1)

        df["protagonist"] = name
        df["name"] = s
        df_list += [df]
df = pd.concat(df_list, axis=0)
df.fillna("", inplace=True)
df

bruenn_jehoshua_IS_S_00028/chronotopoi_bruenn_jehoshua_bozza.xlsx Foglio1 Index(['EVENT', 'LOCATION', 'TIMESPAN', 'NOTES', 'LINKS'], dtype='str')
bruenn_ charlotte_IS_S_00027/chronotopi_charlotte_bruenn_IS_S_00027 (file revisionato).xlsx Charlotte Bruenn geb. Hirsch Index(['Event', 'Location', 'Timespan', 'Notes', 'Links'], dtype='str')
bruenn_ charlotte_IS_S_00027/chronotopi_charlotte_bruenn_IS_S_00027 (file revisionato).xlsx Ludwig Hirsch Index(['Event', 'Location', 'Timespan', 'Notes', 'Links'], dtype='str')
bruenn_ charlotte_IS_S_00027/chronotopi_charlotte_bruenn_IS_S_00027 (file revisionato).xlsx Gutta Hirsch geb. Dingfelder Index(['Event', 'Location', 'Timespan', 'Notes', 'Links'], dtype='str')
bruenn_ charlotte_IS_S_00027/chronotopi_charlotte_bruenn_IS_S_00027 (file revisionato).xlsx Alice Hirsch (Estryn) Index(['Event', 'Location', 'Timespan', 'Notes', 'Links'], dtype='str')
bruenn_ charlotte_IS_S_00027/chronotopi_charlotte_bruenn_IS_S_00027 (file revisionato).xlsx Erich Hirsch Index(['Event', 'Location', 'Timespan', 'Notes', 'Links'], dtype='str')
bruenn_ charlotte_IS_S_00027/chronotopi_charlotte_bruenn_IS_S_00027 (file revisionato).xlsx Walter Hirsch Index(['Event', 'Location', 'Timespan', 'Notes', 'Links'], dtype='str')
bruenn_ charlotte_IS_S_00027/chronotopi_charlotte_bruenn_IS_S_00027 (file revisionato).xlsx Alfons Justin Hirsch Index(['Event', 'Location', 'Timespan', 'Notes', 'Links'], dtype='str')
bruenn_ charlotte_IS_S_00027/chronotopi_charlotte_bruenn_IS_S_00027 (file revisionato).xlsx Margot Hirsch Index(['Event', 'Location', 'Timespan', 'Notes', 'Links'], dtype='str')
stern_IS_S_00142/chronotopi_josef_stern_IS_S_00142.xlsx Josef Stern Index(['Event', 'Location', 'Timespan', 'Notes', 'Links'], dtype='str')
stern_IS_S_00142/chronotopi_josef_stern_IS_S_00142.xlsx Julius Stern Index(['Event', 'Location', 'Timespan', 'Notes', 'Links'], dtype='str')
stern_IS_S_00142/chronotopi_josef_stern_IS_S_00142.xlsx Esther Stern Index(['Event', 'Location', 'Timespan', 'Notes', 'Links'], dtype='str')
stern_IS_S_00142/chronotopi_josef_stern_IS_S_00142.xlsx Sonja Stern Index(['Event', 'Location', 'Timespan', 'Notes', 'Links'], dtype='str')
stern_IS_S_00142/chronotopi_josef_stern_IS_S_00142.xlsx Großvater M David Kaminka Index(['Event', 'Location', 'Timespan', 'Notes', 'Links'], dtype='str')
stern_IS_S_00142/chronotopi_josef_stern_IS_S_00142.xlsx Großmutter M Betty Kaminka geb. Index(['Event', 'Location', 'Timespan', 'Notes', 'Links'], dtype='str')
stern_IS_S_00142/chronotopi_josef_stern_IS_S_00142.xlsx Großvater V Isaak Stern Index(['Event', 'Location', 'Timespan', 'Notes', 'Links'], dtype='str')
stern_IS_S_00142/chronotopi_josef_stern_IS_S_00142.xlsx Großmutter V Auguste Stern geb  Index(['Event', 'Location', 'Timespan', 'Notes', 'Links'], dtype='str')
stern_IS_S_00142/chronotopi_josef_stern_IS_S_00142.xlsx Mutter 2 Claire Stern Index(['Event', 'Location', 'Timespan', 'Notes', 'Links'], dtype='str')

,event,location,timespan,notes,links,protagonist,name
0,Lebenslauf - Geburt / Alter Heimat,\t\nAllenstein (Ostpreußen)https://www.geoname...,19. Januar 1913,,,bruenn_jehoshua_IS_S_00028,Foglio1
1,Lebenslauf - Tod des Vaters,Allenstein,1923,24min01s. - 24min04s.,,bruenn_jehoshua_IS_S_00028,Foglio1
2,Lebenslauf - Schuljahren (Realschule),Allenstein,ca. 1927/1928,"Zuerst christliche Volksschule, dann (von der ...",,bruenn_jehoshua_IS_S_00028,Foglio1
3,Lebenslauf - Kaufmännische Lehre,Allenstein,1931,,,bruenn_jehoshua_IS_S_00028,Foglio1
4,Lebenslauf - Militärversuch,Allenstein,1931,Er hat 3 Jahren bei Frankenstein & Co (Warenha...,,bruenn_jehoshua_IS_S_00028,Foglio1
...,...,...,...,...,...,...,...
1,Deportation,Gießen https://www.wikidata.org/wiki/Q7904 Wal...,16.9.1942\n,,,stern_IS_S_00142,Mutter 2 Claire Stern
2,Transport (Abfahrt),Darmstadt https://www.wikidata.org/wiki/Q2973 ...,1942-09-30 00:00:00,,https://memoryoftreblinka.org/transports-to-tr...,stern_IS_S_00142,Mutter 2 Claire Stern
3,Transport (Ankunft),Treblinka https://www.wikidata.org/wiki/Q15201...,1942-10-02 00:00:00,,,stern_IS_S_00142,Mutter 2 Claire Stern
4,Mord,Treblinka https://www.wikidata.org/wiki/Q15201...,1942,Stolperstein Gießen,https://collections.yadvashem.org/en/names/135...,stern_IS_S_00142,Mutter 2 Claire Stern
5,Erinnerung: Stolperstein,Gießen Marktplatz 15,2008-04-26 00:00:00,,https://www.giessen.de/Erleben/Über-Gießen/Sto...,stern_IS_S_00142,Mutter 2 Claire Stern

# Locations

In [7]:
# locs = {n:l for l, n in df["location"].apply(lambda x: extract_urls(x)).to_list()}
locs = {}
for row in tqdm(df["location"]):
    # print(row)
    # print(extract_urls(row))
    for name, urls in extract_urls(row):
        urls["location"] = name
        locs[name] = urls
# print(locs)

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 153/153 [00:00<00:00, 6140.53it/s]

## Update preexisting locations

In [8]:
rich = pd.read_excel("locations.xlsx")
rich = rich.set_index(["location"])
rich
for location, row in locs.items():
    if location not in rich.index:
        print(location)
        rich.loc[location] = locs[location]
rich
rich.to_excel("locations.xlsx")

Berling (Kolonnenstraße)
Palästina (über Marseille)
Ägypten/Irak/Iran

von Homburg (Saar) nach Nyons, Südfrankreich (bei Avignon)
Nyons Südfrankreich
Nyons, Südfrankreich
Israel (Ramatayim / Ramat HaSharon)
vermutlich Homburg (Saar)
von Homburg nach Südfrankreich (bei Avignon)
von Homburg (Saar) nach Südfrankreich (bei Avignon)
Südfrankreich?
aus dem Kibbuz ausgewiesen
Italien Deutschland Belgien Niederlande
Verkehrsmittel > Zug Klein Linden
Gießen  Walltorstraße 48 Darmstadt
aus Gießen nach Palästina
Von Berlin nach Theresienstadt

# Events

TODO: incomplete due to too much noise. Issues:

- use LL or Lebenslauf, currently extracted as one, but need to be two equivalent
- "alter heimant" instread of "alte heimat"
- "Transport", "Tod des Vaters",  are not label

In [9]:
event_taxonomy = parse_mmd_taxonomy("../model/tassonomia.mmd")
events = sorted(set(event_taxonomy.keys()), key=lambda x: -len(x))
len(events), events[:5] + ["..."] + events[-5:]

(340,
 ['Città/regioni tedesche, austriache, ceche',
  'SR – Spazi sociali / istituzioni',
  'Friedrichswerdersche Gymnasium',
  'Europa – altri paesi e luoghi',
  'Gymnasium zum Grauen Kloster',
  '...',
  'USA',
  'IPD',
  'Tod',
  'Zug',
  'SPD'])

In [10]:
df["events"] = df["event"].apply(lambda x: extract_events(x, events))
df

,event,location,timespan,notes,links,protagonist,name,events
0,Lebenslauf - Geburt / Alter Heimat,\t\nAllenstein (Ostpreußen)https://www.geoname...,19. Januar 1913,,,bruenn_jehoshua_IS_S_00028,Foglio1,"[Geburt, Lebenslauf - / Alter Heimat]"
1,Lebenslauf - Tod des Vaters,Allenstein,1923,24min01s. - 24min04s.,,bruenn_jehoshua_IS_S_00028,Foglio1,"[Tod, Lebenslauf - des Vaters]"
2,Lebenslauf - Schuljahren (Realschule),Allenstein,ca. 1927/1928,"Zuerst christliche Volksschule, dann (von der ...",,bruenn_jehoshua_IS_S_00028,Foglio1,"[Realschule, Lebenslauf - Schuljahren ()]"
3,Lebenslauf - Kaufmännische Lehre,Allenstein,1931,,,bruenn_jehoshua_IS_S_00028,Foglio1,[Lebenslauf - Kaufmännische Lehre]
4,Lebenslauf - Militärversuch,Allenstein,1931,Er hat 3 Jahren bei Frankenstein & Co (Warenha...,,bruenn_jehoshua_IS_S_00028,Foglio1,[Lebenslauf - Militärversuch]
...,...,...,...,...,...,...,...,...
1,Deportation,Gießen https://www.wikidata.org/wiki/Q7904 Wal...,16.9.1942\n,,,stern_IS_S_00142,Mutter 2 Claire Stern,[Deportation]
2,Transport (Abfahrt),Darmstadt https://www.wikidata.org/wiki/Q2973 ...,1942-09-30 00:00:00,,https://memoryoftreblinka.org/transports-to-tr...,stern_IS_S_00142,Mutter 2 Claire Stern,"[Abfahrt, Transport ()]"
3,Transport (Ankunft),Treblinka https://www.wikidata.org/wiki/Q15201...,1942-10-02 00:00:00,,,stern_IS_S_00142,Mutter 2 Claire Stern,"[Ankunft, Transport ()]"
4,Mord,Treblinka https://www.wikidata.org/wiki/Q15201...,1942,Stolperstein Gießen,https://collections.yadvashem.org/en/names/135...,stern_IS_S_00142,Mutter 2 Claire Stern,[Mord]
5,Erinnerung: Stolperstein,Gießen Marktplatz 15,2008-04-26 00:00:00,,https://www.giessen.de/Erleben/Über-Gießen/Sto...,stern_IS_S_00142,Mutter 2 Claire Stern,"[Erinnerung, : Stolperstein]"

# Timespan

In [11]:
df[["time_start", "time_end"]] = (
    df["timespan"].apply(lambda ts: list(parse_timespan(ts).as_tuple())).tolist()
)
df

,event,location,timespan,notes,links,protagonist,name,events,time_start,time_end
0,Lebenslauf - Geburt / Alter Heimat,\t\nAllenstein (Ostpreußen)https://www.geoname...,19. Januar 1913,,,bruenn_jehoshua_IS_S_00028,Foglio1,"[Geburt, Lebenslauf - / Alter Heimat]",1913-01-19,1913-01-19
1,Lebenslauf - Tod des Vaters,Allenstein,1923,24min01s. - 24min04s.,,bruenn_jehoshua_IS_S_00028,Foglio1,"[Tod, Lebenslauf - des Vaters]",1923-01-01,1923-12-31
2,Lebenslauf - Schuljahren (Realschule),Allenstein,ca. 1927/1928,"Zuerst christliche Volksschule, dann (von der ...",,bruenn_jehoshua_IS_S_00028,Foglio1,"[Realschule, Lebenslauf - Schuljahren ()]",1927-01-01,1928-12-31
3,Lebenslauf - Kaufmännische Lehre,Allenstein,1931,,,bruenn_jehoshua_IS_S_00028,Foglio1,[Lebenslauf - Kaufmännische Lehre],1931-01-01,1931-12-31
4,Lebenslauf - Militärversuch,Allenstein,1931,Er hat 3 Jahren bei Frankenstein & Co (Warenha...,,bruenn_jehoshua_IS_S_00028,Foglio1,[Lebenslauf - Militärversuch],1931-01-01,1931-12-31
...,...,...,...,...,...,...,...,...,...,...
1,Deportation,Gießen https://www.wikidata.org/wiki/Q7904 Wal...,16.9.1942\n,,,stern_IS_S_00142,Mutter 2 Claire Stern,[Deportation],1942-09-16,1942-09-16
2,Transport (Abfahrt),Darmstadt https://www.wikidata.org/wiki/Q2973 ...,1942-09-30 00:00:00,,https://memoryoftreblinka.org/transports-to-tr...,stern_IS_S_00142,Mutter 2 Claire Stern,"[Abfahrt, Transport ()]",1942-09-30,1942-09-30
3,Transport (Ankunft),Treblinka https://www.wikidata.org/wiki/Q15201...,1942-10-02 00:00:00,,,stern_IS_S_00142,Mutter 2 Claire Stern,"[Ankunft, Transport ()]",1942-10-02,1942-10-02
4,Mord,Treblinka https://www.wikidata.org/wiki/Q15201...,1942,Stolperstein Gießen,https://collections.yadvashem.org/en/names/135...,stern_IS_S_00142,Mutter 2 Claire Stern,[Mord],1942-01-01,1942-12-31
5,Erinnerung: Stolperstein,Gießen Marktplatz 15,2008-04-26 00:00:00,,https://www.giessen.de/Erleben/Über-Gießen/Sto...,stern_IS_S_00142,Mutter 2 Claire Stern,"[Erinnerung, : Stolperstein]",2008-04-26,2008-04-26

# Notes

left unprocessed for now

In [12]:
set(df["notes"])

{'',
 ' ',
 ' („so eine Art Hachschara“)',
 ' Bruder nach Oslo',
 ' Scheda Lea - lebte unter falschem Namen „Alexandre Hilaire“ ',
 ' falscher Name „Marguerite Hilaire“ - Scheda LEA',
 ' starb schwer krank, nicht durch NS-Verfolgung  (Interview)',
 '(Fragebogen)',
 '(Fragebogen):',
 '(Gedenkblatt)',
 '(Interview Metz)',
 '1973: Jom Kippur Krieg ',
 '20 min 56',
 '22min 0s ',
 '24min01s. - 24min04s.',
 '26min 58s',
 '29min 04',
 '30min 57s',
 '31min 31s',
 '31min 58s',
 '32min 16s',
 '36min 51smein mittlerer Bruder weiß man bis heut nicht, er ist umgekommen, er war damals neunzehn Jahre in in Homburg + . Man hat ihn unter der Eisenbahn gefunden, man weiß bis heute nicht, ja. Das war diese Zeit, . Scheda LEA: 27.02.1936 mit den Eltern nach Nyons ausgewandert (https://gedenkbuch.saarbruecken.de/en/memorial_book/person_details/person-1182) Death 24 May 1935 Homburg, Saarpfalz\nSuicide',
 '39-40 CB: Fünfunddreißig nach der Abstimmung wie die Saar wurde deutsch und sind wir gleich',
 '39-40 CB: Fünfunddreißig nach der Abstimmung wie die Saar wurde deutsch und sind wir gleich (Interview)',
 '39min 44s',
 '40 weggegangen noch mit unsere Sachen alles. Scheda LEA: 27.02.1936 mit den Eltern nach Nyons ausgewandert ',
 '40 weggegangen noch mit unsere Sachen alles. Scheda LEA: 27.02.1936 mit den Eltern nach Nyons ausgewandert (https://gedenkbuch.saarbruecken.de/en/memorial_book/person_details/person-1182)',
 'Am Anfang mit der Tante Betty',
 'April (wahrscheinlich) - strittiger Punkt',
 'Arbeit beim Dr. Blumenthal',
 'Arbeit in einem Restaurant',
 'Arbeiter bei den Bauern',
 'Beruf: Kaufhaus für Konfektion (kurze Zeit). Dann kam er nach Berlin, weil seine Schwester als Modezeichnerin dort arbeitete.',
 'Besuch des Grabes von Heinrich Heine. Dort trifft er sich mit seinem anderen Bruder',
 'Der Brufer empfängt ihn. Am Bahnhof lacht der Kartenverkäufer wegen Jehoschuas Berliner Dialekts',
 'Diskrepanz zwischen Inteview und Gedenkbuch',
 'Eisernes Kreuz',
 'Entscheidung für Palästina; Vorbereitung der Ausreise',
 'Er hat 3 Jahren bei Frankenstein & Co (Warenhaus) gearbeitet. ',
 'Er hatte einen Bauernschwager in Siemenstadt, also ist er eine Woche lang bei ihm geblieben. Inzwischen kam sein Bruder.',
 'Fragebogen',
 'Fragebogen ',
 'Interview',
 'Interview  / Scheda LEA - wh. Nyons/Drôme, Villa Les feures bleues [sic]',
 'Interview Metz',
 'Interview. Es ist nicht eindeutig, ob sich die Aussage auf Margot oder auf Alice bezieht. In der LEA-Akte zu Margot wird Marseille nicht erwähnt; dort heißt es nur, dass sie zusammen mit ihren Eltern zwei Jahre bei einem Bauern in den Alpen versteckt war (die Kosten dafür übernahm ihr Bruder Erich).',
 'Intervista - 40 weggegangen noch mit unsere Sachen alles. Scheda LEA: 27.02.1936 mit den Eltern nach Nyons ausgewandert ',
 'Intervista - mein jüngster Bruder, der war damals achtzehn, neunzehn Jahr, genau weiß ich nicht mehr, hat er sich zur französischen Armee gemeldet, hat man ihn genommen, hat man gesagt, er wär die fünfte Kolonn, hab ich das erste Mal in meinem Leben gesehen ein ein Lager, Intern/ ähm + er war interniert',
 'LEA',
 'Mit seinem Bruder, der  in englischer Uniform kam nach En-Charod (er kam aus Basra). Er lernt English besser als in der Schule',
 'Paratyphus',
 'Pardess Katz b/Tel-Aviv, Shikun Jessodoth 5, Israel',
 'RS / Archivdaten',
 'Scheda Aj',
 'Scheda LEA',
 'Scheda LEA  ',
 'Scheda LEA: 26. August 1942 - August 1944: Inhaftierung der Mutter / 9413 Bl 62: 16.08.1942 verhaftet in Nyons/Drôme von frz. Polizei, Sammellager Crest/Drôme n. Lyon-Vénissieux, von dort entflohen',
 'Scheda LEA: 26. August 1942 - August 1944: Inhaftierung der Mutter, Leben in Illegalität in Nyons, Pampignan, Sahume, Drome, Krankheiten',
 'Scheda Lea',
 'Scheda Lea ',
 'Scheda Lea - Betrieb in Nyons einen Handel mit Vieh und Milcherzeugnissen, lebte von Mitte 1942 bis Ende September 1944 illegal',
 'Scheda ML - Emigration 27.02.1936 nach Frankreich. Verw: Erich, Margot und Alfons Justin Hirsch, sowie Alice Estryn geb. Hirsch und Charlotte Brünn geb. Hirsch nach ihrem Vater; wh. Nyons/Drôme, Villa Les feures bleues [sic]',
 'Schillerschule (Volksschule)\xa0\n\n',
 'Stolperstein Gießen',
 'Umzug  auf Anfrage der Polizei',
 'Zuerst christliche Volksschule, dann (von der None ab) Realschule. Das Datu, bezieht sich auf die Realschule',
 'auf dem Schiff war auch eine Prinzessin, eine Schwester von König Faruk',
 'der fünfte Zionistenkongress',
 'die schönsten jahre habe ich ja im versteck 33min 01s',
 'https://gedenkbuch.saarbruecken.de/gedenkbuch/personen_detailseite/person-3855',
 'im Unternehmen (Keller)',
 'zur Tochter Martha – Ihre 4-Zimmer-Wohnung befand sich dort im Vorderhaus im dritten Stock'}

# Links

left unprocessed for now

In [13]:
set(df["links"])

{'',
 '\nhttps://collections.yadvashem.org/en/names/13219727 Esther-Stern-Platz Gießen  https://www.lotta-magazin.de/ausgabe/1/den-ermordeten-menschen-ein-gesicht-geben/ \n',
 '\nhttps://www.giessen.de/index.php?ModID=7&FID=2874.2967.1&object=tx%2C2874.2967.1 ',
 ' https://gedenkbuch.saarbruecken.de/en/memorial_book/person_details/person-1182',
 ' https://gedenkbuch.saarbruecken.de/gedenkbuch/personen_detailseite/person-3895',
 'Bahnof? https://www.wikidata.org/wiki/Q2915713',
 "Informazione che non compare nell'intervista, ma documentata nella scheda LEA: https://gedenkbuch.saarbruecken.de/en/memorial_book/person_details/person-1182",
 'Nell\'intervista C. dice "Mit 26 Jahren" (ergo nel 1949), ma in altre fonti risulta che si è sposata nel 1951 (Scheda LEA: https://gedenkbuch.saarbruecken.de/en/memorial_book/person_details/person-1182; © Institut für Deutsche Sprache, Mannheim 2013)',
 'http://www.ajpn.org/personne-Charlotte-Hirsch-10313.html https://gedenkbuch.saarbruecken.de/en/memorial_book/person_details/person-1182',
 'https://atom.lib.uct.ac.za/uploads/r/university-of-cape-town-libraries-special-collections/a/3/c/a3cc8572f727d61327e4f929a86fc91c339c13cc41721aa18c8f158e13678891/mss_sahgf_schragenheim_publications_025_1-20.pdf',
 'https://collections.yadvashem.org/en/names/13571207\n\n',
 'https://de.wikipedia.org/wiki/Datei:Stolperstein_Gießen_Nordanlage_Esther_Stern.JPG\nhttps://www.giessen.de/index.php?ModID=7&FID=2874.2967.1&object=tx%2C2874.2967.1 ',
 'https://gedenkbuch.saarbruecken.de/en/memorial_book/person_details/person-1182',
 'https://gedenkbuch.saarbruecken.de/en/memorial_book/person_details/person-1183',
 'https://gedenkbuch.saarbruecken.de/en/memorial_book/person_details/person-3992',
 'https://gedenkbuch.saarbruecken.de/en/memorial_book/person_details/person-3997',
 'https://gedenkbuch.saarbruecken.de/gedenkbuch/personen_detailseite/person-3855',
 'https://gedenkbuch.saarbruecken.de/gedenkbuch/personen_detailseite/person-3920 / https://gedenkbuch.saarbruecken.de/en/memorial_book/person_details/person-1182',
 'https://gedenkbuch.saarbruecken.de/gedenkbuch/personen_detailseite/person-3920%20/',
 'https://gedenkbuch.saarbruecken.de/gedenkbuch/personen_detailseite/person-3997',
 'https://memoryoftreblinka.org/transports-to-treblinka',
 'https://memoryoftreblinka.org/transports-to-treblinka/',
 'https://secure.ushmm.org/online/hsv/person_view.php?PersonId=9230184',
 'https://www.ajpn.org/juste-Marie-Fenayrol-1068.html https://gedenkbuch.saarbruecken.de/en/memorial_book/person_details/person-1182; ',
 'https://www.ancestry.co.uk/genealogy/records/isaak-stern-24-39m6wh9',
 'https://www.facebook.com/groups/nyonsaujourdhui/posts/1239122821734315/',
 'https://www.giessen.de/Erleben/Über-Gießen/Stolpersteine/Marktplatz-15.php?object=tx,2874.1320.1&ModID=7&FID=2874.1260.1&NavID=2874.396&La=1',
 'https://www.giessen.de/index.php?ModID=7&FID=2874.1260.1&object=tx%2C2874.1260.1',
 'https://www.giessen.de/index.php?ModID=7&FID=2874.2939.1&object=tx%7C2874.2939.1',
 'https://www.giessen.de/index.php?ModID=7&FID=2874.2939.1&object=tx%7C2874.2939.1 ',
 'https://www.giessen.de/index.php?ModID=7&FID=2874.2967.1&object=tx%2C2874.2967.1 ',
 'https://www.giessener-allgemeine.de/giessen/die-familien-stern-und-kaminka-91501336.html',
 'https://www.lotta-magazin.de/ausgabe/1/den-ermordeten-menschen-ein-gesicht-geben/ ',
 'https://www.stolpersteine-berlin.de/de/wullenweberstr/11/auguste-stern',
 'https://www.stolpersteine-berlin.de/de/wullenweberstr/11/auguste-stern\n\nTransport I/53 from Berlin,Berlin (Berlin),City of Berlin,Germany to Theresienstadt,Ghetto,Czechoslovakia on 27/08/1942\nhttps://collections.yadvashem.org/en/names/13540314\nhttps://collections.yadvashem.org/en/names/1189610 ',
 'https://www.stolpersteine-berlin.de/de/wullenweberstr/11/martha-katz '}