In [18]:
from glob import glob
import pandas as pd
from tqdm import tqdm

from utils import extract_url_map
from events import extract_events
from timespan import parse_timespan
from taxonomy import load_taxonomy

In [19]:
root_path = "../data/schede mappatura/"

skip = {
    # "david_ruth_FEGB_E_00007": {"rows": 6, "cols": 1}
    "stern_IS_S_00142": {"rows": 2, "cols": 0},
}

In [20]:
chrono_schede = glob(f"{root_path}*/chronotop*")
chrono_schede = [c for c in chrono_schede if not c.endswith(":Zone.Identifier")]
chrono_schede

['../data/schede mappatura/0_template/chronotopoi_template.xlsx',
 '../data/schede mappatura/bruenn_ charlotte_IS_S_00027/chronotopi_charlotte_bruenn_IS_S_00027 (file revisionato).xlsx',
 '../data/schede mappatura/stern_IS_S_00142/chronotopoi_josef_stern_familie_v4.xlsx',
 '../data/schede mappatura/bruenn_jehoshua_IS_S_00028/chronotopoi_bruenn_jehoshua_bozza.xlsx',
 '../data/schede mappatura/david_ruth_FEGB_E_00007/chronotopi_ruth_david_FEGB_E_00007.xlsx']

## A list of individual sources for experimentation

ignored in the oveall logic

In [21]:
# current = "bruenn_jehoshua_IS_S_00028/chronotopoi_bruenn_jehoshua_bozza.xlsx"
# current = "david_ruth_FEGB_E_00007/chronotopi_ruth_david_FEGB_E_00007.xlsx"
# current = "bruenn_ charlotte_IS_S_00027/chronotopi_charlotte_bruenn_IS_S_00027 (file revisionato).xlsx"
# current = "stern_IS_S_00142/chronotopi_josef_stern_IS_S_00142.xlsx"
current = "stern_IS_S_00142/chronotopoi_josef_stern_familie_v4.xlsx"

chrono_schede = [s for s in chrono_schede if current in s]
chrono_schede

['../data/schede mappatura/stern_IS_S_00142/chronotopoi_josef_stern_familie_v4.xlsx']

import openpyxl

overview = {}
for s in chrono_schede:
    wb = openpyxl.load_workbook(s)
    overview[s] = wb.sheetnames
overview

After identification of all sources

# Shortlist processable sources

In [22]:
overview = {
    "stern_IS_S_00142/chronotopoi_josef_stern_familie_v4.xlsx": [
        "Josef Stern",
    ],
}

## Put all data together

In [23]:
first = True
df_list = []
for k, v in overview.items():
    for s in v:
        name = k.split("/")[0]
        # print(k,s)
        if name in skip:
            df = pd.read_excel(
                root_path + k, sheet_name=s, skiprows=skip[name]["rows"]
            ).iloc[:, skip[name]["cols"] :]
        else:
            df = pd.read_excel(root_path + k, sheet_name=s)

        print(k, s, df.columns)
        df.columns = [
            "event_label",
            "event_type",
            "place_name",
            "place_type",
            "place_category",
            "wikidata_qid",
            "geonames_id",
            "google maps",
            "date_certainty",
            "date_label",
            "memorial_inscription",
            "source_doc",
            "source_timecode",
            "source_quote",
            "external_links",
            "notes",
        ]

        # merge columns 6+ to notes
        df["notes"] = df[["notes"] + list(df.columns[6:])].apply(
            lambda row: " ".join(row.dropna().astype(str)), axis=1
        )
        # df = df.drop(df.columns[6:], axis=1)

        df["protagonist"] = name
        df["name"] = s
        df_list += [df]
df = pd.concat(df_list, axis=0).astype(str)
df.fillna("", inplace=True)

# Track start/end locations: end_location = current row's place,
# start_location = previous event's place (per person)
start_locations = []
prev_location = {}  # protagonist → last place_name
for _, row in df.iterrows():
    person = row["protagonist"]
    end_loc = row["place_name"].strip()
    start_loc = prev_location.get(person, end_loc)  # fallback to same as end
    start_locations.append(start_loc)
    if end_loc:
        prev_location[person] = end_loc
df["start_location"] = start_locations
df["end_location"] = df["place_name"]

# Collect concepts from event_type, place_type, place_category
concept_labels = set()
for col in ["event_type", "place_type", "place_category"]:
    for val in df[col]:
        v = val.strip()
        if v and v not in ("nan", "None"):
            concept_labels.add(v)
print(f"Concepts to create: {sorted(concept_labels)}")

df

stern_IS_S_00142/chronotopoi_josef_stern_familie_v4.xlsx Josef Stern Index(['event_label', 'event_type', 'place_name', 'place_type',
       'place_category', 'wikidata_qid', 'geonames_id', 'google maps',
       'date_certainty', 'date_label', 'memorial_inscription', 'source_doc',
       'source_timecode', 'source_quote', 'external_links', 'notes'],
      dtype='str')
Concepts to create: ['Bahnhof', 'Ghettohaus', 'Schiff', 'Synagoge', 'Telephon im Ghettohaus', 'Zug', 'alte_heimat', 'birth', 'education', 'emigration', 'emigration_transit', 'farewell', 'forced_eviction', 'immigration', 'marriage', 'military_service', 'neue_heimat', 'notification', 'ort_der_zeit', 'reise_zurueck', 'residence', 'return_visit', 'return_visit_transit', 'verkehrsmittel', 'work']

,event_label,event_type,place_name,place_type,place_category,wikidata_qid,geonames_id,google maps,date_certainty,date_label,memorial_inscription,source_doc,source_timecode,source_quote,external_links,notes,protagonist,name,start_location,end_location
0,Alte Heimat Geburt,birth,"Gießen, Marktplatz 11",,alte_heimat,Q564579,2920512.0,,certain,15/06/1921,,,,,https://www.geonames.org/2920512/giessen.html\...,2920512.0 certain 15/06/1921 https://www.geona...,stern_IS_S_00142,Josef Stern,"Gießen, Marktplatz 11","Gießen, Marktplatz 11"
1,Alte Heimat Grundschule,education,Gießen,,alte_heimat,,,,probable,1928-1932,,,,,,probable 1928-1932,stern_IS_S_00142,Josef Stern,"Gießen, Marktplatz 11",Gießen
2,Alte Heimat Realgymnasium,education,Gießen,,alte_heimat,,,,uncertain,1932- Winter 1935,,,,,,uncertain 1932- Winter 1935,stern_IS_S_00142,Josef Stern,Gießen,Gießen
3,Wohnort,residence,Löberstraße 20,,alte_heimat,,,,uncertain,1933?,,,,,https://www.giessen.de/index.php?ModID=7&FID=2...,Aufräumung v4: place_name korrigiert von 'Löbe...,stern_IS_S_00142,Josef Stern,Gießen,Löberstraße 20
4,Abgang von der Schule,education,Gießen,,alte_heimat,,,,probable,1935,,,29min 04,,,probable 1935 29min 04,stern_IS_S_00142,Josef Stern,Löberstraße 20,Gießen
5,Wohnort,residence,"Ghettohaus, Walltorstraße 48",Ghettohaus,alte_heimat,,,,probable,ab 1935,,,,,https://www.giessen.de/index.php?ModID=7&FID=2...,probable ab 1935 https://www.giessen.de/index....,stern_IS_S_00142,Josef Stern,Gießen,"Ghettohaus, Walltorstraße 48"
6,Hachschara,education,Schlesien,,alte_heimat,,,,probable,1935,,,30min 57s,,,probable 1935 30min 57s,stern_IS_S_00142,Josef Stern,"Ghettohaus, Walltorstraße 48",Schlesien
7,Bei Verwandten,residence,Berlin,,alte_heimat,Q64,2950159.0,,probable,1935,,,31min 31s,,https://www.wikidata.org/wiki/Q64\nhttps://www...,2950159.0 probable 1935 31min 31s https://www....,stern_IS_S_00142,Josef Stern,Schlesien,Berlin
8,Jeschiwa,education,"Synagoge am Börneplatz, Frankfurt/M",Synagoge,alte_heimat,Q111620976,6553153.0,,probable,1936,,,,,https://www.wikidata.org/wiki/Q111620976\nhttp...,31min 58s — [Hinweis: Zerstört im Novemberpogr...,stern_IS_S_00142,Josef Stern,Berlin,"Synagoge am Börneplatz, Frankfurt/M"
9,Abfahrt > Abschied von den Eltern,farewell,"Bahnhof, Frankfurt am Main",Bahnhof,alte_heimat,Q1794,6553153.0,,probable,1936,,,,,https://www.wikidata.org/wiki/Q1794\nhttps://w...,6553153.0 probable 1936 https://www.wikidata.o...,stern_IS_S_00142,Josef Stern,"Synagoge am Börneplatz, Frankfurt/M","Bahnhof, Frankfurt am Main"
10,Auswanderung,emigration_transit,Frankfurt (Main) Hauptbahnhof,Zug,verkehrsmittel,Q165368,6290300.0,,probable,1936,,,32min 16s,,https://www.wikidata.org/wiki/Q165368\nhttps:/...,6290300.0 probable 1936 32min 16s https://www....,stern_IS_S_00142,Josef Stern,"Bahnhof, Frankfurt am Main",Frankfurt (Main) Hauptbahnhof
11,Auswanderung,emigration_transit,Kehl am Rhein,Zug,verkehrsmittel,Q15979,2891951.0,,probable,1936,,,,,https://www.wikidata.org/wiki/Q15979\nhttps://...,2891951.0 probable 1936 https://www.wikidata.o...,stern_IS_S_00142,Josef Stern,Frankfurt (Main) Hauptbahnhof,Kehl am Rhein
12,Auswanderung,emigration_transit,Brücke Kehl–Straßburg (Rheinquerung),Zug,verkehrsmittel,Q1375288,,,probable,1936,,,,,https://www.wikidata.org/wiki/Q1375288,Heutige Europabrücke ab 1960; 1936 nutzte Ster...,stern_IS_S_00142,Josef Stern,Kehl am Rhein,Brücke Kehl–Straßburg (Rheinquerung)
13,Auswanderung,emigration_transit,Marseille,Zug,verkehrsmittel,Q23482,2995469.0,,probable,1936,,,,,https://www.wikidata.org/wiki/Q23482\nhttps://...,2995469.0 probable 1936 https://www.wikidata.o...,stern_IS_S_00142,Josef Stern,Brücke Kehl–Straßburg (Rheinquerung),Marseille
14,Auswanderung,emigration,Marseille,Schiff,verkehrsmittel,,,,probable,1936,,,,,,probable 1936,stern_IS_S_00142,Josef Stern,Marseille,Marseille
15,Neue Heimat\nEinwanderung,immigration,"Kibbuz Rodges, besteht nicht mehr (in der Nähe...",,neue_heimat,,,,probable,1936-38,,,,,,probable 1936-38,stern_IS_S_00142,Josef Stern,Marseille,"Kibbuz Rodges, besteht nicht mehr (in der Nähe..."
16,Neue Heimat\n\nReise durchs Land,residence,Ēmeq Yizrəʿēl,,neue_heimat,Q763829,293165.0,,probable,1937,,,,,https://www.wikidata.org/wiki/Q763829\nhttps:/...,Jesreelebene 293165.0 probable 1937 https://ww...,stern_IS_S_00142,Josef Stern,"Kibbuz Rodges, besteht nicht mehr (in der Nähe...",Ēmeq Yizrəʿēl
17,Neue Heimat,residence,Kibbuz Ein HaNetziv,,neue_heimat,Q2095906,295211.0,,uncertain,1938-194?,,,,,https://www.wikidata.org/wiki/Q2095906\nhttps:...,aus dem Kibbuz ausgewiesen 295211.0 uncertain ...,stern_IS_S_00142,Josef Stern,Ēmeq Yizrəʿēl,Kibbuz Ein HaNetziv
18,Neue Heimat,residence,Haifa,,neue_heimat,Q41621,294801.0,,uncertain,194?–,,,,,https://www.geonames.org/294801/haifa.html\nht...,Fabrik in der Nähe von Haifa 294801.0 uncertai...,stern_IS_S_00142,Josef Stern,Kibbuz Ein HaNetziv,Haifa
19,Neue Heimat,residence,Kibbuz Tirat Tsvi,,neue_heimat,Q550025,293304.0,,uncertain,1940-1944,,,,,https://www.wikidata.org/wiki/Q550025\nhttps:/...,293304.0 uncertain 1940-1944 https://www.wikid...,stern_IS_S_00142,Josef Stern,Haifa,Kibbuz Tirat Tsvi
20,Reise zurück als Soldat,military_service,Italien,,reise_zurueck,,,,probable,1944,,,,,,probable 1944,stern_IS_S_00142,Josef Stern,Kibbuz Tirat Tsvi,Italien
21,Reise zurück als Soldat,military_service,Deutschland,,reise_zurueck,,,,probable,1944,,,,,,probable 1944,stern_IS_S_00142,Josef Stern,Italien,Deutschland
22,Reise zurück als Soldat,military_service,Belgien,,reise_zurueck,,,,probable,1944,,,,,,probable 1944,stern_IS_S_00142,Josef Stern,Deutschland,Belgien
23,Reise zurück als Soldat,military_service,Niederlande,,reise_zurueck,,,,probable,1944,,,,,,probable 1944,stern_IS_S_00142,Josef Stern,Belgien,Niederlande
24,Neue Heimat\nHeirat,marriage,Haifa,,neue_heimat,,,,uncertain,,,,,,,uncertain,stern_IS_S_00142,Josef Stern,Niederlande,Haifa
25,Neue Heimat\nHaifa\nBeruf,work,"Haifa, Universität, Bibliothek",,neue_heimat,,,,probable,1966–1986,,,,,,probable 1966–1986,stern_IS_S_00142,Josef Stern,Haifa,"Haifa, Universität, Bibliothek"
26,Reise zurück,return_visit_transit,Gießen,,reise_zurueck,Q564579,2920512.0,,probable,1975,,,,,https://www.geonames.org/2920512/giessen.html\...,2920512.0 probable 1975 https://www.geonames.o...,stern_IS_S_00142,Josef Stern,"Haifa, Universität, Bibliothek",Gießen
27,Fahrt Frankfurt-Gießen,return_visit_transit,Frankfurt am Main,Zug,reise_zurueck,Q1794,6553153.0,,,,,,,,https://www.wikidata.org/wiki/Q1794\nhttps://w...,6553153.0 https://www.wikidata.org/wiki/Q1794\...,stern_IS_S_00142,Josef Stern,Gießen,Frankfurt am Main
28,Klein Linden,return_visit_transit,Klein-Linden,Zug,reise_zurueck,Q1571834,2888549.0,,,,,,,,https://www.wikidata.org/wiki/Q1571834\nhttps:...,2888549.0 https://www.wikidata.org/wiki/Q15718...,stern_IS_S_00142,Josef Stern,Frankfurt am Main,Klein-Linden
29,Großen-Linden,return_visit,Großen-Linden,Zug,reise_zurueck,Q116016915,11974166.0,,,,,,,,https://www.wikidata.org/wiki/Q116016915\nhttp...,11974166.0 https://www.wikidata.org/wiki/Q1160...,stern_IS_S_00142,Josef Stern,Klein-Linden,Großen-Linden
30,Geburtshaus Marktplatz 11,return_visit_transit,"Marktplatz 11, Giessen",Zug,reise_zurueck,,,,,,,,,,,Geburtshaus Geburtshaus,stern_IS_S_00142,Josef Stern,Großen-Linden,"Marktplatz 11, Giessen"
31,Aliyah-Anruf,notification,"Gießen, Walltorstraße 48",Telephon im Ghettohaus,alte_heimat,Q564579,2920512.0,,probable,1936,,Interview Metz 2010,30min 15s,"Ich bekam einen Anruf am Telefon in dem Haus, ...",,Chronotopos im engeren Sinn: Ort (Walltorstraß...,stern_IS_S_00142,Josef Stern,"Marktplatz 11, Giessen","Gießen, Walltorstraße 48"
32,Zwangsausweisung Marktplatz 11,forced_eviction,"Gießen, Marktplatz 11",,ort_der_zeit,Q564579,2920512.0,,probable,1933,,Interview Metz 2010,11min 47s,Wir sind allerdings aus diesem schönen Haus gl...,,Josef war 12 Jahre alt. Erstes durch ihn erinn...,stern_IS_S_00142,Josef Stern,"Gießen, Walltorstraße 48","Gießen, Marktplatz 11"

# Locations

In [24]:
# locs = {n:l for l, n in df["location"].apply(lambda x: extract_urls(x)).to_list()}
locs = {}
for row in tqdm(df.to_dict(orient="records")):
    # print(row)
    # print(extract_urls(row))
    name = row["place_name"]
    locs[name] = {}
    place_labels = set()
    if "place_type" in row and row["place_type"].strip():
        place_labels |= {row["place_type"].strip()}
    if row["place_category"].strip():
        place_labels |= {row["place_category"].strip()}
    locs[name]["label"] = ",".join(place_labels)

    urls = extract_url_map(row["external_links"])
    if (
        "www.wikidata.org" not in urls
        and "wikidata_id" in row
        and row["wikidata_qid"].strip()
    ):
        locs[name]["www.wikidata.org"] = (
            "https://www.wikidata.org/wiki/" + row["wikidata_qid"].strip()
        )
    if (
        "www.geonames.org" not in urls
        and "geonames_id" in row
        and row["geonames_id"].strip()
    ):
        locs[name]["www.geonames.org"] = (
            "https://www.geonames.org/" + row["geonames_id"].strip().removesuffix(".0")
        )

    locs[name].update(urls[0])
print(locs)

100%|██████████| 33/33 [00:00<00:00, 49521.30it/s]

{'Gießen, Marktplatz 11': {'label': 'ort_der_zeit', 'www.geonames.org': 'https://www.geonames.org/2920512'}, 'Gießen': {'label': 'reise_zurueck', 'www.geonames.org': 'https://www.geonames.org/2920512/giessen.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q564579'}, 'Löberstraße 20': {'label': 'alte_heimat', 'www.giessen.de': 'https://www.giessen.de/index.php?ModID=7&FID=2874.2939.1&object=tx%7C2874.2939.1'}, 'Ghettohaus, Walltorstraße 48': {'label': 'alte_heimat,Ghettohaus', 'www.giessen.de': 'https://www.giessen.de/index.php?ModID=7&FID=2874.2939.1&object=tx%7C2874.2939.1'}, 'Schlesien': {'label': 'alte_heimat'}, 'Berlin': {'label': 'alte_heimat', 'www.geonames.org': 'https://www.geonames.org/2950159/berlin.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q64'}, 'Synagoge am Börneplatz, Frankfurt/M': {'label': 'alte_heimat,Synagoge', 'www.geonames.org': 'https://www.geonames.org/6553153/frankfurt-am-main.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q1794'}, 'Bahnhof, Frankfurt am Main': {'label': 'alte_heimat,Bahnhof', 'www.geonames.org': 'https://www.geonames.org/6290300/frankfurt-hauptbahnhof.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q1794'}, 'Frankfurt (Main) Hauptbahnhof': {'label': 'Zug,verkehrsmittel', 'www.geonames.org': 'https://www.geonames.org/6290300/frankfurt-hauptbahnhof.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q165368'}, 'Kehl am Rhein': {'label': 'Zug,verkehrsmittel', 'www.geonames.org': 'https://www.geonames.org/2891951/kehl.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q15979'}, 'Brücke Kehl–Straßburg (Rheinquerung)': {'label': 'Zug,verkehrsmittel', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q1375288'}, 'Marseille': {'label': 'Schiff,verkehrsmittel'}, 'Kibbuz Rodges, besteht nicht mehr (in der Nähe von Petah Tikva)': {'label': 'neue_heimat'}, 'Ēmeq Yizrəʿēl': {'label': 'neue_heimat', 'www.geonames.org': 'https://www.geonames.org/293165/jezreel-valley.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q763829'}, 'Kibbuz Ein HaNetziv': {'label': 'neue_heimat', 'www.geonames.org': 'https://www.geonames.org/295211/-en-hanaziv.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q2095906'}, 'Haifa': {'label': 'neue_heimat'}, 'Kibbuz Tirat Tsvi': {'label': 'neue_heimat', 'www.geonames.org': 'https://www.geonames.org/293304/tirat-tsvi.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q550025'}, 'Italien': {'label': 'reise_zurueck'}, 'Deutschland': {'label': 'reise_zurueck'}, 'Belgien': {'label': 'reise_zurueck'}, 'Niederlande': {'label': 'reise_zurueck'}, 'Haifa, Universität, Bibliothek': {'label': 'neue_heimat'}, 'Frankfurt am Main': {'label': 'Zug,reise_zurueck', 'www.geonames.org': 'https://www.geonames.org/6553153/frankfurt-am-main.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q1794'}, 'Klein-Linden': {'label': 'Zug,reise_zurueck', 'www.geonames.org': 'https://www.geonames.org/2888549/klein-linden.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q1571834'}, 'Großen-Linden': {'label': 'Zug,reise_zurueck', 'www.geonames.org': 'https://www.geonames.org/11974166/grossen-linden.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q116016915'}, 'Marktplatz 11, Giessen': {'label': 'Zug,reise_zurueck'}, 'Gießen, Walltorstraße 48': {'label': 'Telephon im Ghettohaus,alte_heimat', 'www.geonames.org': 'https://www.geonames.org/2920512'}}

## Add GO concepts as locations

Concepts under 'GO – Luoghi geografici' are geographic locations.
Add them to the locs dict so they get included in locations.xlsx.

In [25]:
from taxonomy import load_taxonomy

taxonomy = load_taxonomy()

go_concepts = [
    label for label, cat in taxonomy.concept_to_category.items()
    if cat == "GO"
]
# Also include GO sub-category labels
for key, info in taxonomy.sub_categories.items():
    if info.get("parent") == "GO":
        go_concepts.append(info["label"])

for concept_name in go_concepts:
    concept_name = concept_name.strip()
    if not concept_name:
        continue
    if concept_name not in locs:
        locs[concept_name] = {}
    if "label" not in locs[concept_name] or not locs[concept_name]["label"]:
        locs[concept_name]["label"] = "GO"

print(f"Added {len(go_concepts)} GO concepts to locations, total: {len(locs)}")

Added 98 GO concepts to locations, total: 119

## Update preexisting locations

In [26]:
import os
import re
from locations import enrich_locations_xlsx

def _normalize_loc(name):
    """Normalize for matching: lowercase, no punctuation, sorted words."""
    name = str(name).strip().lower()
    name = re.sub(r'[^\w\s]', '', name)
    return ' '.join(sorted(name.split()))

if os.path.exists("locations.xlsx"):
    rich = pd.read_excel("locations.xlsx", dtype=str)
    rich = rich.set_index(["location"])
else:
    rich = pd.DataFrame()
    rich.index.name = "location"

# Build a normalized index for flexible matching
existing_keys = {_normalize_loc(idx): idx for idx in rich.index}

for location, row in locs.items():
    key = _normalize_loc(location)

    if key in existing_keys:
        # Enrich existing row: only fill absent cells
        real_idx = existing_keys[key]
        if isinstance(row, dict):
            for col, val in row.items():
                if col not in rich.columns:
                    rich[col] = ""
                existing = rich.loc[real_idx, col]
                if isinstance(existing, pd.Series):
                    existing = existing.iloc[0]
                if pd.isna(existing) or str(existing).strip() in ("", "nan"):
                    rich.loc[real_idx, col] = str(val)
    else:
        # New location: add row with provided values
        if isinstance(row, dict):
            for col in row:
                if col not in rich.columns:
                    rich[col] = ""
            rich.loc[location] = {col: str(val) for col, val in row.items()}
        else:
            rich.loc[location] = pd.Series(dtype=str)
        existing_keys[key] = location

rich.to_excel("locations.xlsx")

# Enrich with bag-of-words and super-region columns
enrich_locations_xlsx("locations.xlsx")

In [30]:
taxonomy = load_taxonomy("../data/maxqda/MAXQDA_Code_System.mmd")
events = sorted(set(taxonomy.concept_to_category.keys()), key=lambda x: -len(x))
len(events), events[:15] + ["..."] + events[-15:]
# ",".join(events)

(326,
 ['Versteck bei Familie / Privatperson',
  'IPD (Jüd. Pfadfinder Deutschland)',
  'Kloster / kirchliche Einrichtung',
  'Hilfsverein der deutschen Juden',
  'Palästinaamt (Meinekestraße 10)',
  'Friedrichswerdersche Gymnasium',
  'Deutsche Diakonissenhospital',
  'Staatsgründung Israel (1948)',
  'Soldat der Jüdischen Brigade',
  'Gymnasium zum Grauen Kloster',
  'Novemberrevolution (1918–19)',
  'Reflexion in Erzählgegenwart',
  'Soldat der britischen Armee',
  'Blindenwerkstatt Otto Weidt',
  'Synagoge Gießen (orthodox)',
  '...',
  '1934',
  'Prag',
  'Kehl',
  '1921',
  '1986',
  '1939',
  '1919',
  'Emek',
  '1915',
  '1928',
  'SPD',
  'Zug',
  'KPD',
  'Tod',
  'USA'])

# Timespan

In [27]:
df[["time_start", "time_end"]] = (
    df["date_label"].apply(lambda ts: list(parse_timespan(ts).as_tuple())).tolist()
)
df

,event_label,event_type,place_name,place_type,place_category,wikidata_qid,geonames_id,google maps,date_certainty,date_label,...,source_timecode,source_quote,external_links,notes,protagonist,name,start_location,end_location,time_start,time_end
0,Alte Heimat Geburt,birth,"Gießen, Marktplatz 11",,alte_heimat,Q564579,2920512.0,,certain,15/06/1921,...,,,https://www.geonames.org/2920512/giessen.html\...,2920512.0 certain 15/06/1921 https://www.geona...,stern_IS_S_00142,Josef Stern,"Gießen, Marktplatz 11","Gießen, Marktplatz 11",1921-06-15,1921-06-15
1,Alte Heimat Grundschule,education,Gießen,,alte_heimat,,,,probable,1928-1932,...,,,,probable 1928-1932,stern_IS_S_00142,Josef Stern,"Gießen, Marktplatz 11",Gießen,1928-01-01,1932-12-31
2,Alte Heimat Realgymnasium,education,Gießen,,alte_heimat,,,,uncertain,1932- Winter 1935,...,,,,uncertain 1932- Winter 1935,stern_IS_S_00142,Josef Stern,Gießen,Gießen,1932-01-01,1932-12-31
3,Wohnort,residence,Löberstraße 20,,alte_heimat,,,,uncertain,1933?,...,,,https://www.giessen.de/index.php?ModID=7&FID=2...,Aufräumung v4: place_name korrigiert von 'Löbe...,stern_IS_S_00142,Josef Stern,Gießen,Löberstraße 20,1933-01-01,1933-12-31
4,Abgang von der Schule,education,Gießen,,alte_heimat,,,,probable,1935,...,29min 04,,,probable 1935 29min 04,stern_IS_S_00142,Josef Stern,Löberstraße 20,Gießen,1935-01-01,1935-12-31
5,Wohnort,residence,"Ghettohaus, Walltorstraße 48",Ghettohaus,alte_heimat,,,,probable,ab 1935,...,,,https://www.giessen.de/index.php?ModID=7&FID=2...,probable ab 1935 https://www.giessen.de/index....,stern_IS_S_00142,Josef Stern,Gießen,"Ghettohaus, Walltorstraße 48",1935-01-01,1935-12-31
6,Hachschara,education,Schlesien,,alte_heimat,,,,probable,1935,...,30min 57s,,,probable 1935 30min 57s,stern_IS_S_00142,Josef Stern,"Ghettohaus, Walltorstraße 48",Schlesien,1935-01-01,1935-12-31
7,Bei Verwandten,residence,Berlin,,alte_heimat,Q64,2950159.0,,probable,1935,...,31min 31s,,https://www.wikidata.org/wiki/Q64\nhttps://www...,2950159.0 probable 1935 31min 31s https://www....,stern_IS_S_00142,Josef Stern,Schlesien,Berlin,1935-01-01,1935-12-31
8,Jeschiwa,education,"Synagoge am Börneplatz, Frankfurt/M",Synagoge,alte_heimat,Q111620976,6553153.0,,probable,1936,...,,,https://www.wikidata.org/wiki/Q111620976\nhttp...,31min 58s — [Hinweis: Zerstört im Novemberpogr...,stern_IS_S_00142,Josef Stern,Berlin,"Synagoge am Börneplatz, Frankfurt/M",1936-01-01,1936-12-31
9,Abfahrt > Abschied von den Eltern,farewell,"Bahnhof, Frankfurt am Main",Bahnhof,alte_heimat,Q1794,6553153.0,,probable,1936,...,,,https://www.wikidata.org/wiki/Q1794\nhttps://w...,6553153.0 probable 1936 https://www.wikidata.o...,stern_IS_S_00142,Josef Stern,"Synagoge am Börneplatz, Frankfurt/M","Bahnhof, Frankfurt am Main",1936-01-01,1936-12-31
10,Auswanderung,emigration_transit,Frankfurt (Main) Hauptbahnhof,Zug,verkehrsmittel,Q165368,6290300.0,,probable,1936,...,32min 16s,,https://www.wikidata.org/wiki/Q165368\nhttps:/...,6290300.0 probable 1936 32min 16s https://www....,stern_IS_S_00142,Josef Stern,"Bahnhof, Frankfurt am Main",Frankfurt (Main) Hauptbahnhof,1936-01-01,1936-12-31
11,Auswanderung,emigration_transit,Kehl am Rhein,Zug,verkehrsmittel,Q15979,2891951.0,,probable,1936,...,,,https://www.wikidata.org/wiki/Q15979\nhttps://...,2891951.0 probable 1936 https://www.wikidata.o...,stern_IS_S_00142,Josef Stern,Frankfurt (Main) Hauptbahnhof,Kehl am Rhein,1936-01-01,1936-12-31
12,Auswanderung,emigration_transit,Brücke Kehl–Straßburg (Rheinquerung),Zug,verkehrsmittel,Q1375288,,,probable,1936,...,,,https://www.wikidata.org/wiki/Q1375288,Heutige Europabrücke ab 1960; 1936 nutzte Ster...,stern_IS_S_00142,Josef Stern,Kehl am Rhein,Brücke Kehl–Straßburg (Rheinquerung),1936-01-01,1936-12-31
13,Auswanderung,emigration_transit,Marseille,Zug,verkehrsmittel,Q23482,2995469.0,,probable,1936,...,,,https://www.wikidata.org/wiki/Q23482\nhttps://...,2995469.0 probable 1936 https://www.wikidata.o...,stern_IS_S_00142,Josef Stern,Brücke Kehl–Straßburg (Rheinquerung),Marseille,1936-01-01,1936-12-31
14,Auswanderung,emigration,Marseille,Schiff,verkehrsmittel,,,,probable,1936,...,,,,probable 1936,stern_IS_S_00142,Josef Stern,Marseille,Marseille,1936-01-01,1936-12-31
15,Neue Heimat\nEinwanderung,immigration,"Kibbuz Rodges, besteht nicht mehr (in der Nähe...",,neue_heimat,,,,probable,1936-38,...,,,,probable 1936-38,stern_IS_S_00142,Josef Stern,Marseille,"Kibbuz Rodges, besteht nicht mehr (in der Nähe...",1936-01-01,1938-12-31
16,Neue Heimat\n\nReise durchs Land,residence,Ēmeq Yizrəʿēl,,neue_heimat,Q763829,293165.0,,probable,1937,...,,,https://www.wikidata.org/wiki/Q763829\nhttps:/...,Jesreelebene 293165.0 probable 1937 https://ww...,stern_IS_S_00142,Josef Stern,"Kibbuz Rodges, besteht nicht mehr (in der Nähe...",Ēmeq Yizrəʿēl,1937-01-01,1937-12-31
17,Neue Heimat,residence,Kibbuz Ein HaNetziv,,neue_heimat,Q2095906,295211.0,,uncertain,1938-194?,...,,,https://www.wikidata.org/wiki/Q2095906\nhttps:...,aus dem Kibbuz ausgewiesen 295211.0 uncertain ...,stern_IS_S_00142,Josef Stern,Ēmeq Yizrəʿēl,Kibbuz Ein HaNetziv,1938-01-01,1949-12-31
18,Neue Heimat,residence,Haifa,,neue_heimat,Q41621,294801.0,,uncertain,194?–,...,,,https://www.geonames.org/294801/haifa.html\nht...,Fabrik in der Nähe von Haifa 294801.0 uncertai...,stern_IS_S_00142,Josef Stern,Kibbuz Ein HaNetziv,Haifa,1940-01-01,1949-12-31
19,Neue Heimat,residence,Kibbuz Tirat Tsvi,,neue_heimat,Q550025,293304.0,,uncertain,1940-1944,...,,,https://www.wikidata.org/wiki/Q550025\nhttps:/...,293304.0 uncertain 1940-1944 https://www.wikid...,stern_IS_S_00142,Josef Stern,Haifa,Kibbuz Tirat Tsvi,1940-01-01,1944-12-31
20,Reise zurück als Soldat,military_service,Italien,,reise_zurueck,,,,probable,1944,...,,,,probable 1944,stern_IS_S_00142,Josef Stern,Kibbuz Tirat Tsvi,Italien,1944-01-01,1944-12-31
21,Reise zurück als Soldat,military_service,Deutschland,,reise_zurueck,,,,probable,1944,...,,,,probable 1944,stern_IS_S_00142,Josef Stern,Italien,Deutschland,1944-01-01,1944-12-31
22,Reise zurück als Soldat,military_service,Belgien,,reise_zurueck,,,,probable,1944,...,,,,probable 1944,stern_IS_S_00142,Josef Stern,Deutschland,Belgien,1944-01-01,1944-12-31
23,Reise zurück als Soldat,military_service,Niederlande,,reise_zurueck,,,,probable,1944,...,,,,probable 1944,stern_IS_S_00142,Josef Stern,Belgien,Niederlande,1944-01-01,1944-12-31
24,Neue Heimat\nHeirat,marriage,Haifa,,neue_heimat,,,,uncertain,,...,,,,uncertain,stern_IS_S_00142,Josef Stern,Niederlande,Haifa,None,None
25,Neue Heimat\nHaifa\nBeruf,work,"Haifa, Universität, Bibliothek",,neue_heimat,,,,probable,1966–1986,...,,,,probable 1966–1986,stern_IS_S_00142,Josef Stern,Haifa,"Haifa, Universität, Bibliothek",1966-01-01,1986-12-31
26,Reise zurück,return_visit_transit,Gießen,,reise_zurueck,Q564579,2920512.0,,probable,1975,...,,,https://www.geonames.org/2920512/giessen.html\...,2920512.0 probable 1975 https://www.geonames.o...,stern_IS_S_00142,Josef Stern,"Haifa, Universität, Bibliothek",Gießen,1975-01-01,1975-12-31
27,Fahrt Frankfurt-Gießen,return_visit_transit,Frankfurt am Main,Zug,reise_zurueck,Q1794,6553153.0,,,,...,,,https://www.wikidata.org/wiki/Q1794\nhttps://w...,6553153.0 https://www.wikidata.org/wiki/Q1794\...,stern_IS_S_00142,Josef Stern,Gießen,Frankfurt am Main,None,None
28,Klein Linden,return_visit_transit,Klein-Linden,Zug,reise_zurueck,Q1571834,2888549.0,,,,...,,,https://www.wikidata.org/wiki/Q1571834\nhttps:...,2888549.0 https://www.wikidata.org/wiki/Q15718...,stern_IS_S_00142,Josef Stern,Frankfurt am Main,Klein-Linden,None,None
29,Großen-Linden,return_visit,Großen-Linden,Zug,reise_zurueck,Q116016915,11974166.0,,,,...,,,https://www.wikidata.org/wiki/Q116016915\nhttp...,11974166.0 https://www.wikidata.org/wiki/Q1160...,stern_IS_S_00142,Josef Stern,Klein-Linden,Großen-Linden,None,None
30,Geburtshaus Marktplatz 11,return_visit_transit,"Marktplatz 11, Giessen",Zug,reise_zurueck,,,,,,...,,,,Geburtshaus Geburtshaus,stern_IS_S_00142,Josef Stern,Großen-Linden,"Marktplatz 11, Giessen",None,None
31,Aliyah-Anruf,notification,"Gießen, Walltorstraße 48",Telephon im Ghettohaus,alte_heimat,Q564579,2920512.0,,probable,1936,...,30min 15s,"Ich bekam einen Anruf am Telefon in dem Haus, ...",,Chronotopos im engeren Sinn: Ort (Walltorstraß...,stern_IS_S_00142,Josef Stern,"Marktplatz 11, Giessen","Gießen, Walltorstraße 48",1936-01-01,1936-12-31
32,Zwangsausweisung Marktplatz 11,forced_eviction,"Gießen, Marktplatz 11",,ort_der_zeit,Q564579,2920512.0,,probable,1933,...,11min 47s,Wir sind allerdings aus diesem schönen Haus gl...,,Josef war 12 Jahre alt. Erstes durch ihn erinn...,stern_IS_S_00142,Josef Stern,"Gießen, Walltorstraße 48","Gießen, Marktplatz 11",1933-01-01,1933-12-31

# Notes

left unprocessed for now

In [28]:
set(df["notes"])

{'11974166.0 https://www.wikidata.org/wiki/Q116016915\nhttps://www.geonames.org/11974166/grossen-linden.html',
 '2888549.0 https://www.wikidata.org/wiki/Q1571834\nhttps://www.geonames.org/2888549/klein-linden.html',
 '2891951.0 probable 1936 https://www.wikidata.org/wiki/Q15979\nhttps://www.geonames.org/2891951/kehl.html',
 '2920512.0 certain 15/06/1921 https://www.geonames.org/2920512/giessen.html\nhttps://www.wikidata.org/wiki/Q564579\nhttps://www.giessen.de/index.php?ModID=7&FID=2874.2939.1&object=tx%7C2874.2939.1',
 '2920512.0 probable 1975 https://www.geonames.org/2920512/giessen.html\nhttps://www.wikidata.org/wiki/Q564579',
 '293304.0 uncertain 1940-1944 https://www.wikidata.org/wiki/Q550025\nhttps://www.geonames.org/293304/tirat-tsvi.html',
 '2950159.0 probable 1935 31min 31s https://www.wikidata.org/wiki/Q64\nhttps://www.geonames.org/2950159/berlin.html',
 '2995469.0 probable 1936 https://www.wikidata.org/wiki/Q23482\nhttps://www.geonames.org/2995469/marseille.html',
 '31min 58s — [Hinweis: Zerstört im Novemberpogrom 1938; heute Gedenkstätte Neuer Börneplatz.] 6553153.0 probable 1936 https://www.wikidata.org/wiki/Q111620976\nhttps://www.wikidata.org/wiki/Q1794\nhttps://www.geonames.org/6553153/frankfurt-am-main.html 31min 58s — [Hinweis: Zerstört im Novemberpogrom 1938; heute Gedenkstätte Neuer Börneplatz.]',
 '6290300.0 probable 1936 32min 16s https://www.wikidata.org/wiki/Q165368\nhttps://www.geonames.org/6290300/frankfurt-hauptbahnhof.html',
 '6553153.0 https://www.wikidata.org/wiki/Q1794\nhttps://www.geonames.org/6553153/frankfurt-am-main.html',
 '6553153.0 probable 1936 https://www.wikidata.org/wiki/Q1794\nhttps://www.geonames.org/6553153/frankfurt-am-main.html\nhttps://www.geonames.org/6290300/frankfurt-hauptbahnhof.html',
 "Aufräumung v4: place_name korrigiert von 'Löberstraße 20 11' zu 'Löberstraße 20'. uncertain 1933? https://www.giessen.de/index.php?ModID=7&FID=2874.2939.1&object=tx%7C2874.2939.1 Aufräumung v4: place_name korrigiert von 'Löberstraße 20 11' zu 'Löberstraße 20'.",
 'Chronotopos im engeren Sinn: Ort (Walltorstraße 48), Zeit (zwei-Tage-Ultimatum), Medium (Telephon) und ausgehender Knotenpunkt (Frankfurt Hauptbahnhof) in einem Moment verdichtet. Markiert den Beginn der Aliyah-Bewegung Josefs. 2920512.0 probable 1936 Interview Metz 2010 30min 15s Ich bekam einen Anruf am Telefon in dem Haus, in dem wir später gewohnt haben, was später zum Ghetto-Haus wurde. Ich soll innerhalb zwei Tagen bereit sein, zur Alijah nach Frankfurt zu fahren und den Zug zu nehmen Chronotopos im engeren Sinn: Ort (Walltorstraße 48), Zeit (zwei-Tage-Ultimatum), Medium (Telephon) und ausgehender Knotenpunkt (Frankfurt Hauptbahnhof) in einem Moment verdichtet. Markiert den Beginn der Aliyah-Bewegung Josefs.',
 'Fabrik in der Nähe von Haifa 294801.0 uncertain 194?– https://www.geonames.org/294801/haifa.html\nhttps://www.wikidata.org/wiki/Q41621 Fabrik in der Nähe von Haifa',
 'Geburtshaus  Geburtshaus ',
 'Heutige Europabrücke ab 1960; 1936 nutzte Stern die alte Straßenbrücke von 1897 (1939 zerstört). probable 1936 https://www.wikidata.org/wiki/Q1375288 Heutige Europabrücke ab 1960; 1936 nutzte Stern die alte Straßenbrücke von 1897 (1939 zerstört).',
 'Jesreelebene 293165.0 probable 1937 https://www.wikidata.org/wiki/Q763829\nhttps://www.geonames.org/293165/jezreel-valley.html Jesreelebene',
 'Josef war 12 Jahre alt. Erstes durch ihn erinnertes NS-Verfügungsereignis; familienkollektiv. 2920512.0 probable 1933 Interview Metz 2010 11min 47s Wir sind allerdings aus diesem schönen Haus gleich 1933 ausgewiesen worden, weil es unter Denkmalschutz stand. Und in einem solchen Haus durften Juden nicht leben. Das war eine der allerersten Verfügungen der Nazis in Gießen. Josef war 12 Jahre alt. Erstes durch ihn erinnertes NS-Verfügungsereignis; familienkollektiv.',
 'aus dem Kibbuz ausgewiesen 295211.0 uncertain 1938-194? https://www.wikidata.org/wiki/Q2095906\nhttps://www.geonames.org/295211/-en-hanaziv.html aus dem Kibbuz ausgewiesen',
 'probable 1928-1932',
 'probable 1935 29min 04',
 'probable 1935 30min 57s',
 'probable 1936',
 'probable 1936-38',
 'probable 1944',
 'probable 1966–1986',
 'probable ab 1935 https://www.giessen.de/index.php?ModID=7&FID=2874.2939.1&object=tx%7C2874.2939.1',
 'uncertain',
 'uncertain 1932- Winter 1935'}

# Links

left unprocessed for now

In [29]:
urls = set()
for cell in df["external_links"]:
    if pd.notna(cell):
        for url in str(cell).split("\n"):
            url = url.strip()
            if url:
                urls.add(url)
urls

{'https://www.geonames.org/11974166/grossen-linden.html',
 'https://www.geonames.org/2888549/klein-linden.html',
 'https://www.geonames.org/2891951/kehl.html',
 'https://www.geonames.org/2920512/giessen.html',
 'https://www.geonames.org/293165/jezreel-valley.html',
 'https://www.geonames.org/293304/tirat-tsvi.html',
 'https://www.geonames.org/294801/haifa.html',
 'https://www.geonames.org/2950159/berlin.html',
 'https://www.geonames.org/295211/-en-hanaziv.html',
 'https://www.geonames.org/2995469/marseille.html',
 'https://www.geonames.org/6290300/frankfurt-hauptbahnhof.html',
 'https://www.geonames.org/6553153/frankfurt-am-main.html',
 'https://www.giessen.de/index.php?ModID=7&FID=2874.2939.1&object=tx%7C2874.2939.1',
 'https://www.wikidata.org/wiki/Q111620976',
 'https://www.wikidata.org/wiki/Q116016915',
 'https://www.wikidata.org/wiki/Q1375288',
 'https://www.wikidata.org/wiki/Q1571834',
 'https://www.wikidata.org/wiki/Q15979',
 'https://www.wikidata.org/wiki/Q165368',
 'https://www.wikidata.org/wiki/Q1794',
 'https://www.wikidata.org/wiki/Q2095906',
 'https://www.wikidata.org/wiki/Q23482',
 'https://www.wikidata.org/wiki/Q41621',
 'https://www.wikidata.org/wiki/Q550025',
 'https://www.wikidata.org/wiki/Q564579',
 'https://www.wikidata.org/wiki/Q64',
 'https://www.wikidata.org/wiki/Q763829'}

# Events

In [31]:
df["event"] = df["event_label"].apply(lambda x: extract_events(x, events))
df

,event_label,event_type,place_name,place_type,place_category,wikidata_qid,geonames_id,google maps,date_certainty,date_label,...,source_quote,external_links,notes,protagonist,name,start_location,end_location,time_start,time_end,event
0,Alte Heimat Geburt,birth,"Gießen, Marktplatz 11",,alte_heimat,Q564579,2920512.0,,certain,15/06/1921,...,,https://www.geonames.org/2920512/giessen.html\...,2920512.0 certain 15/06/1921 https://www.geona...,stern_IS_S_00142,Josef Stern,"Gießen, Marktplatz 11","Gießen, Marktplatz 11",1921-06-15,1921-06-15,"[Geburt, Alte Heimat]"
1,Alte Heimat Grundschule,education,Gießen,,alte_heimat,,,,probable,1928-1932,...,,,probable 1928-1932,stern_IS_S_00142,Josef Stern,"Gießen, Marktplatz 11",Gießen,1928-01-01,1932-12-31,[Alte Heimat Grundschule]
2,Alte Heimat Realgymnasium,education,Gießen,,alte_heimat,,,,uncertain,1932- Winter 1935,...,,,uncertain 1932- Winter 1935,stern_IS_S_00142,Josef Stern,Gießen,Gießen,1932-01-01,1932-12-31,"[Realgymnasium, Alte Heimat]"
3,Wohnort,residence,Löberstraße 20,,alte_heimat,,,,uncertain,1933?,...,,https://www.giessen.de/index.php?ModID=7&FID=2...,Aufräumung v4: place_name korrigiert von 'Löbe...,stern_IS_S_00142,Josef Stern,Gießen,Löberstraße 20,1933-01-01,1933-12-31,[Wohnort]
4,Abgang von der Schule,education,Gießen,,alte_heimat,,,,probable,1935,...,,,probable 1935 29min 04,stern_IS_S_00142,Josef Stern,Löberstraße 20,Gießen,1935-01-01,1935-12-31,[Abgang von der Schule]
5,Wohnort,residence,"Ghettohaus, Walltorstraße 48",Ghettohaus,alte_heimat,,,,probable,ab 1935,...,,https://www.giessen.de/index.php?ModID=7&FID=2...,probable ab 1935 https://www.giessen.de/index....,stern_IS_S_00142,Josef Stern,Gießen,"Ghettohaus, Walltorstraße 48",1935-01-01,1935-12-31,[Wohnort]
6,Hachschara,education,Schlesien,,alte_heimat,,,,probable,1935,...,,,probable 1935 30min 57s,stern_IS_S_00142,Josef Stern,"Ghettohaus, Walltorstraße 48",Schlesien,1935-01-01,1935-12-31,[Hachschara]
7,Bei Verwandten,residence,Berlin,,alte_heimat,Q64,2950159.0,,probable,1935,...,,https://www.wikidata.org/wiki/Q64\nhttps://www...,2950159.0 probable 1935 31min 31s https://www....,stern_IS_S_00142,Josef Stern,Schlesien,Berlin,1935-01-01,1935-12-31,"[Verwandte, Bei n]"
8,Jeschiwa,education,"Synagoge am Börneplatz, Frankfurt/M",Synagoge,alte_heimat,Q111620976,6553153.0,,probable,1936,...,,https://www.wikidata.org/wiki/Q111620976\nhttp...,31min 58s — [Hinweis: Zerstört im Novemberpogr...,stern_IS_S_00142,Josef Stern,Berlin,"Synagoge am Börneplatz, Frankfurt/M",1936-01-01,1936-12-31,[Jeschiwa]
9,Abfahrt > Abschied von den Eltern,farewell,"Bahnhof, Frankfurt am Main",Bahnhof,alte_heimat,Q1794,6553153.0,,probable,1936,...,,https://www.wikidata.org/wiki/Q1794\nhttps://w...,6553153.0 probable 1936 https://www.wikidata.o...,stern_IS_S_00142,Josef Stern,"Synagoge am Börneplatz, Frankfurt/M","Bahnhof, Frankfurt am Main",1936-01-01,1936-12-31,"[Abschied von den Eltern, Abfahrt >]"
10,Auswanderung,emigration_transit,Frankfurt (Main) Hauptbahnhof,Zug,verkehrsmittel,Q165368,6290300.0,,probable,1936,...,,https://www.wikidata.org/wiki/Q165368\nhttps:/...,6290300.0 probable 1936 32min 16s https://www....,stern_IS_S_00142,Josef Stern,"Bahnhof, Frankfurt am Main",Frankfurt (Main) Hauptbahnhof,1936-01-01,1936-12-31,[Auswanderung]
11,Auswanderung,emigration_transit,Kehl am Rhein,Zug,verkehrsmittel,Q15979,2891951.0,,probable,1936,...,,https://www.wikidata.org/wiki/Q15979\nhttps://...,2891951.0 probable 1936 https://www.wikidata.o...,stern_IS_S_00142,Josef Stern,Frankfurt (Main) Hauptbahnhof,Kehl am Rhein,1936-01-01,1936-12-31,[Auswanderung]
12,Auswanderung,emigration_transit,Brücke Kehl–Straßburg (Rheinquerung),Zug,verkehrsmittel,Q1375288,,,probable,1936,...,,https://www.wikidata.org/wiki/Q1375288,Heutige Europabrücke ab 1960; 1936 nutzte Ster...,stern_IS_S_00142,Josef Stern,Kehl am Rhein,Brücke Kehl–Straßburg (Rheinquerung),1936-01-01,1936-12-31,[Auswanderung]
13,Auswanderung,emigration_transit,Marseille,Zug,verkehrsmittel,Q23482,2995469.0,,probable,1936,...,,https://www.wikidata.org/wiki/Q23482\nhttps://...,2995469.0 probable 1936 https://www.wikidata.o...,stern_IS_S_00142,Josef Stern,Brücke Kehl–Straßburg (Rheinquerung),Marseille,1936-01-01,1936-12-31,[Auswanderung]
14,Auswanderung,emigration,Marseille,Schiff,verkehrsmittel,,,,probable,1936,...,,,probable 1936,stern_IS_S_00142,Josef Stern,Marseille,Marseille,1936-01-01,1936-12-31,[Auswanderung]
15,Neue Heimat\nEinwanderung,immigration,"Kibbuz Rodges, besteht nicht mehr (in der Nähe...",,neue_heimat,,,,probable,1936-38,...,,,probable 1936-38,stern_IS_S_00142,Josef Stern,Marseille,"Kibbuz Rodges, besteht nicht mehr (in der Nähe...",1936-01-01,1938-12-31,[Neue Heimat\nEinwanderung]
16,Neue Heimat\n\nReise durchs Land,residence,Ēmeq Yizrəʿēl,,neue_heimat,Q763829,293165.0,,probable,1937,...,,https://www.wikidata.org/wiki/Q763829\nhttps:/...,Jesreelebene 293165.0 probable 1937 https://ww...,stern_IS_S_00142,Josef Stern,"Kibbuz Rodges, besteht nicht mehr (in der Nähe...",Ēmeq Yizrəʿēl,1937-01-01,1937-12-31,"[Reise durchs Land, Neue Heimat]"
17,Neue Heimat,residence,Kibbuz Ein HaNetziv,,neue_heimat,Q2095906,295211.0,,uncertain,1938-194?,...,,https://www.wikidata.org/wiki/Q2095906\nhttps:...,aus dem Kibbuz ausgewiesen 295211.0 uncertain ...,stern_IS_S_00142,Josef Stern,Ēmeq Yizrəʿēl,Kibbuz Ein HaNetziv,1938-01-01,1949-12-31,[Neue Heimat]
18,Neue Heimat,residence,Haifa,,neue_heimat,Q41621,294801.0,,uncertain,194?–,...,,https://www.geonames.org/294801/haifa.html\nht...,Fabrik in der Nähe von Haifa 294801.0 uncertai...,stern_IS_S_00142,Josef Stern,Kibbuz Ein HaNetziv,Haifa,1940-01-01,1949-12-31,[Neue Heimat]
19,Neue Heimat,residence,Kibbuz Tirat Tsvi,,neue_heimat,Q550025,293304.0,,uncertain,1940-1944,...,,https://www.wikidata.org/wiki/Q550025\nhttps:/...,293304.0 uncertain 1940-1944 https://www.wikid...,stern_IS_S_00142,Josef Stern,Haifa,Kibbuz Tirat Tsvi,1940-01-01,1944-12-31,[Neue Heimat]
20,Reise zurück als Soldat,military_service,Italien,,reise_zurueck,,,,probable,1944,...,,,probable 1944,stern_IS_S_00142,Josef Stern,Kibbuz Tirat Tsvi,Italien,1944-01-01,1944-12-31,[Reise zurück als Soldat]
21,Reise zurück als Soldat,military_service,Deutschland,,reise_zurueck,,,,probable,1944,...,,,probable 1944,stern_IS_S_00142,Josef Stern,Italien,Deutschland,1944-01-01,1944-12-31,[Reise zurück als Soldat]
22,Reise zurück als Soldat,military_service,Belgien,,reise_zurueck,,,,probable,1944,...,,,probable 1944,stern_IS_S_00142,Josef Stern,Deutschland,Belgien,1944-01-01,1944-12-31,[Reise zurück als Soldat]
23,Reise zurück als Soldat,military_service,Niederlande,,reise_zurueck,,,,probable,1944,...,,,probable 1944,stern_IS_S_00142,Josef Stern,Belgien,Niederlande,1944-01-01,1944-12-31,[Reise zurück als Soldat]
24,Neue Heimat\nHeirat,marriage,Haifa,,neue_heimat,,,,uncertain,,...,,,uncertain,stern_IS_S_00142,Josef Stern,Niederlande,Haifa,None,None,"[Heirat, Neue Heimat]"
25,Neue Heimat\nHaifa\nBeruf,work,"Haifa, Universität, Bibliothek",,neue_heimat,,,,probable,1966–1986,...,,,probable 1966–1986,stern_IS_S_00142,Josef Stern,Haifa,"Haifa, Universität, Bibliothek",1966-01-01,1986-12-31,"[Beruf, Haifa, Neue Heimat]"
26,Reise zurück,return_visit_transit,Gießen,,reise_zurueck,Q564579,2920512.0,,probable,1975,...,,https://www.geonames.org/2920512/giessen.html\...,2920512.0 probable 1975 https://www.geonames.o...,stern_IS_S_00142,Josef Stern,"Haifa, Universität, Bibliothek",Gießen,1975-01-01,1975-12-31,[Reise zurück]
27,Fahrt Frankfurt-Gießen,return_visit_transit,Frankfurt am Main,Zug,reise_zurueck,Q1794,6553153.0,,,,...,,https://www.wikidata.org/wiki/Q1794\nhttps://w...,6553153.0 https://www.wikidata.org/wiki/Q1794\...,stern_IS_S_00142,Josef Stern,Gießen,Frankfurt am Main,None,None,[Fahrt Frankfurt-Gießen]
28,Klein Linden,return_visit_transit,Klein-Linden,Zug,reise_zurueck,Q1571834,2888549.0,,,,...,,https://www.wikidata.org/wiki/Q1571834\nhttps:...,2888549.0 https://www.wikidata.org/wiki/Q15718...,stern_IS_S_00142,Josef Stern,Frankfurt am Main,Klein-Linden,None,None,[Klein Linden]
29,Großen-Linden,return_visit,Großen-Linden,Zug,reise_zurueck,Q116016915,11974166.0,,,,...,,https://www.wikidata.org/wiki/Q116016915\nhttp...,11974166.0 https://www.wikidata.org/wiki/Q1160...,stern_IS_S_00142,Josef Stern,Klein-Linden,Großen-Linden,None,None,[Großen-Linden]
30,Geburtshaus Marktplatz 11,return_visit_transit,"Marktplatz 11, Giessen",Zug,reise_zurueck,,,,,,...,,,Geburtshaus Geburtshaus,stern_IS_S_00142,Josef Stern,Großen-Linden,"Marktplatz 11, Giessen",None,None,"[Marktplatz 11, Geburtshaus]"
31,Aliyah-Anruf,notification,"Gießen, Walltorstraße 48",Telephon im Ghettohaus,alte_heimat,Q564579,2920512.0,,probable,1936,...,"Ich bekam einen Anruf am Telefon in dem Haus, ...",,Chronotopos im engeren Sinn: Ort (Walltorstraß...,stern_IS_S_00142,Josef Stern,"Marktplatz 11, Giessen","Gießen, Walltorstraße 48",1936-01-01,1936-12-31,[Aliyah-Anruf]
32,Zwangsausweisung Marktplatz 11,forced_eviction,"Gießen, Marktplatz 11",,ort_der_zeit,Q564579,2920512.0,,probable,1933,...,Wir sind allerdings aus diesem schönen Haus gl...,,Josef war 12 Jahre alt. Erstes durch ihn erinn...,stern_IS_S_00142,Josef Stern,"Gießen, Walltorstraße 48","Gießen, Marktplatz 11",1933-01-01,1933-12-31,"[Marktplatz 11, Zwangsausweisung]"

In [32]:
from api_client import (
    login, get_or_create_concept,
)
from locations import (
    load_locations_db,
)

login()
load_locations_db()

# === Main import ===

# 1. Create all concepts
print("Creating concepts...")
for label in sorted(concept_labels):
    get_or_create_concept(label)
print(f"  {len(concept_labels)} concept labels processed")

Authenticated
  Loaded 244 locations from locations.xlsx
Creating concepts...
  25 concept labels processed