In [1]:
from glob import glob
import re
import pandas as pd
from tqdm import tqdm

from locations import extract_url_map
from events import parse_mmd_taxonomy, extract_events
from timespan import parse_timespan

In [2]:
root_path = "../data/schede mappatura/"

In [3]:
chrono_schede = glob(f"{root_path}*/chronotop*")
chrono_schede = [s for s in chrono_schede if not s.endswith(":Zone.Identifier") and not s.endswith("v4.xlsx") and not s.endswith("template.xlsx")]
chrono_schede

['../data/schede mappatura/bruenn_ charlotte_IS_S_00027/chronotopi_charlotte_bruenn_IS_S_00027 (file revisionato).xlsx',
 '../data/schede mappatura/bruenn_jehoshua_IS_S_00028/chronotopoi_bruenn_jehoshua_bozza.xlsx',
 '../data/schede mappatura/david_ruth_FEGB_E_00007/chronotopi_ruth_david_FEGB_E_00007.xlsx']

## A list of individual sources for experimentation

ignored in the oveall logic

# current = "bruenn_jehoshua_IS_S_00028/chronotopoi_bruenn_jehoshua_bozza.xlsx"
# current = "david_ruth_FEGB_E_00007/chronotopi_ruth_david_FEGB_E_00007.xlsx"
# current = "bruenn_ charlotte_IS_S_00027/chronotopi_charlotte_bruenn_IS_S_00027 (file revisionato).xlsx"
# current = "stern_IS_S_00142/chronotopi_josef_stern_IS_S_00142.xlsx"
current = "stern_IS_S_00142/chronotopoi_josef_stern_familie_v4.xlsx"

chrono_schede = [s for s in chrono_schede if current in s]
chrono_schede

import openpyxl

overview = {}
for s in chrono_schede:
    wb = openpyxl.load_workbook(s)
    overview[s] = wb.sheetnames
overview

After identification of all sources

# Shortlist processable sources

In [4]:
overview = {
    "bruenn_jehoshua_IS_S_00028/chronotopoi_bruenn_jehoshua_bozza.xlsx": [
        "Foglio1",
    ],
    "david_ruth_FEGB_E_00007/chronotopi_ruth_david_FEGB_E_00007.xlsx": [
        "Ruth Louise David",
        "1 Ehe - Andrew Finch",
        "2. Ehe - Herbert Aron David",
        "Mutt-Margarethe Oppenheimer ",
        "Vat -Moritz Oppenheimer",
        "Isaak Oppenheimer",
        "Ernst Oppenheimer",
        "Werner Oppenheimer",
        "Hanna Oppenheimer",
        "Michael Oppenheimer",
        "Feodora (Feo) Oppenheimer",
        "Liese Oppenheimer gb. Krämer",
        "Alice Urbach",
        "Robert Sommer",
        "Renate Knigge-Tesche ",
    ],
    "bruenn_ charlotte_IS_S_00027/chronotopi_charlotte_bruenn_IS_S_00027 (file revisionato).xlsx": [
        "Charlotte Bruenn geb. Hirsch",
        "Ludwig Hirsch",
        "Gutta Hirsch geb. Dingfelder",
        "Alice Hirsch (Estryn)",
        "Erich Hirsch",
        "Walter Hirsch",
        "Alfons Justin Hirsch",
        "Margot Hirsch",
    ],
}

## Put all data together

In [5]:
import openpyxl as _openpyxl

df_list = []
for k, v in overview.items():
    for s in v:
        name = k.split("/")[0]

        # Auto-detect header row: if first cell is not "Event", skip one row
        _wb = _openpyxl.load_workbook(root_path + k, read_only=True)
        _ws = _wb[s]
        _first_cell = next(_ws.iter_rows(min_row=1, max_row=1, max_col=1))[0].value
        _wb.close()
        skiprows = 0 if str(_first_cell).strip() == "Event" else 1

        df = pd.read_excel(root_path + k, sheet_name=s, skiprows=skiprows)
        print(k, s, f"(skip={skiprows})", df.shape)

        # Keep only first 5 columns (old format: Event, Location, Timespan, Notes, Links)
        df = df.iloc[:, :5]
        df.columns = ["event_label", "raw_location", "date_label", "notes", "external_links"]

        # Parse location column: extract place name and wikidata/geonames IDs
        place_names, wikidata_qids, geonames_ids = [], [], []
        for loc_text in df["raw_location"]:
            if pd.isna(loc_text) or str(loc_text).strip() in ("", "nan"):
                place_names.append("")
                wikidata_qids.append("")
                geonames_ids.append("")
                continue
            loc_str = str(loc_text)
            # Extract wikidata QID
            wq = re.search(r"wikidata\.org/wiki/(Q\d+)", loc_str)
            wikidata_qids.append(wq.group(1) if wq else "")
            # Extract geonames ID
            gn = re.search(r"geonames\.org/(\d+)", loc_str)
            geonames_ids.append(gn.group(1) if gn else "")
            # Place name: first line, with all URLs stripped
            first_line = loc_str.split("\n")[0].strip()
            first_line = re.sub(r"https?://\S+", "", first_line)
            first_line = re.sub(r"(?:www\.)?(?:wikidata|geonames)\.\S+", "", first_line)
            place_name = first_line.rstrip(";").strip()
            place_names.append(place_name)

        df["place_name"] = place_names
        df["wikidata_qid"] = wikidata_qids
        df["geonames_id"] = geonames_ids
        df = df.drop(columns=["raw_location"])

        # Filter geonames/wikidata URLs from external_links
        def _clean_links(text):
            if pd.isna(text) or str(text).strip() in ("", "nan"):
                return ""
            lines = str(text).split("\n")
            return "\n".join(
                l for l in lines
                if l.strip() and "geonames.org" not in l and "wikidata.org" not in l
            )
        df["external_links"] = df["external_links"].apply(_clean_links)

        # Add empty v4-specific columns
        for col in [
            "event_type", "place_type", "place_category",
            "date_certainty", "memorial_inscription",
            "source_doc", "source_timecode", "source_quote",
        ]:
            df[col] = ""

        df["protagonist"] = name
        df["name"] = s
        df_list.append(df)

df = pd.concat(df_list, axis=0).astype(str)
df.fillna("", inplace=True)

# Track start/end locations (each event starts where the previous one ended)
start_locations = []
prev_location = {}
for _, row in df.iterrows():
    person = row["protagonist"]
    end_loc = row["place_name"].strip()
    start_loc = prev_location.get(person, end_loc)
    start_locations.append(start_loc)
    if end_loc:
        prev_location[person] = end_loc
df["start_location"] = start_locations
df["end_location"] = df["place_name"]

# Collect concepts (empty for old format, kept for API import compatibility)
concept_labels = set()
for col in ["event_type", "place_type", "place_category"]:
    for val in df[col]:
        v = val.strip()
        if v and v != "nan":
            concept_labels.add(v)
print(f"Concepts to create: {sorted(concept_labels)}")

df

bruenn_jehoshua_IS_S_00028/chronotopoi_bruenn_jehoshua_bozza.xlsx Foglio1 (skip=1) (25, 5)
david_ruth_FEGB_E_00007/chronotopi_ruth_david_FEGB_E_00007.xlsx Ruth Louise David (skip=0) (63, 6)
david_ruth_FEGB_E_00007/chronotopi_ruth_david_FEGB_E_00007.xlsx 1 Ehe - Andrew Finch (skip=0) (11, 5)
david_ruth_FEGB_E_00007/chronotopi_ruth_david_FEGB_E_00007.xlsx 2. Ehe - Herbert Aron David (skip=0) (16, 5)
david_ruth_FEGB_E_00007/chronotopi_ruth_david_FEGB_E_00007.xlsx Mutt-Margarethe Oppenheimer  (skip=0) (35, 6)
david_ruth_FEGB_E_00007/chronotopi_ruth_david_FEGB_E_00007.xlsx Vat -Moritz Oppenheimer (skip=0) (30, 7)
david_ruth_FEGB_E_00007/chronotopi_ruth_david_FEGB_E_00007.xlsx Isaak Oppenheimer (skip=0) (13, 5)
david_ruth_FEGB_E_00007/chronotopi_ruth_david_FEGB_E_00007.xlsx Ernst Oppenheimer (skip=1) (10, 5)
david_ruth_FEGB_E_00007/chronotopi_ruth_david_FEGB_E_00007.xlsx Werner Oppenheimer (skip=1) (8, 5)
david_ruth_FEGB_E_00007/chronotopi_ruth_david_FEGB_E_00007.xlsx Hanna Oppenheimer (skip=0) (12, 5)
david_ruth_FEGB_E_00007/chronotopi_ruth_david_FEGB_E_00007.xlsx Michael Oppenheimer (skip=0) (13, 5)
david_ruth_FEGB_E_00007/chronotopi_ruth_david_FEGB_E_00007.xlsx Feodora (Feo) Oppenheimer (skip=0) (15, 5)
david_ruth_FEGB_E_00007/chronotopi_ruth_david_FEGB_E_00007.xlsx Liese Oppenheimer gb. Krämer (skip=0) (13, 5)
david_ruth_FEGB_E_00007/chronotopi_ruth_david_FEGB_E_00007.xlsx Alice Urbach (skip=0) (9, 5)
david_ruth_FEGB_E_00007/chronotopi_ruth_david_FEGB_E_00007.xlsx Robert Sommer (skip=0) (5, 5)
david_ruth_FEGB_E_00007/chronotopi_ruth_david_FEGB_E_00007.xlsx Renate Knigge-Tesche  (skip=0) (6, 5)
bruenn_ charlotte_IS_S_00027/chronotopi_charlotte_bruenn_IS_S_00027 (file revisionato).xlsx Charlotte Bruenn geb. Hirsch (skip=0) (30, 5)
bruenn_ charlotte_IS_S_00027/chronotopi_charlotte_bruenn_IS_S_00027 (file revisionato).xlsx Ludwig Hirsch (skip=0) (5, 5)
bruenn_ charlotte_IS_S_00027/chronotopi_charlotte_bruenn_IS_S_00027 (file revisionato).xlsx Gutta Hirsch geb. Dingfelder (skip=0) (5, 5)
bruenn_ charlotte_IS_S_00027/chronotopi_charlotte_bruenn_IS_S_00027 (file revisionato).xlsx Alice Hirsch (Estryn) (skip=0) (2, 5)
bruenn_ charlotte_IS_S_00027/chronotopi_charlotte_bruenn_IS_S_00027 (file revisionato).xlsx Erich Hirsch (skip=0) (4, 5)
bruenn_ charlotte_IS_S_00027/chronotopi_charlotte_bruenn_IS_S_00027 (file revisionato).xlsx Walter Hirsch (skip=0) (2, 5)
bruenn_ charlotte_IS_S_00027/chronotopi_charlotte_bruenn_IS_S_00027 (file revisionato).xlsx Alfons Justin Hirsch (skip=0) (7, 5)
bruenn_ charlotte_IS_S_00027/chronotopi_charlotte_bruenn_IS_S_00027 (file revisionato).xlsx Margot Hirsch (skip=0) (5, 5)
Concepts to create: []

,event_label,date_label,notes,external_links,place_name,wikidata_qid,geonames_id,event_type,place_type,place_category,date_certainty,memorial_inscription,source_doc,source_timecode,source_quote,protagonist,name,start_location,end_location
0,Lebenslauf - Tod des Vaters,1923,24min01s. - 24min04s.,,Allenstein,,,,,,,,,,,bruenn_jehoshua_IS_S_00028,Foglio1,Allenstein,Allenstein
1,Lebenslauf - Schuljahren (Realschule),ca. 1927/1928,"Zuerst christliche Volksschule, dann (von der ...",,Allenstein,,,,,,,,,,,bruenn_jehoshua_IS_S_00028,Foglio1,Allenstein,Allenstein
2,Lebenslauf - Kaufmännische Lehre,1931,,,Allenstein,,,,,,,,,,,bruenn_jehoshua_IS_S_00028,Foglio1,Allenstein,Allenstein
3,Lebenslauf - Militärversuch,1931,Er hat 3 Jahren bei Frankenstein & Co (Warenha...,,Allenstein,,,,,,,,,,,bruenn_jehoshua_IS_S_00028,Foglio1,Allenstein,Allenstein
4,Lebenslauf - Berufstätigkeit,1931,Beruf: Kaufhaus für Konfektion (kurze Zeit). D...,https://gedenkbuch.saarbruecken.de/en/memorial...,Finsterwalde,,6550600,,,,,,,,,bruenn_jehoshua_IS_S_00028,Foglio1,Allenstein,Finsterwalde
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,Lebenslauf - Geburt / Alte Heimat,1928-03-03 00:00:00,Scheda LEA,https://gedenkbuch.saarbruecken.de/gedenkbuch/...,Homburg (Saar),Q7040,2899449,,,,,,,,,bruenn_ charlotte_IS_S_00027,Margot Hirsch,"Avignon (Provence), Frankreich",Homburg (Saar)
1,Lebenslauft - Jüdische Grundschule / Christlic...,ca. 1934–1935,39-40 CB: Fünfunddreißig nach der Abstimmung w...,,Homburg (Saar),Q7040,2899449,,,,,,,,,bruenn_ charlotte_IS_S_00027,Margot Hirsch,Homburg (Saar),Homburg (Saar)
2,Lebenslauf - Auswanderung,1935,40 weggegangen noch mit unsere Sachen alles. S...,https://gedenkbuch.saarbruecken.de/en/memorial...,"von Homburg (Saar) nach Nyons, Südfrankreich (...",Q209810,2989819,,,,,,,,,bruenn_ charlotte_IS_S_00027,Margot Hirsch,Homburg (Saar),"von Homburg (Saar) nach Nyons, Südfrankreich (..."
3,Lebenslauf – Versteck (bei einer Familie in Ma...,nach 25/08/1941,"Interview. Es ist nicht eindeutig, ob sich die...",https://gedenkbuch.saarbruecken.de/en/memorial...,Marseille,Q23482,6447142,,,,,,,,,bruenn_ charlotte_IS_S_00027,Margot Hirsch,"von Homburg (Saar) nach Nyons, Südfrankreich (...",Marseille
4,Leben unter falschem Namen,ab 1944,falscher Name „Marguerite Hilaire“ - Scheda LEA,https://gedenkbuch.saarbruecken.de/en/memorial...,Frankreich,,,,,,,,,,,bruenn_ charlotte_IS_S_00027,Margot Hirsch,Marseille,Frankreich

# Locations

In [6]:
locs = {}
for row in tqdm(df.to_dict(orient="records")):
    name = row["place_name"]
    if not name or name.strip() in ("", "nan"):
        continue
    locs[name] = {}

    # Place labels from type/category (empty for old format)
    place_labels = set()
    if row.get("place_type", "").strip():
        place_labels |= {row["place_type"].strip()}
    if row.get("place_category", "").strip():
        place_labels |= {row["place_category"].strip()}
    locs[name]["label"] = ",".join(place_labels)

    # Wikidata/geonames URLs from extracted IDs
    wq = row.get("wikidata_qid", "").strip()
    if wq and wq != "nan":
        locs[name]["www.wikidata.org"] = f"https://www.wikidata.org/wiki/{wq}"
    gn = row.get("geonames_id", "").strip()
    if gn and gn != "nan":
        locs[name]["www.geonames.org"] = f"https://www.geonames.org/{gn}"

    # Additional URLs from external_links
    urls, _ = extract_url_map(str(row.get("external_links", "")))
    for k, v in urls.items():
        if k not in locs[name]:
            locs[name][k] = v

print(locs)

100%|██████████████████████████████████████████████████| 344/344 [00:00<00:00, 84663.81it/s]

{'Allenstein': {'label': ''}, 'Finsterwalde': {'label': '', 'www.geonames.org': 'https://www.geonames.org/6550600', 'gedenkbuch.saarbruecken.de': 'https://gedenkbuch.saarbruecken.de/en/memorial_book/person_details/person-1183'}, 'Berlin (Brunnenstraße)': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q992834'}, 'Berling (Kolonnenstraße)': {'label': ''}, 'Berlin': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q64', 'www.geonames.org': 'https://www.geonames.org/2950159', 'en.wikipedia.org': 'https://en.wikipedia.org/wiki/Herbert_A._David'}, 'Berlin (Siemensstadt)': {'label': '', 'www.geonames.org': 'https://www.geonames.org/2832373'}, 'Weißensee': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q675174'}, 'Paris, Frankreich': {'label': '', 'www.geonames.org': 'https://www.geonames.org/2988507', 'gedenkbuch.saarbruecken.de': 'https://gedenkbuch.saarbruecken.de/en/memorial_book/person_details/person-1183'}, 'Paris, Montmartre Friedhof': {'label': '', 'www.geonames.org': 'https://www.geonames.org/6452785'}, 'Südfrankreich': {'label': '', 'gedenkbuch.saarbruecken.de': 'https://gedenkbuch.saarbruecken.de/gedenkbuch/personen_detailseite/person-3855'}, 'Marseille': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q23482', 'www.geonames.org': 'https://www.geonames.org/6447142', 'gedenkbuch.saarbruecken.de': 'https://gedenkbuch.saarbruecken.de/en/memorial_book/person_details/person-3997'}, 'Palästina (über Marseille)': {'label': '', 'gedenkbuch.saarbruecken.de': 'https://gedenkbuch.saarbruecken.de/en/memorial_book/person_details/person-1183'}, 'Haifa': {'label': ''}, 'En-Charod': {'label': '', 'www.geonames.org': 'https://www.geonames.org/295210'}, 'Jordan': {'label': '', 'www.geonames.org': 'https://www.geonames.org/248816'}, 'Zürich': {'label': '', 'www.geonames.org': 'https://www.geonames.org/2657896'}, 'Tel Aviv': {'label': ''}, 'Naher Osten': {'label': ''}, 'Ägypten/Irak/Iran': {'label': ''}, 'Jaffa': {'label': ''}, 'Leicester': {'label': ''}, 'Frankfurt/M': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q1794', 'www.geonames.org': 'https://www.geonames.org/2925533'}, 'Fränkisch Crumbach': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q622126', 'www.geonames.org': 'https://www.geonames.org/2925507'}, 'Grundschule - Volksschule': {'label': ''}, 'Höchst im Odenwald': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q634819', 'www.geonames.org': 'https://www.geonames.org/2902951'}, 'R 7, 24 (Strasse)': {'label': ''}, 'Google maps:': {'label': '', 'tinyurl.com': 'https://tinyurl.com/33y47jxx'}, 'Mannheim Hauptbahnof': {'label': ''}, 'Frankfurt Hauptbahnof': {'label': ''}, 'Hoek van Holland': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q2792592', 'www.geonames.org': 'https://www.geonames.org/2754007'}, 'Harwich': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q990616', 'www.geonames.org': 'https://www.geonames.org/4939008'}, 'Tynemouth': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q1755020', 'www.geonames.org': 'https://www.geonames.org/2635269'}, 'Windermere': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q390370', 'www.geonames.org': 'https://www.geonames.org/2633852', 'www.facebook.com': 'https://www.facebook.com/groups/OldBowness/posts/3431692513769892/'}, 'Frascati': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q190963', 'www.geonames.org': 'https://www.geonames.org/3176589'}, 'Australia': {'label': '', 'www.geonames.org': 'https://www.geonames.org/2077456', 'en.wikipedia.org': 'https://en.wikipedia.org/wiki/Herbert_A._David'}, 'Iowa': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q1546', 'www.geonames.org': 'https://www.geonames.org/4862182'}, 'Iowa State University': {'label': ''}, 'Mannheim': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q2119', 'www.geonames.org': 'https://www.geonames.org/2873891', 'archiv.schillerschule.de': 'https://archiv.schillerschule.de/images/dokumente/Ehemalige/Schiller-EXtra/schillerextra_11.pdf)'}, 'Frankfurt': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q1794', 'www.geonames.org': 'https://www.geonames.org/2925533', 'archiv.schillerschule.de': 'https://archiv.schillerschule.de/images/dokumente/Ehemalige/Schiller-EXtra/schillerextra_11.pdf'}, 'Heidelberg': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q2966', 'www.geonames.org': 'https://www.geonames.org/2907911'}, 'Göttingen': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q3033', 'www.geonames.org': 'https://www.geonames.org/2918632'}, 'Jena': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q3150', 'www.geonames.org': 'https://www.geonames.org/2895044'}, 'Kowno, Lituanien': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q4115712', 'www.geonames.org': 'https://www.geonames.org/598316'}, 'Gurs:': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q708638', 'www.geonames.org': 'https://www.geonames.org/12494761', 'it.wikipedia.org': 'https://it.wikipedia.org/wiki/Memoriale_di_Neckarzimmern'}, 'Frauen: Marseille': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q23482', 'www.geonames.org': 'https://www.geonames.org/2995469'}, 'Drancy:': {'label': '', 'www.geonames.org': 'https://www.geonames.org/12077049'}, 'Auschwitz': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q663764', 'www.geonames.org': 'https://www.geonames.org/7701596'}, '<': {'label': ''}, 'Odenwald - Fränkisch Crumbach': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q622126', 'www.geonames.org': 'https://www.geonames.org/2925507'}, 'Erbacher Straße 17 Fränkisch Crumbach': {'label': '', 'www.alte-zigarrenfabrik.com': 'https://www.alte-zigarrenfabrik.com/wp-content/uploads/2022/04/Oppenheimer.endgueltige-Fassung.pdf'}, '(1884-1922)': {'label': ''}, 'Rexingen': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q2147112', 'www.geonames.org': 'https://www.geonames.org/2847721'}, 'Tod': {'label': ''}, 'Buchenwald': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q152802', 'www.geonames.org': 'https://www.geonames.org/8644023'}, 'Männer: Camp des Milles': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q481647'}, 'Bad König': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q379121', 'www.geonames.org': 'https://www.geonames.org/2953419', 'www.alte-zigarrenfabrik.com': 'https://www.alte-zigarrenfabrik.com/wp-content/uploads/2022/04/Oppenheimer.endgueltige-Fassung.pdf;', 'www.museum.de': 'https://www.museum.de/audioguide/34/39/DE/0;', 'www.myheritage.it': 'https://www.myheritage.it/names/isaak_oppenheimer'}, 'Michelstadt': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q516517', 'www.geonames.org': 'https://www.geonames.org/2871284'}, 'USA New York': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q1384', 'www.geonames.org': 'https://www.geonames.org/5128581'}, 'Groß-Bieberau': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q539579', 'www.geonames.org': 'https://www.geonames.org/2916966'}, 'Odenwald:': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q8359', 'www.geonames.org': 'https://www.geonames.org/2858101'}, 'Argentinien:': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q414', 'www.geonames.org': 'https://www.geonames.org/3865483'}, 'New York': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q1384', 'www.geonames.org': 'https://www.geonames.org/5128581'}, 'Geburt': {'label': '', 'www.sommer-archive.com': 'https://www.sommer-archive.com/english'}, 'Sussex:': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q23346'}, 'New York:': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q1384', 'www.geonames.org': 'https://www.geonames.org/5128581'}, 'Cornell University': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q49115'}, 'Upstate University Hospital': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q30254105', 'www.geonames.org': 'https://www.geonames.org/7180645'}, 'Syracuse': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q128069', 'www.geonames.org': 'https://www.geonames.org/5140405', 'obits.syracuse.com': 'https://obits.syracuse.com/us/obituaries/syracuse/name/hannah-oppenheimer-obituary?id=39044601', 'ballweg.store.helloflowers.com': 'https://ballweg.store.helloflowers.com/obituaries/Hannah-Oppenheimer/#!/TributeWall'}, 'Robert Sommer': {'label': ''}, 'Paris:': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q90', 'www.geonames.org': 'https://www.geonames.org/2988507'}, 'Frankfurt/Munchen': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q1726', 'www.geonames.org': 'https://www.geonames.org/2867714'}, 'York': {'label': ''}, '1955': {'label': ''}, 'Wien': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q702289', 'www.geonames.org': 'https://www.geonames.org/2761369', 'de.wikipedia.org': 'https://de.wikipedia.org/wiki/Alice_Urbach'}, 'Mill Valley': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q846413', 'de.wikipedia.org': 'https://de.wikipedia.org/wiki/Alice_Urbach'}, 'Paris': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q90', 'www.geonames.org': 'https://www.geonames.org/2988507', 'www.sommer-archive.com': 'https://www.sommer-archive.com/english'}, 'Hilfsperson Michael und Fedora': {'label': ''}, 'Hessen:': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q1199', 'www.geonames.org': 'https://www.geonames.org/2905330', 'www.vrm-trauer.de': 'https://www.vrm-trauer.de/traueranzeige/renate-knigge-tesche'}, 'Renate Knigge-Tesche (1947–2025) war eine deutsche Bildungsreferentin für politische Bildung im Bundesland Hessen.': {'label': ''}, 'Homburg (Saar)': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q7040', 'www.geonames.org': 'https://www.geonames.org/2899449'}, 'von Homburg (Saar) nach Nyons, Südfrankreich (bei Avignon)    hôtel Monnier, puis s’installent place de la République': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q209810', 'www.geonames.org': 'https://www.geonames.org/2989819', 'www.facebook.com': 'https://www.facebook.com/groups/nyonsaujourdhui/posts/1239122821734315/'}, 'Nyons Südfrankreich': {'label': '', 'gedenkbuch.saarbruecken.de': 'https://gedenkbuch.saarbruecken.de/en/memorial_book/person_details/person-1182'}, 'Nyons, Südfrankreich': {'label': '', 'gedenkbuch.saarbruecken.de': 'https://gedenkbuch.saarbruecken.de/en/memorial_book/person_details/person-1182'}, 'Umgebung von Nyons': {'label': ''}, 'Montpellier': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q6441', 'www.geonames.org': 'https://www.geonames.org/2992166'}, 'Pompignan/Hte. Garonne Nähe Toulouse': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q943312', 'www.geonames.org': 'https://www.geonames.org/6445017'}, 'Nähe Toulouse (Südfrankreich)': {'label': ''}, 'Toulouse     (bei Fernayrol, 5 rue Bayard)': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q7880', 'www.geonames.org': 'https://www.geonames.org/2972315', 'www.ajpn.org': 'http://www.ajpn.org/personne-Charlotte-Hirsch-10313.html', 'gedenkbuch.saarbruecken.de': 'https://gedenkbuch.saarbruecken.de/en/memorial_book/person_details/person-1182'}, 'Toulouse   Bahnhof Tolouse': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q7880', 'www.geonames.org': 'https://www.geonames.org/6301916'}, 'Südfrankreich  (Toulouse?)': {'label': ''}, 'Toulouse': {'label': '', 'gedenkbuch.saarbruecken.de': 'https://gedenkbuch.saarbruecken.de/en/memorial_book/person_details/person-1182'}, 'Marseille (Hafen)': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q34963701', 'www.geonames.org': 'https://www.geonames.org/12196053'}, 'Israel (Ramatayim / Ramat HaSharon)': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q7024558', 'www.geonames.org': 'https://www.geonames.org/294951', 'gedenkbuch.saarbruecken.de': 'https://gedenkbuch.saarbruecken.de/en/memorial_book/person_details/person-1182'}, 'Tel Aviv   (Ben-Jehuda-Straße)': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q33935', 'www.geonames.org': 'https://www.geonames.org/293397'}, 'Bnei Brak': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q152467', 'www.geonames.org': 'https://www.geonames.org/295514', 'gedenkbuch.saarbruecken.de': 'https://gedenkbuch.saarbruecken.de/en/memorial_book/person_details/person-1182'}, 'Israel': {'label': ''}, 'vermutlich Homburg (Saar)': {'label': '', 'gedenkbuch.saarbruecken.de': 'https://gedenkbuch.saarbruecken.de/en/memorial_book/person_details/person-3992'}, 'von Homburg nach Südfrankreich (bei Avignon)': {'label': '', 'gedenkbuch.saarbruecken.de': 'https://gedenkbuch.saarbruecken.de/en/memorial_book/person_details/person-3992'}, 'Nyons (Drôme), Frankreich': {'label': '', 'gedenkbuch.saarbruecken.de': 'https://gedenkbuch.saarbruecken.de/en/memorial_book/person_details/person-3992'}, 'Uehlfeld a/Aisch': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q33509937', 'www.geonames.org': 'https://www.geonames.org/2820334'}, 'von Homburg (Saar) nach Südfrankreich (bei Avignon)': {'label': '', 'gedenkbuch.saarbruecken.de': 'https://gedenkbuch.saarbruecken.de/gedenkbuch/personen_detailseite/person-3920%20/'}, 'Avignon (Südfrankreich)': {'label': ''}, 'England': {'label': ''}, 'von Homburg (Saar) nach Nyons, Südfrankreich (bei Avignon)': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q209810', 'www.geonames.org': 'https://www.geonames.org/2989819', 'gedenkbuch.saarbruecken.de': 'https://gedenkbuch.saarbruecken.de/en/memorial_book/person_details/person-1182'}, 'Orange - Vaucluse, Frankreich (wh. 32, Boulevard de la Mergue, Orange -Vauculuse)': {'label': '', 'gedenkbuch.saarbruecken.de': 'https://gedenkbuch.saarbruecken.de/gedenkbuch/personen_detailseite/person-3895'}, 'Orange (Frankreich)': {'label': '', 'gedenkbuch.saarbruecken.de': 'https://gedenkbuch.saarbruecken.de/gedenkbuch/personen_detailseite/person-3895'}, 'Südfrankreich?': {'label': ''}, 'Frankreich': {'label': '', 'gedenkbuch.saarbruecken.de': 'https://gedenkbuch.saarbruecken.de/en/memorial_book/person_details/person-3997'}, 'Avignon (Provence), Frankreich': {'label': '', 'gedenkbuch.saarbruecken.de': 'https://gedenkbuch.saarbruecken.de/gedenkbuch/personen_detailseite/person-3855'}}

## Update preexisting locations

In [7]:
rich = pd.read_excel("locations.xlsx", dtype=str)
rich = rich.set_index(["location"])

for location, row in locs.items():
    if location not in rich.index:
        rich.loc[location] = locs[location]

    # Add any new columns from locs that don't exist yet
    for col, val in row.items() if isinstance(row, dict) else {}:
        if col not in rich.columns:
            rich[col] = ""
        rich.loc[location, col] = str(val)

rich.to_excel("locations.xlsx")

# Timespan

In [8]:
df[["time_start", "time_end"]] = (
    df["date_label"].apply(lambda ts: list(parse_timespan(ts).as_tuple())).tolist()
)
df

,event_label,date_label,notes,external_links,place_name,wikidata_qid,geonames_id,event_type,place_type,place_category,...,memorial_inscription,source_doc,source_timecode,source_quote,protagonist,name,start_location,end_location,time_start,time_end
0,Lebenslauf - Tod des Vaters,1923,24min01s. - 24min04s.,,Allenstein,,,,,,...,,,,,bruenn_jehoshua_IS_S_00028,Foglio1,Allenstein,Allenstein,1923-01-01,1923-12-31
1,Lebenslauf - Schuljahren (Realschule),ca. 1927/1928,"Zuerst christliche Volksschule, dann (von der ...",,Allenstein,,,,,,...,,,,,bruenn_jehoshua_IS_S_00028,Foglio1,Allenstein,Allenstein,1927-01-01,1928-12-31
2,Lebenslauf - Kaufmännische Lehre,1931,,,Allenstein,,,,,,...,,,,,bruenn_jehoshua_IS_S_00028,Foglio1,Allenstein,Allenstein,1931-01-01,1931-12-31
3,Lebenslauf - Militärversuch,1931,Er hat 3 Jahren bei Frankenstein & Co (Warenha...,,Allenstein,,,,,,...,,,,,bruenn_jehoshua_IS_S_00028,Foglio1,Allenstein,Allenstein,1931-01-01,1931-12-31
4,Lebenslauf - Berufstätigkeit,1931,Beruf: Kaufhaus für Konfektion (kurze Zeit). D...,https://gedenkbuch.saarbruecken.de/en/memorial...,Finsterwalde,,6550600,,,,...,,,,,bruenn_jehoshua_IS_S_00028,Foglio1,Allenstein,Finsterwalde,1931-01-01,1931-12-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,Lebenslauf - Geburt / Alte Heimat,1928-03-03 00:00:00,Scheda LEA,https://gedenkbuch.saarbruecken.de/gedenkbuch/...,Homburg (Saar),Q7040,2899449,,,,...,,,,,bruenn_ charlotte_IS_S_00027,Margot Hirsch,"Avignon (Provence), Frankreich",Homburg (Saar),1928-03-03,1928-03-03
1,Lebenslauft - Jüdische Grundschule / Christlic...,ca. 1934–1935,39-40 CB: Fünfunddreißig nach der Abstimmung w...,,Homburg (Saar),Q7040,2899449,,,,...,,,,,bruenn_ charlotte_IS_S_00027,Margot Hirsch,Homburg (Saar),Homburg (Saar),1934-01-01,1935-12-31
2,Lebenslauf - Auswanderung,1935,40 weggegangen noch mit unsere Sachen alles. S...,https://gedenkbuch.saarbruecken.de/en/memorial...,"von Homburg (Saar) nach Nyons, Südfrankreich (...",Q209810,2989819,,,,...,,,,,bruenn_ charlotte_IS_S_00027,Margot Hirsch,Homburg (Saar),"von Homburg (Saar) nach Nyons, Südfrankreich (...",1935-01-01,1935-12-31
3,Lebenslauf – Versteck (bei einer Familie in Ma...,nach 25/08/1941,"Interview. Es ist nicht eindeutig, ob sich die...",https://gedenkbuch.saarbruecken.de/en/memorial...,Marseille,Q23482,6447142,,,,...,,,,,bruenn_ charlotte_IS_S_00027,Margot Hirsch,"von Homburg (Saar) nach Nyons, Südfrankreich (...",Marseille,1941-08-25,1941-08-25
4,Leben unter falschem Namen,ab 1944,falscher Name „Marguerite Hilaire“ - Scheda LEA,https://gedenkbuch.saarbruecken.de/en/memorial...,Frankreich,,,,,,...,,,,,bruenn_ charlotte_IS_S_00027,Margot Hirsch,Marseille,Frankreich,1944-01-01,1944-12-31

# Notes

left unprocessed for now

In [9]:
set(df["notes"])

{'',
 ' („so eine Art Hachschara“)',
 ' Bruder nach Oslo',
 ' Scheda Lea - lebte unter falschem Namen „Alexandre Hilaire“ ',
 ' Verbindung mit RUTH DAVID',
 ' falscher Name „Marguerite Hilaire“ - Scheda LEA',
 ' starb schwer krank, nicht durch NS-Verfolgung  (Interview)',
 '(Interview)',
 '(Interwiev)',
 '(bis ich achtzehn Jahre alt war) ',
 '1973: Jom Kippur Krieg ',
 '20 min 56',
 '24min01s. - 24min04s.',
 '26min 58s',
 '36min 51smein mittlerer Bruder weiß man bis heut nicht, er ist umgekommen, er war damals neunzehn Jahre in in Homburg + . Man hat ihn unter der Eisenbahn gefunden, man weiß bis heute nicht, ja. Das war diese Zeit, . Scheda LEA: 27.02.1936 mit den Eltern nach Nyons ausgewandert (https://gedenkbuch.saarbruecken.de/en/memorial_book/person_details/person-1182) Death 24 May 1935 Homburg, Saarpfalz\nSuicide',
 '39-40 CB: Fünfunddreißig nach der Abstimmung wie die Saar wurde deutsch und sind wir gleich',
 '39-40 CB: Fünfunddreißig nach der Abstimmung wie die Saar wurde deutsch und sind wir gleich (Interview)',
 '40 weggegangen noch mit unsere Sachen alles. Scheda LEA: 27.02.1936 mit den Eltern nach Nyons ausgewandert ',
 '40 weggegangen noch mit unsere Sachen alles. Scheda LEA: 27.02.1936 mit den Eltern nach Nyons ausgewandert (https://gedenkbuch.saarbruecken.de/en/memorial_book/person_details/person-1182)',
 '55 Percy Park in Tynemouth (NE30 4JZ)',
 'Am Anfang mit der Tante Betty',
 'April (wahrscheinlich) - strittiger Punkt',
 'Arbeit beim Dr. Blumenthal',
 'Arbeit in einem Restaurant',
 'Arbeiter bei den Bauern',
 'Beruf: Kaufhaus für Konfektion (kurze Zeit). Dann kam er nach Berlin, weil seine Schwester als Modezeichnerin dort arbeitete.',
 'Besuch des Grabes von Heinrich Heine. Dort trifft er sich mit seinem anderen Bruder',
 'Der Brufer empfängt ihn. Am Bahnhof lacht der Kartenverkäufer wegen Jehoschuas Berliner Dialekts',
 'Diskrepanz zwischen Inteview und Gedenkbuch',
 'Entscheidung für Palästina; Vorbereitung der Ausreise',
 'Er hat 3 Jahren bei Frankenstein & Co (Warenhaus) gearbeitet. ',
 'Er hatte einen Bauernschwager in Siemenstadt, also ist er eine Woche lang bei ihm geblieben. Inzwischen kam sein Bruder.',
 'Fragebogen',
 'Fragebogen ',
 'Google maps: https://tinyurl.com/33y47jxx',
 'Interview',
 'Interview  / Scheda LEA - wh. Nyons/Drôme, Villa Les feures bleues [sic]',
 'Interview. Es ist nicht eindeutig, ob sich die Aussage auf Margot oder auf Alice bezieht. In der LEA-Akte zu Margot wird Marseille nicht erwähnt; dort heißt es nur, dass sie zusammen mit ihren Eltern zwei Jahre bei einem Bauern in den Alpen versteckt war (die Kosten dafür übernahm ihr Bruder Erich).',
 'Intervista - 40 weggegangen noch mit unsere Sachen alles. Scheda LEA: 27.02.1936 mit den Eltern nach Nyons ausgewandert ',
 'Intervista - mein jüngster Bruder, der war damals achtzehn, neunzehn Jahr, genau weiß ich nicht mehr, hat er sich zur französischen Armee gemeldet, hat man ihn genommen, hat man gesagt, er wär die fünfte Kolonn, hab ich das erste Mal in meinem Leben gesehen ein ein Lager, Intern/ ähm + er war interniert',
 'LEA',
 'Mit seinem Bruder, der  in englischer Uniform kam nach En-Charod (er kam aus Basra). Er lernt English besser als in der Schule',
 "Non sono riuscita a geolocalizzare con esattezza l'Internierungslager di Marseille",
 'Oakburn Schule/Southwood Hostel ',
 'Paratyphus',
 'Pardess Katz b/Tel-Aviv, Shikun Jessodoth 5, Israel',
 'R 7, 24 (Strasse)',
 'RS / Archivdaten',
 'Scheda Aj',
 'Scheda LEA',
 'Scheda LEA  ',
 'Scheda LEA: 26. August 1942 - August 1944: Inhaftierung der Mutter / 9413 Bl 62: 16.08.1942 verhaftet in Nyons/Drôme von frz. Polizei, Sammellager Crest/Drôme n. Lyon-Vénissieux, von dort entflohen',
 'Scheda LEA: 26. August 1942 - August 1944: Inhaftierung der Mutter, Leben in Illegalität in Nyons, Pampignan, Sahume, Drome, Krankheiten',
 'Scheda Lea',
 'Scheda Lea ',
 'Scheda Lea - Betrieb in Nyons einen Handel mit Vieh und Milcherzeugnissen, lebte von Mitte 1942 bis Ende September 1944 illegal',
 'Scheda ML - Emigration 27.02.1936 nach Frankreich. Verw: Erich, Margot und Alfons Justin Hirsch, sowie Alice Estryn geb. Hirsch und Charlotte Brünn geb. Hirsch nach ihrem Vater; wh. Nyons/Drôme, Villa Les feures bleues [sic]',
 'Umzug  auf Anfrage der Polizei',
 'Zuerst christliche Volksschule, dann (von der None ab) Realschule. Das Datu, bezieht sich auf die Realschule',
 'auf dem Schiff war auch eine Prinzessin, eine Schwester von König Faruk',
 'der fünfte Zionistenkongress',
 'die schönsten jahre habe ich ja im versteck 33min 01s',
 'drei Monate -Schule',
 'https://gedenkbuch.saarbruecken.de/gedenkbuch/personen_detailseite/person-3855',
 'https://it.wikipedia.org/wiki/Azione_Wagner-B%C3%Bcrckel\nhttps://it.wikipedia.org/wiki/Memoriale_di_Neckarzimmern',
 'https://kindertransport.org/2023/01/the-lost-history-of-tynemouths-holocaust-safe-house-for-girls/',
 'https://www.geonames.org/2873891/mannheim.html',
 'https://www.mahnmal-neckarzimmern.de/gedenkbuch/oppenheimer-feodora',
 'https://www.theguardian.com/education/2018/mar/22/andrew-finch-obituary',
 'https://www.wikidata.org/wiki/Q2119',
 'im Unternehmen (Keller)'}

# Links

left unprocessed for now

In [10]:
urls = set()
for cell in df["external_links"]:
    if pd.notna(cell):
        for url in str(cell).split("\n"):
            url = url.strip()
            if url:
                urls.add(url)
urls

{'1940',
 'Dokumente, die im Jüdischen Museum Frankfurt eingesehen wurden',
 'Google maps: https://tinyurl.com/33y47jxx',
 "Informazione che non compare nell'intervista, ma documentata nella scheda LEA: https://gedenkbuch.saarbruecken.de/en/memorial_book/person_details/person-1182",
 'Nell\'intervista C. dice "Mit 26 Jahren" (ergo nel 1949), ma in altre fonti risulta che si è sposata nel 1951 (Scheda LEA: https://gedenkbuch.saarbruecken.de/en/memorial_book/person_details/person-1182; © Institut für Deutsche Sprache, Mannheim 2013)',
 'R 7, 24 (Strasse)',
 'chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://archiv.schillerschule.de/images/dokumente/Ehemalige/Schiller-EXtra/schillerextra_11.pdf',
 'chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://archiv.schillerschule.de/images/dokumente/Ehemalige/Schiller-EXtra/schillerextra_11.pdf)',
 'chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://www.alte-zigarrenfabrik.com/wp-content/uploads/2022/04/Oppenheimer.endgueltige-Fassung.pdf',
 'chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://www.alte-zigarrenfabrik.com/wp-content/uploads/2022/04/Oppenheimer.endgueltige-Fassung.pdf; https://www.museum.de/audioguide/34/39/DE/0; https://www.myheritage.it/names/isaak_oppenheimer',
 'http://www.ajpn.org/personne-Charlotte-Hirsch-10313.html https://gedenkbuch.saarbruecken.de/en/memorial_book/person_details/person-1182',
 'https://ballweg.store.helloflowers.com/obituaries/Hannah-Oppenheimer/#!/TributeWall',
 'https://collections.ushmm.org/search/catalog/irn631167; https://collections.ushmm.org/search/catalog/irn43213',
 'https://de.wikipedia.org/wiki/Alice_Urbach',
 'https://de.wikipedia.org/wiki/Margarethe_Oppenheimer',
 'https://en.wikipedia.org/wiki/Herbert_A._David',
 'https://espace.memomori.fr/deces/75/paris-19e/feodora-oppenheimer-commune-inconnue-2026-04-13-5380b6',
 'https://gedenkbuch.saarbruecken.de/en/memorial_book/person_details/person-1182',
 'https://gedenkbuch.saarbruecken.de/en/memorial_book/person_details/person-1183',
 'https://gedenkbuch.saarbruecken.de/en/memorial_book/person_details/person-3992',
 'https://gedenkbuch.saarbruecken.de/en/memorial_book/person_details/person-3997',
 'https://gedenkbuch.saarbruecken.de/gedenkbuch/personen_detailseite/person-3855',
 'https://gedenkbuch.saarbruecken.de/gedenkbuch/personen_detailseite/person-3895',
 'https://gedenkbuch.saarbruecken.de/gedenkbuch/personen_detailseite/person-3920 / https://gedenkbuch.saarbruecken.de/en/memorial_book/person_details/person-1182',
 'https://gedenkbuch.saarbruecken.de/gedenkbuch/personen_detailseite/person-3920%20/',
 'https://gedenkbuch.saarbruecken.de/gedenkbuch/personen_detailseite/person-3997',
 'https://it.wikipedia.org/wiki/Azione_Wagner-B%C3%Bcrckel',
 'https://it.wikipedia.org/wiki/Memoriale_di_Neckarzimmern',
 'https://kindertransport.org/2023/01/the-lost-history-of-tynemouths-holocaust-safe-house-for-girls/',
 'https://obits.syracuse.com/us/obituaries/syracuse/name/hannah-oppenheimer-obituary?id=39044601',
 'https://portal.ehri-project.eu/units/us-005578-irn40190?sort=detail',
 'https://stolpersteine-mainz.de/index.php/2025/05/06/nachruf-fuer-renate-knigge-tesche/',
 'https://www.ajpn.org/juste-Marie-Fenayrol-1068.html https://gedenkbuch.saarbruecken.de/en/memorial_book/person_details/person-1182;',
 'https://www.facebook.com/groups/OldBowness/posts/3431692513769892/',
 'https://www.facebook.com/groups/nyonsaujourdhui/posts/1239122821734315/',
 'https://www.mannheim.de/de/tourismus-entdecken/stadtgeschichte/stadtpunkte/migration-toleranz-verfolgung/juedisches-waisenhaus',
 'https://www.myheritage.it/names/isaak_oppenheimer',
 'https://www.sommer-archive.com/english',
 'https://www.theguardian.com/education/2018/mar/22/andrew-finch-obituary',
 'https://www.vrm-trauer.de/traueranzeige/renate-knigge-tesche',
 'www.alte-zigarrenfabrik.com/wp-content/uploads/2022/04/Oppenheimer.endgueltige-Fassung.pdf'}

# Events

TODO: incomplete due to too much noise. Issues:

- use LL or Lebenslauf, currently extracted as one, but need to be two equivalent
- "alter heimant" instread of "alte heimat"
- "Transport", "Tod des Vaters",  are not label

In [11]:
event_taxonomy = parse_mmd_taxonomy("../docs/tassonomia.mmd")
events = sorted(set(event_taxonomy.keys()), key=lambda x: -len(x))
len(events), events[:5] + ["..."] + events[-5:]

(372,
 ['Rodges zentrale Hachschara-Stelle der religiösen Arbeiterpartei',
  'Neue Heimat vom Verein der ehemaligen Gießener',
  "Stigmatisierung'Ostjuden'Weimarer Republik",
  'Città/regioni tedesche, austriache, ceche',
  'JPD Jüdischer Pfadfinderbund Deutschland',
  '...',
  '1998',
  'Tod',
  'USA',
  'Zug',
  'IPD'])

In [12]:
df["event"] = df["event_label"].apply(lambda x: extract_events(x, events))
df

,event_label,date_label,notes,external_links,place_name,wikidata_qid,geonames_id,event_type,place_type,place_category,...,source_doc,source_timecode,source_quote,protagonist,name,start_location,end_location,time_start,time_end,event
0,Lebenslauf - Tod des Vaters,1923,24min01s. - 24min04s.,,Allenstein,,,,,,...,,,,bruenn_jehoshua_IS_S_00028,Foglio1,Allenstein,Allenstein,1923-01-01,1923-12-31,"[Vater, Tod, Lebenslauf - des s]"
1,Lebenslauf - Schuljahren (Realschule),ca. 1927/1928,"Zuerst christliche Volksschule, dann (von der ...",,Allenstein,,,,,,...,,,,bruenn_jehoshua_IS_S_00028,Foglio1,Allenstein,Allenstein,1927-01-01,1928-12-31,"[Schule, Lebenslauf - Schuljahren (Real)]"
2,Lebenslauf - Kaufmännische Lehre,1931,,,Allenstein,,,,,,...,,,,bruenn_jehoshua_IS_S_00028,Foglio1,Allenstein,Allenstein,1931-01-01,1931-12-31,[Lebenslauf - Kaufmännische Lehre]
3,Lebenslauf - Militärversuch,1931,Er hat 3 Jahren bei Frankenstein & Co (Warenha...,,Allenstein,,,,,,...,,,,bruenn_jehoshua_IS_S_00028,Foglio1,Allenstein,Allenstein,1931-01-01,1931-12-31,[Lebenslauf - Militärversuch]
4,Lebenslauf - Berufstätigkeit,1931,Beruf: Kaufhaus für Konfektion (kurze Zeit). D...,https://gedenkbuch.saarbruecken.de/en/memorial...,Finsterwalde,,6550600,,,,...,,,,bruenn_jehoshua_IS_S_00028,Foglio1,Allenstein,Finsterwalde,1931-01-01,1931-12-31,"[Beruf, Lebenslauf - stätigkeit]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,Lebenslauf - Geburt / Alte Heimat,1928-03-03 00:00:00,Scheda LEA,https://gedenkbuch.saarbruecken.de/gedenkbuch/...,Homburg (Saar),Q7040,2899449,,,,...,,,,bruenn_ charlotte_IS_S_00027,Margot Hirsch,"Avignon (Provence), Frankreich",Homburg (Saar),1928-03-03,1928-03-03,"[alte Heimat, Lebenslauf - Geburt /]"
1,Lebenslauft - Jüdische Grundschule / Christlic...,ca. 1934–1935,39-40 CB: Fünfunddreißig nach der Abstimmung w...,,Homburg (Saar),Q7040,2899449,,,,...,,,,bruenn_ charlotte_IS_S_00027,Margot Hirsch,Homburg (Saar),Homburg (Saar),1934-01-01,1935-12-31,"[Schule, Lebenslauft - Jüdische Grund / Christ..."
2,Lebenslauf - Auswanderung,1935,40 weggegangen noch mit unsere Sachen alles. S...,https://gedenkbuch.saarbruecken.de/en/memorial...,"von Homburg (Saar) nach Nyons, Südfrankreich (...",Q209810,2989819,,,,...,,,,bruenn_ charlotte_IS_S_00027,Margot Hirsch,Homburg (Saar),"von Homburg (Saar) nach Nyons, Südfrankreich (...",1935-01-01,1935-12-31,"[Auswanderung, Lebenslauf -]"
3,Lebenslauf – Versteck (bei einer Familie in Ma...,nach 25/08/1941,"Interview. Es ist nicht eindeutig, ob sich die...",https://gedenkbuch.saarbruecken.de/en/memorial...,Marseille,Q23482,6447142,,,,...,,,,bruenn_ charlotte_IS_S_00027,Margot Hirsch,"von Homburg (Saar) nach Nyons, Südfrankreich (...",Marseille,1941-08-25,1941-08-25,"[Marseille, Familie, Lebenslauf – Versteck (be..."
4,Leben unter falschem Namen,ab 1944,falscher Name „Marguerite Hilaire“ - Scheda LEA,https://gedenkbuch.saarbruecken.de/en/memorial...,Frankreich,,,,,,...,,,,bruenn_ charlotte_IS_S_00027,Margot Hirsch,Marseille,Frankreich,1944-01-01,1944-12-31,"[Name, Leben unter falschem n]"

# Import to API

In [13]:
import os
import re
import requests
import openpyxl

BASE_URL = os.environ.get("MMT_API_URL", "http://localhost:8000/motm/api")
LOGIN_URL = os.environ.get("MMT_LOGIN_URL", "http://localhost:8000/admin/login/")
SESSION = requests.Session()

SESSION.get(LOGIN_URL)
SESSION.post(LOGIN_URL, data={
    "username": "admin",
    "password": "admin",
    "csrfmiddlewaretoken": SESSION.cookies["csrftoken"],
    "next": "/admin/",
})
SESSION.headers["X-CSRFToken"] = SESSION.cookies.get("csrftoken", "")
SESSION.headers["Referer"] = LOGIN_URL
print("Authenticated" if SESSION.cookies.get("sessionid") else "Login failed")


def api_get(endpoint, params=None):
    if params is None:
        params = {}
    params.setdefault("limit", 10000)
    resp = SESSION.get(f"{BASE_URL}/{endpoint}/", params=params)
    resp.raise_for_status()
    data = resp.json()
    return data["results"] if isinstance(data, dict) and "results" in data else data


def api_post(endpoint, payload):
    resp = SESSION.post(f"{BASE_URL}/{endpoint}/", json=payload)
    if resp.status_code >= 400:
        raise Exception(f"{resp.status_code} {resp.reason} for {endpoint}: {resp.text} (payload: {payload})")
    return resp.json()


def api_patch(endpoint, obj_id, payload):
    resp = SESSION.patch(f"{BASE_URL}/{endpoint}/{obj_id}/", json=payload)
    if resp.status_code >= 400:
        raise Exception(f"{resp.status_code} {resp.reason} for {endpoint}/{obj_id}: {resp.text} (payload: {payload})")
    return resp.json()


# --- Concepts ---
_concept_cache = {}


def get_or_create_concept(label):
    label = label.strip()
    if not label or label == "nan":
        return None
    key = label.lower()
    if key in _concept_cache:
        return _concept_cache[key]
    existing = api_get("concepts", params={"search": label})
    match = next((c for c in existing if c["label"].lower() == key), None)
    if match:
        _concept_cache[key] = match["id"]
        return match["id"]
    created = api_post("concepts", {"label": label})
    _concept_cache[key] = created["id"]
    return created["id"]


# --- Locations database (locations.xlsx) ---
LOCATIONS_XLSX = os.path.join(os.path.dirname(__file__) if "__file__" in dir() else ".", "locations.xlsx")
_locations_db = {}  # name.lower() -> {lat, long, wikidata_id, geonames_id, label, urls}

def _extract_id_from_url(url, prefix):
    """Extract ID from a URL like https://www.wikidata.org/wiki/Q1794 -> Q1794"""
    if not url:
        return None
    url = str(url).strip()
    if not url or url == "nan":
        return None
    idx = url.rfind("/")
    return url[idx+1:] if idx >= 0 else url

def load_locations_db():
    """Load locations.xlsx into _locations_db."""
    if not os.path.exists(LOCATIONS_XLSX):
        print(f"  locations.xlsx not found at {LOCATIONS_XLSX}, starting fresh")
        return
    wb = openpyxl.load_workbook(LOCATIONS_XLSX)
    ws = wb.active
    for r in range(2, ws.max_row + 1):
        name = ws.cell(r, 1).value
        if not name:
            continue
        key = str(name).strip().lower()
        wikidata_url = str(ws.cell(r, 6).value or "").strip()
        geonames_url = str(ws.cell(r, 5).value or "").strip()
        extra_url = str(ws.cell(r, 7).value or "").strip()
        _locations_db[key] = {
            "name": str(name).strip(),
            "lat": ws.cell(r, 2).value,
            "long": ws.cell(r, 3).value,
            "label": str(ws.cell(r, 4).value or "").strip(),
            "wikidata_id": _extract_id_from_url(wikidata_url, "wikidata.org"),
            "geonames_id": _extract_id_from_url(geonames_url, "geonames.org"),
            "wikidata_url": wikidata_url if wikidata_url and wikidata_url != "nan" else "",
            "geonames_url": geonames_url if geonames_url and geonames_url != "nan" else "",
            "extra_url": extra_url if extra_url and extra_url != "nan" else "",
        }
    print(f"  Loaded {len(_locations_db)} locations from locations.xlsx")

def save_locations_db():
    """Save _locations_db back to locations.xlsx."""
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.append(["location", "lat", "long", "label", "www.geonames.org", "www.wikidata.org", "www.giessen.de"])
    for key in sorted(_locations_db.keys()):
        loc = _locations_db[key]
        ws.append([
            loc["name"],
            loc.get("lat") or "",
            loc.get("long") or "",
            loc.get("label", ""),
            loc.get("geonames_url", ""),
            loc.get("wikidata_url", ""),
            loc.get("extra_url", ""),
        ])
    wb.save(LOCATIONS_XLSX)
    print(f"  Saved {len(_locations_db)} locations to locations.xlsx")

def upsert_location_db(name, wikidata_qid=None, geonames_id=None):
    """Add location to the database if not already present."""
    if not name or str(name).strip() in ("", "nan"):
        return
    name = str(name).strip()
    key = name.lower()
    if key in _locations_db:
        # Enrich existing entry with external IDs if provided
        if wikidata_qid and wikidata_qid not in ("", "nan") and not _locations_db[key].get("wikidata_id"):
            _locations_db[key]["wikidata_id"] = wikidata_qid
            _locations_db[key]["wikidata_url"] = f"https://www.wikidata.org/wiki/{wikidata_qid}"
        if geonames_id and geonames_id not in ("", "nan") and not _locations_db[key].get("geonames_id"):
            _locations_db[key]["geonames_id"] = geonames_id
            _locations_db[key]["geonames_url"] = f"https://www.geonames.org/{geonames_id}"
        return
    _locations_db[key] = {
        "name": name,
        "lat": None,
        "long": None,
        "label": "",
        "wikidata_id": wikidata_qid if wikidata_qid and wikidata_qid not in ("", "nan") else "",
        "geonames_id": geonames_id if geonames_id and geonames_id not in ("", "nan") else "",
        "wikidata_url": f"https://www.wikidata.org/wiki/{wikidata_qid}" if wikidata_qid and wikidata_qid not in ("", "nan") else "",
        "geonames_url": f"https://www.geonames.org/{geonames_id}" if geonames_id and geonames_id not in ("", "nan") else "",
        "extra_url": "",
    }

load_locations_db()

_location_cache = {}

def get_or_create_location(name, wikidata_qid=None, geonames_id=None):
    """Create or retrieve a LocationPoint, using locations.xlsx for coordinates."""
    if not name or str(name).strip() in ("", "nan"):
        return None
    name = str(name).strip()
    key = name.lower()
    if key in _location_cache:
        return _location_cache[key]
    existing = api_get("locations", params={"search": name})
    match = next((loc for loc in existing if loc["current_name"].lower() == key), None)
    if match:
        _location_cache[key] = match["id"]
        return match["id"]
    # Build payload from locations.xlsx data
    db_entry = _locations_db.get(key, {})
    payload = {"current_name": name}
    # Coordinates from locations.xlsx
    lat = db_entry.get("lat")
    lng = db_entry.get("long")
    if lat and lng:
        try:
            payload["latitude"] = float(lat)
            payload["longitude"] = float(lng)
        except (ValueError, TypeError):
            pass
    # External IDs: prefer locations.xlsx, fall back to function args
    wid = db_entry.get("wikidata_id") or (wikidata_qid if wikidata_qid and wikidata_qid not in ("", "nan") else None)
    gid = db_entry.get("geonames_id") or (geonames_id if geonames_id and geonames_id not in ("", "nan") else None)
    if wid:
        payload["wikidata_id"] = wid
    if gid:
        payload["geonames_id"] = gid
    created = api_post("locations", payload)
    _location_cache[key] = created["id"]
    return created["id"]


# --- Persons ---
_person_cache = {}


def get_person_id(protagonist_dir, sheet_name):
    """Look up person by identifier extracted from directory name, then by sheet name."""
    if protagonist_dir in _person_cache:
        return _person_cache[protagonist_dir]
    # Try identifier: "stern_IS_S_00142" → "IS_S_00142"
    parts = protagonist_dir.split("_", 1)
    if len(parts) > 1:
        identifier = parts[1]
        existing = api_get("persons", params={"search": identifier})
        match = next((p for p in existing if p.get("identifier") == identifier), None)
        if match:
            _person_cache[protagonist_dir] = match["id"]
            return match["id"]
    # Fallback: search by sheet name (e.g. "Josef Stern")
    existing = api_get("persons", params={"search": sheet_name})
    if existing:
        _person_cache[protagonist_dir] = existing[0]["id"]
        return existing[0]["id"]
    return None


# --- Timespans ---
_timespan_cache = {}


def get_or_create_timespan(start=None, end=None):
    if start is None and end is None:
        return None
    s_iso = start.isoformat() if start else None
    e_iso = end.isoformat() if end else None
    key = (s_iso, e_iso)
    if key in _timespan_cache:
        return _timespan_cache[key]
    existing = api_get("timespans")
    for ts in existing:
        if ts.get("start") == s_iso and ts.get("end") == e_iso:
            _timespan_cache[key] = ts["id"]
            return ts["id"]
    created = api_post("timespans", {"start": s_iso, "end": e_iso})
    _timespan_cache[key] = created["id"]
    return created["id"]


# --- URLs ---
_url_cache = {}


def get_or_create_url(url_str):
    url_str = url_str.strip()
    if not url_str or url_str == "nan":
        return None
    if url_str in _url_cache:
        return _url_cache[url_str]
    existing = api_get("urls")
    for u in existing:
        if u["url"] == url_str:
            _url_cache[url_str] = u["id"]
            return u["id"]
    try:
        created = api_post("urls", {"url": url_str})
        _url_cache[url_str] = created["id"]
        return created["id"]
    except Exception as e:
        print(f"  URL creation failed for {url_str}: {e}")
        return None


def extract_urls_from_text(text):
    """Extract URLs from a text field."""
    if not text or str(text).strip() in ("", "nan"):
        return []
    return re.findall(r"https?://[^\s<>\"{}|\\^`\[\]]+", str(text))


def clean_str(val):
    """Return cleaned string or empty string for nan/blank values."""
    s = str(val).strip()
    if s in ("", "nan"):
        return ""
    # Strip .0 suffix from float-converted IDs (e.g. '2920512.0' -> '2920512')
    if s.endswith(".0") and s[:-2].isdigit():
        s = s[:-2]
    return s


# === Main import ===

# 1. Create all concepts
print("Creating concepts...")
for label in sorted(concept_labels):
    get_or_create_concept(label)
print(f"  {len(concept_labels)} concept labels processed")

# 1b. Build concept taxonomy (parent + icon)
print("Setting up concept taxonomy...")
import json as _json
with open("taxonomy.json", "r") as _f:
    _tax = _json.load(_f)

# Create root categories with icons
_cat_ids = {}  # category key -> concept id
for key, info in _tax["categories"].items():
    cid = get_or_create_concept(info["label"])
    if cid:
        api_patch("concepts", cid, {"icon": info["icon"], "parent": None})
        _cat_ids[key] = cid

# Create sub-categories with parent
_subcat_ids = {}
for key, info in _tax["sub_categories"].items():
    cid = get_or_create_concept(info["label"])
    parent_id = _cat_ids.get(info["parent"])
    if cid and parent_id:
        root_icon = _tax["categories"][info["parent"]]["icon"]
        api_patch("concepts", cid, {"icon": root_icon, "parent": parent_id})
        _subcat_ids[key] = cid

# Set parent + icon on each mapped leaf concept
for label, cat_key in _tax["concept_to_category"].items():
    cid = _concept_cache.get(label.lower().strip())
    if not cid:
        cid = get_or_create_concept(label)
    if cid:
        root_icon = _tax["categories"][cat_key]["icon"]
        parent_id = _cat_ids.get(cat_key)
        api_patch("concepts", cid, {"icon": root_icon, "parent": parent_id})

# Set icon on unmapped concepts (default to empty)
print(f"  Taxonomy set up: {len(_cat_ids)} roots, {len(_subcat_ids)} sub-cats")


# 2. Import events
print("\nImporting events...")
created_events = []
errors = []

for idx, (_, row) in enumerate(tqdm(df.iterrows(), total=len(df), desc="Events")):
    try:
        # Timespan from date_label
        date_label = clean_str(row["date_label"])
        ts = parse_timespan(date_label) if date_label else None
        timespan_id = get_or_create_timespan(ts.start, ts.end) if ts and ts.start else None

        # Upsert locations into the locations database
        upsert_location_db(
            row["end_location"],
            wikidata_qid=clean_str(row.get("wikidata_qid", "")),
            geonames_id=clean_str(row.get("geonames_id", "")),
        )
        upsert_location_db(row["start_location"])

        # Locations with external IDs
        end_loc_id = get_or_create_location(
            row["end_location"],
            wikidata_qid=clean_str(row.get("wikidata_qid", "")),
            geonames_id=clean_str(row.get("geonames_id", "")),
        )
        start_loc_id = get_or_create_location(row["start_location"])

        # Person
        person_id = get_person_id(row["protagonist"], row["name"])

        # is_confirmed from date_certainty
        date_certainty = clean_str(row.get("date_certainty", ""))
        is_confirmed = date_certainty.lower() in ("certain", "sicher", "yes", "ja")

        # Event description
        description = clean_str(row["event_label"])

        # Build event payload
        payload = {
            "description": description,
            "is_confirmed": is_confirmed,
        }
        if timespan_id:
            payload["timespan"] = timespan_id
        if start_loc_id:
            payload["start_location"] = start_loc_id
        if end_loc_id:
            payload["end_location"] = end_loc_id
        if person_id:
            payload["persons"] = [person_id]

        # URLs from external_links
        url_ids = []
        for url_str in extract_urls_from_text(row.get("external_links", "")):
            if "geonames.org" in url_str or "wikidata.org" in url_str:
                continue
            uid = get_or_create_url(url_str)
            if uid:
                url_ids.append(uid)
        if url_ids:
            payload["urls"] = url_ids

        # Concepts from event_type, place_type, place_category
        concept_ids = []
        for col in ["event_type", "place_type", "place_category"]:
            val = clean_str(row.get(col, ""))
            if val:
                cid = get_or_create_concept(val)
                if cid:
                    concept_ids.append(cid)

        if concept_ids:
            payload["concepts"] = concept_ids

        event = api_post("events", payload)
        event_id = event["id"]

        # Extraction to link concepts, source data, and notes
        source_quote = clean_str(row.get("source_quote", ""))
        source_timecode = clean_str(row.get("source_timecode", ""))
        source_doc = clean_str(row.get("source_doc", ""))
        memorial = clean_str(row.get("memorial_inscription", ""))

        # Build extraction notes from memorial_inscription, source_doc, original notes
        notes_parts = []
        if memorial:
            notes_parts.append(f"Memorial inscription: {memorial}")
        if source_doc:
            notes_parts.append(f"Source: {source_doc}")
        extraction_notes = "\n".join(notes_parts)

        if concept_ids or source_quote or extraction_notes:
            extraction_payload = {
                "event": event_id,
                "quote": source_quote,
                "timecode": source_timecode,
                "notes": extraction_notes,
            }
            if person_id:
                extraction_payload["people_mentioned"] = person_id
            if concept_ids:
                extraction_payload["concepts"] = concept_ids
            api_post("extractions", extraction_payload)

        created_events.append(event_id)
    except Exception as e:
        errors.append(f"Row {idx}: {e}")

print(f"\nCreated {len(created_events)} events")
if errors:
    print(f"\n{len(errors)} errors:")
    for err in errors[:20]:
        print(f"  {err}")

# Save updated locations database
save_locations_db()

Authenticated
  Loaded 189 locations from locations.xlsx
Creating concepts...
  0 concept labels processed
Setting up concept taxonomy...
  Taxonomy set up: 10 roots, 23 sub-cats

Importing events...

Events: 100%|█████████████████████████████████████████████| 344/344 [01:10<00:00,  4.89it/s]

Created 341 events

3 errors:
  Row 283: 400 Bad Request for locations: {"current_name":["Ensure this field has no more than 100 characters."]} (payload: {'current_name': 'Renate Knigge-Tesche (1947–2025) war eine deutsche Bildungsreferentin für politische Bildung im Bundesland Hessen.'})
  Row 286: 400 Bad Request for locations: {"current_name":["Ensure this field has no more than 100 characters."]} (payload: {'current_name': 'von Homburg (Saar) nach Nyons, Südfrankreich (bei Avignon)    hôtel Monnier, puis s’installent place de la République', 'wikidata_id': 'Q209810', 'geonames_id': '2989819'})
  Row 287: 400 Bad Request for locations: {"current_name":["Ensure this field has no more than 100 characters."]} (payload: {'current_name': 'von Homburg (Saar) nach Nyons, Südfrankreich (bei Avignon)    hôtel Monnier, puis s’installent place de la République', 'wikidata_id': 'Q209810', 'geonames_id': '2989819'})
  Saved 189 locations to locations.xlsx