In [1]:
from glob import glob
import pandas as pd
from tqdm import tqdm

from utils import extract_url_map
from events import extract_events
from timespan import parse_timespan
from taxonomy import load_taxonomy

In [2]:
# root_path = "../data/schede mappatura/"
root_path = "../data/nuove schede/"

skip = {
    # "david_ruth_FEGB_E_00007": {"rows": 6, "cols": 1}
    "stern_IS_S_00142": {"rows": 2, "cols": 0},
    "chronotopoi_josef_stern_familie_v4a.xlsx": {"rows": 2, "cols": 0},
}

In [3]:
chrono_schede = glob(f"{root_path}*chronotop*")
chrono_schede = [c for c in chrono_schede if not c.endswith(":Zone.Identifier")]
chrono_schede

['../data/nuove schede/chronotopoi_josef_stern_familie_v4a.xlsx']

## A list of individual sources for experimentation

ignored in the oveall logic

# current = "bruenn_jehoshua_IS_S_00028/chronotopoi_bruenn_jehoshua_bozza.xlsx"
# current = "david_ruth_FEGB_E_00007/chronotopi_ruth_david_FEGB_E_00007.xlsx"
# current = "bruenn_ charlotte_IS_S_00027/chronotopi_charlotte_bruenn_IS_S_00027 (file revisionato).xlsx"
# current = "stern_IS_S_00142/chronotopi_josef_stern_IS_S_00142.xlsx"
current = "chronotopoi_josef_stern_familie_v4a.xlsx"

chrono_schede = [s for s in chrono_schede if current in s]
chrono_schede

In [4]:
import openpyxl

overview = {}
for s in chrono_schede:
    wb = openpyxl.load_workbook(s)
    overview[s] = wb.sheetnames
overview

{'../data/nuove schede/chronotopoi_josef_stern_familie_v4a.xlsx': ['Josef Stern',
  'Isaak Stern',
  'Auguste Stern',
  'Betty Kaminka',
  'David Kaminka',
  'Julius Stern',
  'Johanna Stern',
  'Claire Stern',
  'Sonja Stern',
  'Esther Stern',
  '_Vokabular',
  '_README']}

After identification of all sources

# Shortlist processable sources

overview = {
    "chronotopoi_josef_stern_familie_v4a.xlsx": [
        "Josef Stern",
    ],
}

## Put all data together

In [ ]:
first = True

df_list = []
for k, v in overview.items():
    for s in v:
        if s.startswith("_"):
            continue
        # Extract name from k: try both nested path (for schede mappatura) and filename (for nuove schede)
        name = k.split("/")[-1] if "/" in k else k
        # print(k,s)
        # name = s
        config = skip.get(name)
        if config:
            df = pd.read_excel(
                k, sheet_name=s, skiprows=config["rows"]
            ).iloc[:, config["cols"] :]
        else:
            # Reviewed chronotopoi sheets may have title/metadata rows before the header.
            # Locate event_label instead of assuming every workbook starts at row zero.
            preview = pd.read_excel(k, sheet_name=s, header=None, nrows=10)
            header_row = next(
                (
                    int(index)
                    for index, values in preview.iterrows()
                    if "event_label" in {
                        str(value).strip() for value in values if pd.notna(value)
                    }
                ),
                0,
            )
            df = pd.read_excel(k, sheet_name=s, header=header_row)

        print(k, s, f"Columns: {list(df.columns)}")
        
        # The Excel file already has proper column names. Just ensure we have the ones we need.
        # If columns are named correctly, we can use them directly.
        # Otherwise, rename to the expected schema.
        
        # Only rename if the first column is not a proper name (i.e., when we have Unnamed columns)
        if "Unnamed:" in str(df.columns[0]):
            # Old format - needs renaming
            df.columns = [
                "event_label",
                "event_type",
                "place_name",
                "place_type",
                "place_category",
                "wikidata_qid",
                "geonames_id",
                "google maps",
                "date_certainty",
                "date_label",
                "memorial_inscription",
                "source_doc",
                "source_timecode",
                "source_quote",
                "external_links",
                "notes",
            ]
            # merge columns 6+ to notes
            df["notes"] = df[["notes"] + list(df.columns[6:])].apply(
                lambda row: " ".join(row.dropna().astype(str)), axis=1
            )
        else:
            # New format with proper column names - use as-is
            pass

        df["name"] = s
        df_list += [df]
df = pd.concat(df_list, axis=0).astype(str)
df.fillna("", inplace=True)

# Track start/end locations: end_location = current row's place,
# start_location = previous event's place (per person)
start_locations = []
prev_location = {}  # protagonist → last place_name
for _, row in df.iterrows():
    person = row["name"]
    end_loc = row["place_name"].strip()
    start_loc = prev_location.get(person, end_loc)  # fallback to same as end
    start_locations.append(start_loc)
    if end_loc:
        prev_location[person] = end_loc
df["start_location"] = start_locations
df["end_location"] = df["place_name"]

# Collect concepts from event_type, place_type, place_category
concept_labels = set()
for col in ["event_type", "place_category"]:  # Adjusted for new columns
    if col in df.columns:
        for val in df[col]:
            v = val.strip() if isinstance(val, str) else str(val).strip()
            if v and v not in ("nan", "None", ""):
                concept_labels.add(v)
print(f"Concepts to create: {sorted(concept_labels)}")

df

../data/nuove schede/chronotopoi_josef_stern_familie_v4a.xlsx Josef Stern Columns: ['event_id', 'event_label', 'event_type', 'place_name', 'place_detail', 'place_lat', 'place_lon', 'place_category', 'wikidata_qid', 'geonames_id', 'date_start', 'date_end', 'date_precision', 'date_certainty', 'date_label', 'journey_id', 'sequence_nr', 'transport_mode', 'memorial_for_event_id', 'memorial_inscription', 'source_doc', 'source_timecode', 'source_quote', 'external_links', 'notes', 'relation_to_main_person']
../data/nuove schede/chronotopoi_josef_stern_familie_v4a.xlsx Isaak Stern Columns: ['event_id', 'event_label', 'event_type', 'place_name', 'place_detail', 'place_lat', 'place_lon', 'place_category', 'wikidata_qid', 'geonames_id', 'date_start', 'date_end', 'date_precision', 'date_certainty', 'date_label', 'journey_id', 'sequence_nr', 'transport_mode', 'memorial_for_event_id', 'memorial_inscription', 'source_doc', 'source_timecode', 'source_quote', 'external_links', 'notes', 'relation_to_main_person']
../data/nuove schede/chronotopoi_josef_stern_familie_v4a.xlsx Auguste Stern Columns: ['event_id', 'event_label', 'event_type', 'place_name', 'place_detail', 'place_lat', 'place_lon', 'place_category', 'wikidata_qid', 'geonames_id', 'date_start', 'date_end', 'date_precision', 'date_certainty', 'date_label', 'journey_id', 'sequence_nr', 'transport_mode', 'memorial_for_event_id', 'memorial_inscription', 'source_doc', 'source_timecode', 'source_quote', 'external_links', 'notes', 'relation_to_main_person']
../data/nuove schede/chronotopoi_josef_stern_familie_v4a.xlsx Betty Kaminka Columns: ['event_id', 'event_label', 'event_type', 'place_name', 'place_detail', 'place_lat', 'place_lon', 'place_category', 'wikidata_qid', 'geonames_id', 'date_start', 'date_end', 'date_precision', 'date_certainty', 'date_label', 'journey_id', 'sequence_nr', 'transport_mode', 'memorial_for_event_id', 'memorial_inscription', 'source_doc', 'source_timecode', 'source_quote', 'external_links', 'notes', 'relation_to_main_person']
../data/nuove schede/chronotopoi_josef_stern_familie_v4a.xlsx David Kaminka Columns: ['event_id', 'event_label', 'event_type', 'place_name', 'place_detail', 'place_lat', 'place_lon', 'place_category', 'wikidata_qid', 'geonames_id', 'date_start', 'date_end', 'date_precision', 'date_certainty', 'date_label', 'journey_id', 'sequence_nr', 'transport_mode', 'memorial_for_event_id', 'memorial_inscription', 'source_doc', 'source_timecode', 'source_quote', 'external_links', 'notes', 'relation_to_main_person']
../data/nuove schede/chronotopoi_josef_stern_familie_v4a.xlsx Julius Stern Columns: ['event_id', 'event_label', 'event_type', 'place_name', 'place_detail', 'place_lat', 'place_lon', 'place_category', 'wikidata_qid', 'geonames_id', 'date_start', 'date_end', 'date_precision', 'date_certainty', 'date_label', 'journey_id', 'sequence_nr', 'transport_mode', 'memorial_for_event_id', 'memorial_inscription', 'source_doc', 'source_timecode', 'source_quote', 'external_links', 'notes', 'relation_to_main_person']
../data/nuove schede/chronotopoi_josef_stern_familie_v4a.xlsx Johanna Stern Columns: ['event_id', 'event_label', 'event_type', 'place_name', 'place_detail', 'place_lat', 'place_lon', 'place_category', 'wikidata_qid', 'geonames_id', 'date_start', 'date_end', 'date_precision', 'date_certainty', 'date_label', 'journey_id', 'sequence_nr', 'transport_mode', 'memorial_for_event_id', 'memorial_inscription', 'source_doc', 'source_timecode', 'source_quote', 'external_links', 'notes', 'relation_to_main_person']
../data/nuove schede/chronotopoi_josef_stern_familie_v4a.xlsx Claire Stern Columns: ['event_id', 'event_label', 'event_type', 'place_name', 'place_detail', 'place_lat', 'place_lon', 'place_category', 'wikidata_qid', 'geonames_id', 'date_start', 'date_end', 'date_precision', 'date_certainty', 'date_label', 'journey_id', 'sequence_nr', 'transport_mode', 'memorial_for_event_id', 'memorial_inscription', 'source_doc', 'source_timecode', 'source_quote', 'external_links', 'notes', 'relation_to_main_person']
../data/nuove schede/chronotopoi_josef_stern_familie_v4a.xlsx Sonja Stern Columns: ['event_id', 'event_label', 'event_type', 'place_name', 'place_detail', 'place_lat', 'place_lon', 'place_category', 'wikidata_qid', 'geonames_id', 'date_start', 'date_end', 'date_precision', 'date_certainty', 'date_label', 'journey_id', 'sequence_nr', 'transport_mode', 'memorial_for_event_id', 'memorial_inscription', 'source_doc', 'source_timecode', 'source_quote', 'external_links', 'notes', 'relation_to_main_person']
../data/nuove schede/chronotopoi_josef_stern_familie_v4a.xlsx Esther Stern Columns: ['event_id', 'event_label', 'event_type', 'place_name', 'place_detail', 'place_lat', 'place_lon', 'place_category', 'wikidata_qid', 'geonames_id', 'date_start', 'date_end', 'date_precision', 'date_certainty', 'date_label', 'journey_id', 'sequence_nr', 'transport_mode', 'memorial_for_event_id', 'memorial_inscription', 'source_doc', 'source_timecode', 'source_quote', 'external_links', 'notes', 'relation_to_main_person']
Concepts to create: ['administrative', 'alte_heimat', 'arrest', 'birth', 'death', 'deportation', 'education', 'emigration', 'emigration_transit', 'erinnerungsort', 'farewell', 'forced_designation', 'forced_eviction', 'immigration', 'marriage', 'memorial_gedenkbuch_berlin', 'memorial_gedenkbuch_bundesarchiv', 'memorial_stolperstein', 'memorial_street_name', 'memorial_yad_vashem', 'military_service', 'murder', 'neue_heimat', 'notification', 'ort_der_zeit', 'reise_zurueck', 'residence', 'residence_change', 'return_visit', 'return_visit_transit', 'transport_arrival', 'transport_departure', 'verkehrsmittel', 'work']

,event_id,event_label,event_type,place_name,place_detail,place_lat,place_lon,place_category,wikidata_qid,geonames_id,...,memorial_inscription,source_doc,source_timecode,source_quote,external_links,notes,relation_to_main_person,name,start_location,end_location
0,,Alte Heimat Geburt,birth,Gießen,Marktplatz 11,,,alte_heimat,Q564579,2920512.0,...,,,,,https://www.geonames.org/2920512/giessen.html\...,,,Josef Stern,Gießen,Gießen
1,,Alte Heimat Grundschule,education,Gießen,,,,alte_heimat,,,...,,,,,,,,Josef Stern,Gießen,Gießen
2,,Alte Heimat Realgymnasium,education,Gießen,,,,alte_heimat,,,...,,,,,,,,Josef Stern,Gießen,Gießen
3,,Wohnort,residence,Gießen,Löberstraße 20,,,alte_heimat,,,...,,,,,https://www.giessen.de/index.php?ModID=7&FID=2...,Aufräumung v4: place_name korrigiert von 'Löbe...,,Josef Stern,Gießen,Gießen
4,,Zwangsausweisung Marktplatz 11,forced_eviction,Gießen,Marktplatz 11,,,ort_der_zeit,Q564579,2920512.0,...,,Interview Metz 2010,11min 47s,Wir sind allerdings aus diesem schönen Haus gl...,,Josef war 12 Jahre alt. Erstes durch ihn erinn...,,Josef Stern,Gießen,Gießen
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13,ev_sister2_015,Erinnerung: Gedenkblatt Yad Vashem (Josef Stern),memorial_yad_vashem,Yad Vashem,"Halle der Namen, Jerusalem",,,erinnerungsort,Q156591,,...,,Yad Vashem Gedenkblatt; Reproduktion in [Aufsa...,,"Haifa, 16.9.1980 — am Jahrestag der Verschleppung",,"Eingereicht von Josef (Helmut) Stern (Bruder),...",sister,Esther Stern,Yad Vashem,Yad Vashem
14,ev_sister2_016,Erinnerung: Eintrag im Bundesarchiv-Gedenkbuch,memorial_gedenkbuch_bundesarchiv,Koblenz,Bundesarchiv,,,erinnerungsort,Q3920,,...,,"Bundesarchiv, Gedenkbuch – Opfer der Verfolgun...",,,https://apps.bundesarchiv.de/gedenkbuch/de976422,Bundesstaatliche Erinnerungsschicht (BRD),sister,Esther Stern,Yad Vashem,Koblenz
15,ev_sister2_014,Erinnerung: Gedenkblatt Yad Vashem (Ora Hadari),memorial_yad_vashem,Yad Vashem,"Halle der Namen, Jerusalem",,,erinnerungsort,Q156591,,...,,"Yad Vashem, Central Database of Shoah Victims'...",,,https://collections.yadvashem.org/en/names/132...,"Eingereicht von Ora Hadari (Nichte, Tochter Jo...",sister,Esther Stern,Koblenz,Yad Vashem
16,ev_sister2_007,Erinnerung Stolperstein,memorial_stolperstein,Gießen Marktplatz 15,Marktplatz 15 (ehem. Marktplatz 11; selbe Haus...,,,erinnerungsort,Q564579,2920512.0,...,HIER WOHNTE\nESTHER STERN\nJG. 1926\nDEPORTIER...,Stolperstein Marktplatz 15 Gießen; Foto via Wi...,,,https://commons.wikimedia.org/wiki/File:Stolpe...,Sammelstolperstein mit Julius Stern (ev_father...,sister,Esther Stern,Yad Vashem,Gießen Marktplatz 15
17,ev_sister2_008,Erinnerung Platz,memorial_street_name,Esther-Stern-Platz Gießen,,,,erinnerungsort,,,...,,,,,https://www.lotta-magazin.de/ausgabe/1/den-erm...,,sister,Esther Stern,Gießen Marktplatz 15,Esther-Stern-Platz Gießen

# Locations

In [6]:
# locs = {n:l for l, n in df["location"].apply(lambda x: extract_urls(x)).to_list()}
locs = {}
for row in tqdm(df.to_dict(orient="records")):
    # print(row)
    # print(extract_urls(row))
    name = row["place_name"]
    locs[name] = {}
    place_labels = set()
    if "place_type" in row and row["place_type"].strip():
        place_labels |= {row["place_type"].strip()}
    if row["place_category"].strip():
        place_labels |= {row["place_category"].strip()}
    locs[name]["label"] = ",".join(place_labels)

    urls = extract_url_map(row["external_links"])
    if (
        "www.wikidata.org" not in urls
        and "wikidata_id" in row
        and row["wikidata_qid"].strip()
    ):
        locs[name]["www.wikidata.org"] = (
            "https://www.wikidata.org/wiki/" + row["wikidata_qid"].strip()
        )
    if (
        "www.geonames.org" not in urls
        and "geonames_id" in row
        and row["geonames_id"].strip()
    ):
        locs[name]["www.geonames.org"] = (
            "https://www.geonames.org/" + row["geonames_id"].strip().removesuffix(".0")
        )

    locs[name].update(urls[0])
print(locs)

100%|█████████████████████████████████████████████████| 130/130 [00:00<00:00, 182850.27it/s]

{'Gießen': {'label': 'ort_der_zeit', 'www.geonames.org': 'https://www.geonames.org/2938913/darmstadt.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q2973'}, '': {'label': ''}, 'Schlesien': {'label': 'alte_heimat'}, 'Berlin': {'label': 'erinnerungsort'}, 'Frankfurt/M': {'label': 'alte_heimat', 'www.geonames.org': 'https://www.geonames.org/6553153/frankfurt-am-main.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q1794'}, 'Frankfurt am Main': {'label': 'reise_zurueck', 'www.geonames.org': 'https://www.geonames.org/6553153/frankfurt-am-main.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q1794'}, 'Kehl am Rhein': {'label': 'verkehrsmittel', 'www.geonames.org': 'https://www.geonames.org/2891951/kehl.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q15979'}, 'Brücke Kehl–Straßburg (Rheinquerung)': {'label': 'verkehrsmittel', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q1375288'}, 'Marseille': {'label': 'verkehrsmittel'}, 'Kibbuz Rodges, besteht nicht mehr (in der Nähe von Petah Tikva)': {'label': 'neue_heimat'}, 'Ēmeq Yizrəʿēl': {'label': 'neue_heimat', 'www.geonames.org': 'https://www.geonames.org/293165/jezreel-valley.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q763829'}, 'Kibbuz Ein HaNetziv': {'label': 'neue_heimat', 'www.geonames.org': 'https://www.geonames.org/295211/-en-hanaziv.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q2095906'}, 'Haifa': {'label': 'neue_heimat'}, 'Kibbuz Tirat Tsvi': {'label': 'neue_heimat', 'www.geonames.org': 'https://www.geonames.org/293304/tirat-tsvi.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q550025'}, 'Italien': {'label': 'reise_zurueck'}, 'Deutschland': {'label': 'reise_zurueck'}, 'Belgien': {'label': 'reise_zurueck'}, 'Niederlande': {'label': 'reise_zurueck'}, 'Klein-Linden': {'label': 'reise_zurueck', 'www.geonames.org': 'https://www.geonames.org/2888549/klein-linden.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q1571834'}, 'Großen-Linden': {'label': 'reise_zurueck', 'www.geonames.org': 'https://www.geonames.org/11974166/grossen-linden.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q116016915'}, 'Breidenbach': {'label': 'alte_heimat', 'www.geonames.org': 'https://www.geonames.org/2944820/breidenbach.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q564579'}, 'Steinstraße 19,': {'label': 'alte_heimat'}, 'Wullenweberstraße 11, Berlin-Moabit': {'label': 'erinnerungsort', 'www.geonames.org': 'https://www.geonames.org/2950159', 'www.stolpersteine-berlin.de': 'https://www.stolpersteine-berlin.de/de/wullenweberstr/11/auguste-stern'}, 'Wölfersheim': {'label': 'alte_heimat', 'www.geonames.org': 'https://www.geonames.org/2806852/woelfersheim.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q634098'}, 'Theresienstadt': {'label': 'ort_der_zeit', 'www.geonames.org': 'https://www.geonames.org/12217751/theresienstadt-concentration-camp-and-ghetto.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q160175'}, 'Koblenz': {'label': 'erinnerungsort', 'apps.bundesarchiv.de': 'https://apps.bundesarchiv.de/gedenkbuch/de976422'}, 'Yad Vashem': {'label': 'erinnerungsort', 'collections.yadvashem.org': 'https://collections.yadvashem.org/en/names/13219727'}, 'Baiertal': {'label': 'alte_heimat', 'www.geonames.org': 'https://www.geonames.org/2953189/baiertal.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q7904'}, 'Lollar': {'label': 'alte_heimat', 'www.geonames.org': 'https://www.geonames.org/6557780'}, 'United States': {'label': 'neue_heimat', 'www.geonames.org': 'https://www.geonames.org/6252001/united-states.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q30'}, 'Berdytschiw': {'label': 'alte_heimat', 'www.geonames.org': 'https://www.geonames.org/712441/berdychiv.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q7904'}, 'Oberhessen': {'label': '', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q15837262'}, 'Marktplatz 11': {'label': 'alte_heimat', 'www.giessen.de': 'https://www.giessen.de/index.php?ModID=7&FID=2874.2939.1&object=tx%7C2874.2939.1'}, 'Löberstraße 20': {'label': 'alte_heimat', 'www.giessen.de': 'https://www.giessen.de/index.php?ModID=7&FID=2874.2939.1&object=tx%7C2874.2939.1'}, 'Walltorstraße 48': {'label': 'ort_der_zeit'}, 'Stuttgart': {'label': 'alte_heimat', 'www.geonames.org': 'https://www.geonames.org/2825297/stuttgart.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q1022'}, 'Frankfurt (Main) Hauptbahnhof': {'label': 'alte_heimat', 'www.geonames.org': 'https://www.geonames.org/6290300/frankfurt-hauptbahnhof.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q165368'}, 'KZ Buchenwald': {'label': 'ort_der_zeit', 'www.geonames.org': 'https://www.geonames.org/8644023/konzentrationslager-buchenwald.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q152802'}, 'Darmstadt': {'label': 'verkehrsmittel', 'www.geonames.org': 'https://www.geonames.org/2938913/darmstadt.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q2973'}, 'Treblinka (Vernichtungslager)': {'label': 'ort_der_zeit', 'www.geonames.org': 'https://www.geonames.org/756807/treblinka.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q152010'}, 'Gießen Marktplatz 15': {'label': 'erinnerungsort', 'www.geonames.org': 'https://www.geonames.org/2920512', 'commons.wikimedia.org': 'https://commons.wikimedia.org/wiki/File:Stolperstein_Gießen_Marktplatz_15_Esther_Stern.JPG', 'www.giessen.de': 'https://www.giessen.de/Erleben/Über-Gießen/Stolpersteine/Marktplatz-15'}, 'Sennfeld (Adelsheim)': {'label': 'alte_heimat', 'www.geonames.org': 'https://www.geonames.org/2833011/sennfeld.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q14531586'}, 'aus Gießen nach Palästina': {'label': 'verkehrsmittel', 'atom.lib.uct.ac.za': 'https://atom.lib.uct.ac.za/uploads/r/university-of-cape-town-libraries-special-collections/a/3/c/a3cc8572f727d61327e4f929a86fc91c339c13cc41721aa18c8f158e13678891/mss_sahgf_schragenheim_publications_025_1-20.pdf'}, 'Gießen Schillerschule (Volksschule)': {'label': 'alte_heimat', 'de.wikipedia.org': 'https://de.wikipedia.org/wiki/Datei:Stolperstein_Gießen_Nordanlage_Esther_Stern.JPG', 'www.giessen.de': 'https://www.giessen.de/index.php?ModID=7&FID=2874.2967.1&object=tx%2C2874.2967.1'}, 'Esther-Stern-Platz Gießen': {'label': 'erinnerungsort', 'www.lotta-magazin.de': 'https://www.lotta-magazin.de/ausgabe/1/den-ermordeten-menschen-ein-gesicht-geben/'}}

## Add GO concepts as locations

Concepts under 'GO – Luoghi geografici' are geographic locations.
Add them to the locs dict so they get included in locations.xlsx.

In [7]:
from taxonomy import load_taxonomy

taxonomy = load_taxonomy()

go_concepts = [
    label for label, cat in taxonomy.concept_to_category.items()
    if cat == "GO"
]
# Also include GO sub-category labels
for key, info in taxonomy.sub_categories.items():
    if info.get("parent") == "GO":
        go_concepts.append(info["label"])

for concept_name in go_concepts:
    concept_name = concept_name.strip()
    if not concept_name:
        continue
    if concept_name not in locs:
        locs[concept_name] = {}
    if "label" not in locs[concept_name] or not locs[concept_name]["label"]:
        locs[concept_name]["label"] = "GO"

print(f"Added {len(go_concepts)} GO concepts to locations, total: {len(locs)}")

Added 0 GO concepts to locations, total: 45

## Update preexisting locations

In [8]:
import os
import re
from locations import enrich_locations_xlsx

def _normalize_loc(name):
    """Normalize for matching: lowercase, no punctuation, sorted words."""
    name = str(name).strip().lower()
    name = re.sub(r'[^\w\s]', '', name)
    return ' '.join(sorted(name.split()))

if os.path.exists("locations.xlsx"):
    rich = pd.read_excel("locations.xlsx", dtype=str)
    rich = rich.set_index(["location"])
else:
    rich = pd.DataFrame()
    rich.index.name = "location"

# Build a normalized index for flexible matching
existing_keys = {_normalize_loc(idx): idx for idx in rich.index}

for location, row in locs.items():
    key = _normalize_loc(location)

    if key in existing_keys:
        # Enrich existing row: only fill absent cells
        real_idx = existing_keys[key]
        if isinstance(row, dict):
            for col, val in row.items():
                if col not in rich.columns:
                    rich[col] = ""
                existing = rich.loc[real_idx, col]
                if isinstance(existing, pd.Series):
                    existing = existing.iloc[0]
                if pd.isna(existing) or str(existing).strip() in ("", "nan"):
                    rich.loc[real_idx, col] = str(val)
    else:
        # New location: add row with provided values
        if isinstance(row, dict):
            for col in row:
                if col not in rich.columns:
                    rich[col] = ""
            rich.loc[location] = {col: str(val) for col, val in row.items()}
        else:
            rich.loc[location] = pd.Series(dtype=str)
        existing_keys[key] = location

rich.to_excel("locations.xlsx")

# Enrich with bag-of-words and super-region columns
enrich_locations_xlsx("locations.xlsx")

In [9]:
taxonomy = load_taxonomy("../data/maxqda/MAXQDA_Code_System.mmd")
events = sorted(set(taxonomy.concept_to_category.keys()), key=lambda x: -len(x))
len(events), events[:15] + ["..."] + events[-15:]
# ",".join(events)

(184,
 ['Versteck bei Familie / Privatperson',
  'IPD (Jüd. Pfadfinder Deutschland)',
  'Kloster / kirchliche Einrichtung',
  'Hilfsverein der deutschen Juden',
  'OZ-b Migrationsinfrastruktur',
  'Reflexion in Erzählgegenwart',
  'Soldat der Jüdischen Brigade',
  'Soldat der britischen Armee',
  'OZ-c Verstecke & Schutzorte',
  'Realschule / Realgymnasium',
  'Einwanderung (Endstation)',
  'Referendariat / Praktikum',
  'Konsulat (drittstaatlich)',
  'Gedenktafel / Gedenkstein',
  'Jüdisch-deutsche Bräuche',
  '...',
  'Onkel',
  'Tante',
  'Iwrit',
  'Ahawa',
  'Brief',
  'Bruch',
  'Rhein',
  'Vater',
  'Musik',
  'Beruf',
  'Name',
  'Zug',
  'KPD',
  'SPD',
  'Tod'])

# Timespan

In [10]:
df[["time_start", "time_end"]] = (
    df["date_label"].apply(lambda ts: list(parse_timespan(ts).as_tuple())).tolist()
)
df

,event_id,event_label,event_type,place_name,place_detail,place_lat,place_lon,place_category,wikidata_qid,geonames_id,...,source_timecode,source_quote,external_links,notes,relation_to_main_person,name,start_location,end_location,time_start,time_end
0,,Alte Heimat Geburt,birth,Gießen,Marktplatz 11,,,alte_heimat,Q564579,2920512.0,...,,,https://www.geonames.org/2920512/giessen.html\...,,,Josef Stern,Gießen,Gießen,1921-06-15,1921-06-15
1,,Alte Heimat Grundschule,education,Gießen,,,,alte_heimat,,,...,,,,,,Josef Stern,Gießen,Gießen,1928-01-01,1932-12-31
2,,Alte Heimat Realgymnasium,education,Gießen,,,,alte_heimat,,,...,,,,,,Josef Stern,Gießen,Gießen,1932-01-01,1932-12-31
3,,Wohnort,residence,Gießen,Löberstraße 20,,,alte_heimat,,,...,,,https://www.giessen.de/index.php?ModID=7&FID=2...,Aufräumung v4: place_name korrigiert von 'Löbe...,,Josef Stern,Gießen,Gießen,1933-01-01,1933-12-31
4,,Zwangsausweisung Marktplatz 11,forced_eviction,Gießen,Marktplatz 11,,,ort_der_zeit,Q564579,2920512.0,...,11min 47s,Wir sind allerdings aus diesem schönen Haus gl...,,Josef war 12 Jahre alt. Erstes durch ihn erinn...,,Josef Stern,Gießen,Gießen,1933-01-01,1933-12-31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13,ev_sister2_015,Erinnerung: Gedenkblatt Yad Vashem (Josef Stern),memorial_yad_vashem,Yad Vashem,"Halle der Namen, Jerusalem",,,erinnerungsort,Q156591,,...,,"Haifa, 16.9.1980 — am Jahrestag der Verschleppung",,"Eingereicht von Josef (Helmut) Stern (Bruder),...",sister,Esther Stern,Yad Vashem,Yad Vashem,1980-09-16,1980-09-16
14,ev_sister2_016,Erinnerung: Eintrag im Bundesarchiv-Gedenkbuch,memorial_gedenkbuch_bundesarchiv,Koblenz,Bundesarchiv,,,erinnerungsort,Q3920,,...,,,https://apps.bundesarchiv.de/gedenkbuch/de976422,Bundesstaatliche Erinnerungsschicht (BRD),sister,Esther Stern,Yad Vashem,Koblenz,None,None
15,ev_sister2_014,Erinnerung: Gedenkblatt Yad Vashem (Ora Hadari),memorial_yad_vashem,Yad Vashem,"Halle der Namen, Jerusalem",,,erinnerungsort,Q156591,,...,,,https://collections.yadvashem.org/en/names/132...,"Eingereicht von Ora Hadari (Nichte, Tochter Jo...",sister,Esther Stern,Koblenz,Yad Vashem,1995-06-15,1995-06-15
16,ev_sister2_007,Erinnerung Stolperstein,memorial_stolperstein,Gießen Marktplatz 15,Marktplatz 15 (ehem. Marktplatz 11; selbe Haus...,,,erinnerungsort,Q564579,2920512.0,...,,,https://commons.wikimedia.org/wiki/File:Stolpe...,Sammelstolperstein mit Julius Stern (ev_father...,sister,Esther Stern,Yad Vashem,Gießen Marktplatz 15,2008-04-26,2008-04-26
17,ev_sister2_008,Erinnerung Platz,memorial_street_name,Esther-Stern-Platz Gießen,,,,erinnerungsort,,,...,,,https://www.lotta-magazin.de/ausgabe/1/den-erm...,,sister,Esther Stern,Gießen Marktplatz 15,Esther-Stern-Platz Gießen,None,None

# Notes

left unprocessed for now

In [11]:
set(df["notes"])

{'',
 '(Fragebogen)',
 '(Fragebogen):',
 '(Fragebogen): — [Hinweis: Quellfehler korrigiert — Q564579 (Gießen) durch Breidenbach ersetzt.]',
 '(Gedenkblatt)',
 '(Interview Metz)',
 "(Interview Metz)\ndate_start ergänzt: Steinstraße 19 Gießen war auch Julius' Kindheitsadresse 1900 (ev_father_002); Ende 1934 vor Umzug nach Berlin 1935",
 '22min 0s',
 '31min 58s — [Hinweis: Zerstört im Novemberpogrom 1938; heute Gedenkstätte Neuer Börneplatz.]',
 '39min 44s',
 "Aufräumung v4: place_name korrigiert von 'Löberstraße 20 11' zu 'Löberstraße 20'.",
 'Berliner Stolperstein-Inschrift mit tagesgenauen Datierungen (Berliner Konvention, abweichend vom Gießener Schema, das nur Jahreszahlen führt)',
 'Bundesstaatliche Erinnerungsschicht (BRD)',
 'Bundesstaatliche Erinnerungsschicht (BRD); zur Unterscheidung von familialer Yad-Vashem-Schicht und kommunaler Stolperstein-Schicht',
 'Chronotopos im engeren Sinn: Ort (Walltorstraße 48), Zeit (zwei-Tage-Ultimatum), Medium (Telephon) und ausgehender Knotenpunkt (Frankfurt Hauptbahnhof) in einem Moment verdichtet. Markiert den Beginn der Aliyah-Bewegung Josefs.',
 'Datum nicht im Datensatz belegt; eingegrenzt durch Geburt Josef (15.6.1921) und Übersiedlung Johannas aus Lollar 1908',
 'Datum unbestimmt; analog Claire ev_stepm_005 und Esther ev_sister2_006 modelliert\ndate_start präzisiert auf 1942-10-02 (Tag der Ankunft in Treblinka); date_label bleibt "1942" da Tag des Mordes nicht belegt',
 'Eingereicht von Alex Salm, von Yad Vashem als "researcher" kategorisiert; Salm hat mehrere Gedenkblätter unabhängig eingereicht; weitere biographische Identifikation derzeit nicht möglich (Stand 14.5.2026). Repräsentiert die externe Forschungs-Schicht der Kommemoration neben familialer (Yad-Vashem-Gedenkblätter) und kommunaler (Stolperstein) Ebene.',
 "Eingereicht von Josef (Helmut) Stern (Bruder), wohnhaft Einstein Str. 82, Haifa 34601. Bewusste Wahl der deutschen Formularversion; Doppelsignatur 'Josef (Helmut)' verbindet israelischen Namen und deutschen Kindheitsnamen; Einreichungsdatum am Jahrestag der Verschleppung Esthers (16.9.1942) — drei aufeinandergelegte Identitätsschichten (deutsche Kindheit, Trauma 1942, israelisches Überleben 1980) in einem A4-Bogen.",
 'Eingereicht von Josef Stern (Sohn); früheste der zwei dokumentierten Yad-Vashem-Einreichungen für Julius. Tageseinreichungsdatum bislang nicht aus der Online-Datenbank rekonstruierbar.',
 "Eingereicht von Ora Hadari (Enkelin, Tochter Josef Sterns); Teil der Sammeleinreichung am Geburtstag ihres Vaters Josef (15.6.1995). Parallele Einreichungen für Claire, Esther, Auguste. Bemerkenswert, weil bereits 1978 von Josef eingereicht — Ora's Einreichung ist also nicht Lückenschluss, sondern eigener generationaler Erinnerungsakt.",
 'Eingereicht von Ora Hadari (Nichte, Tochter Josef Sterns); Teil der Sammeleinreichung am Geburtstag ihres Vaters Josef (15.6.1995). Parallele Einreichungen für Julius, Claire, Auguste am selben Tag.',
 'Eingereicht von Ora Hadari (Stief-Enkelin, Tochter Josef Sterns); Teil ihrer Sammeleinreichung am Geburtstag ihres Vaters Josef (15.6.1995) — siehe parallele Einreichungen für Julius (ev_father_???_YV_ora), Esther (ev_sister2_???_YV_ora), Auguste (ev_pgm_???_YV_ora)',
 'Eingereicht von Ora Hadari (Urenkelin, Tochter Josef Sterns); Teil der Sammeleinreichung am Geburtstag ihres Vaters Josef (15.6.1995). Parallele Einreichungen für Julius, Claire, Esther am selben Tag.',
 'Eingereicht von Sonja Stern Poper (Schwester); hebräisches Formular; Einreichungsort vermutlich Haifa. Datierung 1965 stimmt mit hebräischem Jahr-Stempel תשכ"ה überein. Älteste der drei für Esther dokumentierten Yad-Vashem-Einreichungen.',
 'Eisernes Kreuz',
 'Endpunkt durch Auswanderung nach Palästina 1938 (ev_sister1_002)',
 'Fabrik in der Nähe von Haifa',
 'Geburtshaus ',
 'Heirat ergab Stiefmutter-Konstellation zu Josef (geb. 1921) und Sonja (geb. 1922); biologische Tochter Esther 1926',
 'Heiratsdatum nicht direkt belegt; eingegrenzt durch Geburt Josefs (15.6.1921). Vgl. Julius ev_father_014.',
 'Heutige Europabrücke ab 1960; 1936 nutzte Stern die alte Straßenbrücke von 1897 (1939 zerstört).',
 'Interview Metz',
 'Jesreelebene',
 'Josef war 12 Jahre alt. Erstes durch ihn erinnertes NS-Verfügungsereignis; familienkollektiv.',
 'Kollektiv-Ereignis der Familie; Esther war 7 Jahre alt. Vgl. Julius ev_father_016',
 'Kollektiv-Ereignis der Familie; vgl. Julius ev_father_016',
 'Lebte am Marktplatz 11 mit ihren Eltern Kaminka; nach Heirat mit Julius Stern dort als Ehefrau und Mutter weiter wohnhaft (Mehrgenerationen-Haushalt).',
 'Letzter Wohnort vor Deportation; Adresse wurde später zum Judenhaus erklärt (siehe Julius ev_father_017). Endet mit Deportation am 16.9.1942.',
 'Letzter Wohnort vor Deportation; Esther wohnte hier von 9. Lebensjahr bis zur Verschleppung mit 16',
 'Mehrgenerationen-Haushalt am Marktplatz 11: zusammen mit Tochter Johanna (verh. mit Julius Stern) und deren Kindern Josef und Sonja. Endpunkt durch Auswanderung in die USA am 5.10.1936.',
 'Mit den Eltern Kaminka von Lollar nach Gießen, Marktplatz 11 (vgl. ev_mgm_002, ev_mgf_003). Johanna war zur Umzugszeit 12 Jahre alt.',
 'Nach dem Tod der Mutter Johanna 1923 zu Isaak und Auguste Stern in die Steinstraße 19. Endpunkt durch Wiederheirat des Vaters Julius mit Claire am 24.12.1924 — Sonja kehrte danach an den Marktplatz 11 zurück. Während dieser Phase war ihr Bruder Josef hingegen am Marktplatz 11 in Obhut der maternalen Großeltern Kaminka geblieben (räumliche Trennung der Geschwister).',
 'Nicht im Bundesarchiv-Gedenkbuch verzeichnet (Stand 14.5.2026) und nicht im Berliner Gedenkbuch (Stand 14.5.2026). Beide staatlichen Erinnerungsregister legen Tod-durch-NS-Verfolgungsmaßnahme als Aufnahmekriterium an (Deportation, Mord, Suizid unter Verfolgung); Isaaks Tod 1939 in Berlin erfüllt dieses nicht. Die doppelte Auslassung markiert eine ausdrückliche staatliche Erinnerungs-Schwelle: er lebte unter Verfolgung, starb aber nicht innerhalb der dafür anerkennungspflichtigen Kategorien.',
 'Quellenkonflikt: kommunale Erinnerungsseite verwendet "Ghettohaus" für 1935, Sterns Erlebnisbericht differenziert zwischen Einzug 1935 und späterer Judenhaus-Verfügung. Verlässliche systemische Judenhaus-Designation in Deutschland erfolgte typischerweise nach dem Mietergesetz für Juden vom 30.4.1939.\ndate_start pragmatisch auf 30.4.1939 gesetzt (Inkrafttreten des Mietergesetzes für Juden, das Grundlage für Judenhaus-Designationen wurde); date_certainty bleibt uncertain',
 'Regional-staatliche Erinnerungsschicht (Land Berlin), spezifisch für Berliner Deportierte; gedrucktes Werk ohne digitale Volltext-Version, daher keine Stabil-URL möglich. Augustes berlinische Wohn- und Deportationszeit macht sie für diese regionale Schicht eintragefähig — im Unterschied zu den Gießener Familienmitgliedern.',
 'Rückkehr zur Familie nach Heirat Julius/Claire 24.12.1924; Endpunkt durch Zwangsausweisung 1933',
 'Sammelstolperstein mit Claire Stern (ev_stepm_006) und Esther Stern (ev_sister2_007); deportiert gemeinsam am 30.09.1942 ab Darmstadt',
 'Sammelstolperstein mit Julius Stern (ev_father_013) und Claire Stern (ev_stepm_006)',
 'Sammelstolperstein mit Julius Stern (ev_father_013) und Esther Stern (ev_sister2_007); GEB. THALHEIMER eigene Inschriftzeile',
 'Sonja war 11 Jahre alt; Kollektiv-Ereignis der Familie',
 'Sterbeort und Sterbedatum (Tag/Monat) nicht im Datensatz belegt; Standesamtsregister Gießen 1923 wäre die direkte Quelle. Strukturelle Konsequenz: Sonja zu paternalen Großeltern in die Steinstraße 19 (1923–1924), Josef in Obhut der maternalen Großeltern Kaminka am Marktplatz 11. Wiedervereinigung der Geschwister im Haushalt nach Wiederheirat Julius/Claire am 24.12.1924.',
 'Stolperstein Gießen\ndate_start präzisiert auf 1942-10-02 (Tag der Ankunft in Treblinka); date_label bleibt "1942"',
 'Tochter von Betty und David Kaminka; zur Geburtszeit lebten die Eltern noch in Lollar (Umzug nach Gießen erst 1908).',
 'Vorwand: Denkmalschutz. Nach Stern eine der ersten antijüdischen Verfügungen in Gießen.',
 'Wohnort durch Heirat begründet; Endpunkt durch Zwangsausweisung 1933 (Interview Metz 11min 47s)',
 'Wohnte am Marktplatz 11 mit Eltern Julius und Johanna sowie maternalen Großeltern Kaminka, bis zum Tod der Mutter 1923',
 'Wohnte von Geburt bis Zwangsausweisung 1933 am Marktplatz 11 (Familienhaushalt). Endpunkt durch Zwangsausweisung 1933 (Interview Metz 11min 47s).',
 'Zwischenstation nach Zwangsausweisung Marktplatz 11; vgl. Julius ev_father_005',
 'aus dem Kibbuz ausgewiesen',
 'date_start auf November 1938 gesetzt (date_label: "November 1938", Kontext Novemberpogrom)',
 'date_start ergänzt für korrekte chronologische Sortierung (Schule ab 12.04.1932 bis vermutlich Schulwechsel 1933)',
 'date_start ergänzt: nach Zwangsausweisung Marktplatz 11 (1933) bis Umzug Walltorstraße 48 (1935, vgl. giessen.de)',
 'date_start gesetzt auf 1920 (date_label sagt "1920 bis 1933"); end-Datum durch belegte Zwangsausweisung 1933',
 'zur Tochter Martha – Ihre 4-Zimmer-Wohnung befand sich dort im Vorderhaus im dritten Stock — Wohnten zur Tochter Martha Katz geb. Stern (1891–1943, deportiert 1943 nach Auschwitz). — [Hinweis: 4-Zimmer-Wohnung der Tochter Martha Katz im 3. Stock Vorderhaus.]'}

# Links

left unprocessed for now

In [12]:
urls = set()
for cell in df["external_links"]:
    if pd.notna(cell):
        for url in str(cell).split("\n"):
            url = url.strip()
            if url:
                urls.add(url)
urls

{'https://apps.bundesarchiv.de/gedenkbuch/de1167397',
 'https://apps.bundesarchiv.de/gedenkbuch/de976422',
 'https://apps.bundesarchiv.de/gedenkbuch/de976856',
 'https://apps.bundesarchiv.de/gedenkbuch/de976944',
 'https://atom.lib.uct.ac.za/uploads/r/university-of-cape-town-libraries-special-collections/a/3/c/a3cc8572f727d61327e4f929a86fc91c339c13cc41721aa18c8f158e13678891/mss_sahgf_schragenheim_publications_025_1-20.pdf',
 'https://collections.yadvashem.org/en/names/1189610',
 'https://collections.yadvashem.org/en/names/13219727',
 'https://collections.yadvashem.org/en/names/13547976',
 'https://collections.yadvashem.org/en/names/13571207',
 'https://collections.yadvashem.org/en/names/13834992',
 'https://collections.yadvashem.org/en/names/522846',
 'https://commons.wikimedia.org/wiki/File:Stolperstein_Gießen_Marktplatz_15_Claire_Stern.JPG',
 'https://commons.wikimedia.org/wiki/File:Stolperstein_Gießen_Marktplatz_15_Esther_Stern.JPG',
 'https://commons.wikimedia.org/wiki/File:Stolperstein_Gießen_Marktplatz_15_Julius_Stern.JPG',
 'https://de.wikipedia.org/wiki/Datei:Stolperstein_Gießen_Nordanlage_Esther_Stern.JPG',
 'https://www.geonames.org/11974166/grossen-linden.html',
 'https://www.geonames.org/12217751/theresienstadt-concentration-camp-and-ghetto.html',
 'https://www.geonames.org/2806852/woelfersheim.html',
 'https://www.geonames.org/2825297/stuttgart.html',
 'https://www.geonames.org/2833011/sennfeld.html',
 'https://www.geonames.org/2888549/klein-linden.html',
 'https://www.geonames.org/2891951/kehl.html',
 'https://www.geonames.org/2920512/giessen.html',
 'https://www.geonames.org/293165/jezreel-valley.html',
 'https://www.geonames.org/293304/tirat-tsvi.html',
 'https://www.geonames.org/2938913/darmstadt.html',
 'https://www.geonames.org/2944820/breidenbach.html',
 'https://www.geonames.org/294801/haifa.html',
 'https://www.geonames.org/2950159/berlin.html',
 'https://www.geonames.org/295211/-en-hanaziv.html',
 'https://www.geonames.org/2953189/baiertal.html',
 'https://www.geonames.org/2995469/marseille.html',
 'https://www.geonames.org/6252001/united-states.html',
 'https://www.geonames.org/6290300/frankfurt-hauptbahnhof.html',
 'https://www.geonames.org/6553153/frankfurt-am-main.html',
 'https://www.geonames.org/6557780/lollar.html',
 'https://www.geonames.org/712441/berdychiv.html',
 'https://www.geonames.org/756807/treblinka-extermination-camp.html',
 'https://www.geonames.org/756807/treblinka.html',
 'https://www.geonames.org/8644023/konzentrationslager-buchenwald.html',
 'https://www.giessen.de/Erleben/Über-Gießen/Stolpersteine/Marktplatz-15',
 'https://www.giessen.de/index.php?ModID=7&FID=2874.2939.1',
 'https://www.giessen.de/index.php?ModID=7&FID=2874.2939.1&object=tx%7C2874.2939.1',
 'https://www.giessen.de/index.php?ModID=7&FID=2874.2967.1&object=tx%2C2874.2967.1',
 'https://www.lotta-magazin.de/ausgabe/1/den-ermordeten-menschen-ein-gesicht-geben/',
 'https://www.stolpersteine-berlin.de/de/wullenweberstr/11/auguste-stern',
 'https://www.wikidata.org/wiki/Q1022',
 'https://www.wikidata.org/wiki/Q111620976',
 'https://www.wikidata.org/wiki/Q116016915',
 'https://www.wikidata.org/wiki/Q1375288',
 'https://www.wikidata.org/wiki/Q14531586',
 'https://www.wikidata.org/wiki/Q152010',
 'https://www.wikidata.org/wiki/Q152802',
 'https://www.wikidata.org/wiki/Q1571834',
 'https://www.wikidata.org/wiki/Q15837262',
 'https://www.wikidata.org/wiki/Q158799',
 'https://www.wikidata.org/wiki/Q15979',
 'https://www.wikidata.org/wiki/Q160175',
 'https://www.wikidata.org/wiki/Q165368',
 'https://www.wikidata.org/wiki/Q1794',
 'https://www.wikidata.org/wiki/Q2095906',
 'https://www.wikidata.org/wiki/Q23482',
 'https://www.wikidata.org/wiki/Q2973',
 'https://www.wikidata.org/wiki/Q30',
 'https://www.wikidata.org/wiki/Q41621',
 'https://www.wikidata.org/wiki/Q550025',
 'https://www.wikidata.org/wiki/Q56161165',
 'https://www.wikidata.org/wiki/Q564579',
 'https://www.wikidata.org/wiki/Q625061',
 'https://www.wikidata.org/wiki/Q634098',
 'https://www.wikidata.org/wiki/Q64',
 'https://www.wikidata.org/wiki/Q763829',
 'https://www.wikidata.org/wiki/Q7904',
 'https://www.wikidata.org/wiki/Q803735'}

# Events

In [13]:
df["event"] = df["event_label"].apply(lambda x: extract_events(x, events))
df

,event_id,event_label,event_type,place_name,place_detail,place_lat,place_lon,place_category,wikidata_qid,geonames_id,...,source_quote,external_links,notes,relation_to_main_person,name,start_location,end_location,time_start,time_end,event
0,,Alte Heimat Geburt,birth,Gießen,Marktplatz 11,,,alte_heimat,Q564579,2920512.0,...,,https://www.geonames.org/2920512/giessen.html\...,,,Josef Stern,Gießen,Gießen,1921-06-15,1921-06-15,"[Geburt, Alte Heimat]"
1,,Alte Heimat Grundschule,education,Gießen,,,,alte_heimat,,,...,,,,,Josef Stern,Gießen,Gießen,1928-01-01,1932-12-31,"[Schule, Alte Heimat Grund]"
2,,Alte Heimat Realgymnasium,education,Gießen,,,,alte_heimat,,,...,,,,,Josef Stern,Gießen,Gießen,1932-01-01,1932-12-31,[Alte Heimat Realgymnasium]
3,,Wohnort,residence,Gießen,Löberstraße 20,,,alte_heimat,,,...,,https://www.giessen.de/index.php?ModID=7&FID=2...,Aufräumung v4: place_name korrigiert von 'Löbe...,,Josef Stern,Gießen,Gießen,1933-01-01,1933-12-31,[Wohnort]
4,,Zwangsausweisung Marktplatz 11,forced_eviction,Gießen,Marktplatz 11,,,ort_der_zeit,Q564579,2920512.0,...,Wir sind allerdings aus diesem schönen Haus gl...,,Josef war 12 Jahre alt. Erstes durch ihn erinn...,,Josef Stern,Gießen,Gießen,1933-01-01,1933-12-31,[Zwangsausweisung Marktplatz 11]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13,ev_sister2_015,Erinnerung: Gedenkblatt Yad Vashem (Josef Stern),memorial_yad_vashem,Yad Vashem,"Halle der Namen, Jerusalem",,,erinnerungsort,Q156591,,...,"Haifa, 16.9.1980 — am Jahrestag der Verschleppung",,"Eingereicht von Josef (Helmut) Stern (Bruder),...",sister,Esther Stern,Yad Vashem,Yad Vashem,1980-09-16,1980-09-16,"[Yad Vashem, Erinnerung: Gedenkblatt (Josef S..."
14,ev_sister2_016,Erinnerung: Eintrag im Bundesarchiv-Gedenkbuch,memorial_gedenkbuch_bundesarchiv,Koblenz,Bundesarchiv,,,erinnerungsort,Q3920,,...,,https://apps.bundesarchiv.de/gedenkbuch/de976422,Bundesstaatliche Erinnerungsschicht (BRD),sister,Esther Stern,Yad Vashem,Koblenz,None,None,[Erinnerung: Eintrag im Bundesarchiv-Gedenkbuch]
15,ev_sister2_014,Erinnerung: Gedenkblatt Yad Vashem (Ora Hadari),memorial_yad_vashem,Yad Vashem,"Halle der Namen, Jerusalem",,,erinnerungsort,Q156591,,...,,https://collections.yadvashem.org/en/names/132...,"Eingereicht von Ora Hadari (Nichte, Tochter Jo...",sister,Esther Stern,Koblenz,Yad Vashem,1995-06-15,1995-06-15,"[Yad Vashem, Erinnerung: Gedenkblatt (Ora Had..."
16,ev_sister2_007,Erinnerung Stolperstein,memorial_stolperstein,Gießen Marktplatz 15,Marktplatz 15 (ehem. Marktplatz 11; selbe Haus...,,,erinnerungsort,Q564579,2920512.0,...,,https://commons.wikimedia.org/wiki/File:Stolpe...,Sammelstolperstein mit Julius Stern (ev_father...,sister,Esther Stern,Yad Vashem,Gießen Marktplatz 15,2008-04-26,2008-04-26,"[Stolperstein, Erinnerung]"
17,ev_sister2_008,Erinnerung Platz,memorial_street_name,Esther-Stern-Platz Gießen,,,,erinnerungsort,,,...,,https://www.lotta-magazin.de/ausgabe/1/den-erm...,,sister,Esther Stern,Gießen Marktplatz 15,Esther-Stern-Platz Gießen,None,None,[Erinnerung Platz]

In [14]:
from api_client import login, get_or_create_concept
from locations import load_locations_db

login()
load_locations_db()

print("Creating concepts...")
for label in sorted(concept_labels):
    get_or_create_concept(label)
print(f"  {len(concept_labels)} concept labels processed")

Authenticated
  Loaded 264 locations from locations.xlsx
Creating concepts...
  34 concept labels processed

Persist chronotopoi events from DataFrame to the API with locations, dates, and categories.

In [ ]:
from locations import load_locations_db
from events import create_event_from_row

# Load locations database for coordinate lookup
locations_db = load_locations_db()

# Create events from all dataframe rows, tracking which person each comes from
print("Creating events from chronotopi data...")
created_events = []

# Iterate through overview to track sheet names (person identifiers)
for k, v in overview.items():
    protagonist = df["name"]
    for protagonist in v:  # protagonist is the sheet name (person identifier)
        # Get rows for this person
        person_df = df[df["name"] == protagonist]


        for idx, row in person_df.iterrows():
            start_location = row.get("start_location", "").strip()
            event_id = create_event_from_row(row, protagonist, locations_db, start_location)
            if event_id:
                created_events.append(event_id)
                print(f"  ✅ {row['event_label']} → Event #{event_id}")
            else:
                print(f"  ⚠️ Skipped: {row['event_label']}")

print(f"\n✅ Created {len(created_events)} events")

  Loaded 264 locations from locations.xlsx
Creating events from chronotopi data...
Creating event: Alte Heimat Geburt
End place: Gießen
End location: [3] Gießen (Marktplatz 11)
Start location: [1] Gießen
Dates: 1921-06-15-None
Categories: ['birth', 'alte_heimat']
Links: ({'www.geonames.org': 'https://www.geonames.org/2920512/giessen.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q564579', 'www.giessen.de': 'https://www.giessen.de/index.php?ModID=7&FID=2874.2939.1&object=tx%7C2874.2939.1'}, '')
Payload: {'archive_id': 'Josef Stern_Alte_Heimat_Geburt', 'description': 'Alte Heimat Geburt', 'start_date': '1921-06-15'}
  ✅ Alte Heimat Geburt → Event #1962
Creating event: Alte Heimat Grundschule
End place: Gießen
End location: [1] Gießen
Start location: [None] Gießen
Dates: 1928-01-01-None
Categories: ['education', 'alte_heimat']
Links: []
Payload: {'archive_id': 'Josef Stern_Alte_Heimat_Grundsch', 'description': 'Alte Heimat Grundschule', 'start_date': '1928-01-01'}
  ✅ Alte Heimat Grundschule → Event #1963
Creating event: Alte Heimat Realgymnasium
End place: Gießen
End location: [1] Gießen
Start location: [None] Gießen
Dates: 1932-01-01-None
Categories: ['education', 'alte_heimat']
Links: []
Payload: {'archive_id': 'Josef Stern_Alte_Heimat_Realgymn', 'description': 'Alte Heimat Realgymnasium', 'start_date': '1932-01-01'}
  ✅ Alte Heimat Realgymnasium → Event #1964
Creating event: Wohnort
End place: Gießen
End location: [4] Gießen (Löberstraße 20)
Start location: [1] Gießen
Dates: 1933-01-01-None
Categories: ['residence', 'alte_heimat']
Links: ({'www.giessen.de': 'https://www.giessen.de/index.php?ModID=7&FID=2874.2939.1&object=tx%7C2874.2939.1'}, '')
Payload: {'archive_id': 'Josef Stern_Wohnort', 'description': 'Wohnort', 'start_date': '1933-01-01'}
  ✅ Wohnort → Event #1965
Creating event: Zwangsausweisung Marktplatz 11
End place: Gießen
End location: [3] Gießen (Marktplatz 11)
Start location: [1] Gießen
Dates: 1933-01-01-None
Categories: ['forced_eviction', 'ort_der_zeit']
Links: []
Payload: {'archive_id': 'Josef Stern_Zwangsausweisung_Mar', 'description': 'Zwangsausweisung Marktplatz 11', 'start_date': '1933-01-01'}
  ✅ Zwangsausweisung Marktplatz 11 → Event #1966
Creating event: Abgang von der Schule
End place: Gießen
End location: [1] Gießen
Start location: [None] Gießen
Dates: 1935-01-01-None
Categories: ['education', 'alte_heimat']
Links: []
Payload: {'archive_id': 'Josef Stern_Abgang_von_der_Schul', 'description': 'Abgang von der Schule', 'start_date': '1935-01-01'}
  ✅ Abgang von der Schule → Event #1967
Creating event: Wohnort
End place:
Failed to create event due to missing location: event_id
event_label                                                          Wohnort
event_type                                                         residence
place_name
place_detail                                    Ghettohaus, Walltorstraße 48
place_lat
place_lon
place_category                                                   alte_heimat
wikidata_qid
geonames_id
date_start                                                              1935
date_end
date_precision
date_certainty                                                      probable
date_label                                                           ab 1935
journey_id
sequence_nr
transport_mode
memorial_for_event_id
memorial_inscription
source_doc
source_timecode
source_quote
external_links             https://www.giessen.de/index.php?ModID=7&FID=2...
notes
relation_to_main_person
name                                                             Josef Stern
start_location                                                        Gießen
end_location
time_start                                                        1935-01-01
time_end                                                          1935-12-31
event                                                              [Wohnort]
Name: 6, dtype: object
  ⚠️ Skipped: Wohnort
Creating event: Hachschara
End place: Schlesien
End location: [5] Schlesien
Start location: [1] Gießen
Dates: 1935-01-01-None
Categories: ['education', 'alte_heimat']
Links: []
Payload: {'archive_id': 'Josef Stern_Hachschara', 'description': 'Hachschara', 'start_date': '1935-01-01'}
  ✅ Hachschara → Event #1968
Creating event: Bei Verwandten
End place: Berlin
End location: [6] Berlin
Start location: [5] Schlesien
Dates: 1935-01-01-None
Categories: ['residence', 'alte_heimat']
Links: ({'www.wikidata.org': 'https://www.wikidata.org/wiki/Q64', 'www.geonames.org': 'https://www.geonames.org/2950159/berlin.html'}, '')
Payload: {'archive_id': 'Josef Stern_Bei_Verwandten', 'description': 'Bei Verwandten', 'start_date': '1935-01-01'}
  ✅ Bei Verwandten → Event #1969
Creating event: Jeschiwa
End place: Frankfurt/M
End location: [7] Frankfurt/M (Synagoge am Börneplatz)
Start location: [6] Berlin
Dates: 1936-01-01-None
Categories: ['education', 'alte_heimat']
Links: ({'www.wikidata.org': 'https://www.wikidata.org/wiki/Q1794', 'www.geonames.org': 'https://www.geonames.org/6553153/frankfurt-am-main.html'}, '')
Payload: {'archive_id': 'Josef Stern_Jeschiwa', 'description': 'Jeschiwa', 'start_date': '1936-01-01'}
  ✅ Jeschiwa → Event #1970
Creating event: Aliyah-Anruf
End place: Gießen
End location: [26] Gießen (Walltorstraße 48)
Start location: [9] Frankfurt/M
Dates: 1936-01-01-None
Categories: ['notification', 'Telephon im Ghettohaus', 'alte_heimat']
Links: []
Payload: {'archive_id': 'Josef Stern_Aliyah-Anruf', 'description': 'Aliyah-Anruf', 'start_date': '1936-01-01'}
  ✅ Aliyah-Anruf → Event #1971
Creating event: Abfahrt > Abschied von den Eltern
End place: Frankfurt am Main
End location: [8] Frankfurt am Main (Hauptbahnhof)
Start location: [1] Gießen
Dates: 1936-01-01-None
Categories: ['farewell', 'alte_heimat']
Links: ({'www.wikidata.org': 'https://www.wikidata.org/wiki/Q1794', 'www.geonames.org': 'https://www.geonames.org/6290300/frankfurt-hauptbahnhof.html'}, '')
Payload: {'archive_id': 'Josef Stern_Abfahrt_>_Abschied_v', 'description': 'Abfahrt > Abschied von den Eltern', 'start_date': '1936-01-01'}
  ✅ Abfahrt > Abschied von den Eltern → Event #1972
Creating event: Auswanderung
End place: Frankfurt am Main
End location: [8] Frankfurt am Main (Hauptbahnhof)
Start location: [10] Frankfurt am Main
Dates: 1936-01-01-None
Categories: ['emigration_transit', 'Zug', 'verkehrsmittel']
Links: ({'www.wikidata.org': 'https://www.wikidata.org/wiki/Q165368', 'www.geonames.org': 'https://www.geonames.org/6290300/frankfurt-hauptbahnhof.html'}, '')
Payload: {'archive_id': 'Josef Stern_Auswanderung', 'description': 'Auswanderung', 'start_date': '1936-01-01'}
  ✅ Auswanderung → Event #1973
Creating event: Auswanderung
End place: Kehl am Rhein
End location: [11] Kehl am Rhein
Start location: [10] Frankfurt am Main
Dates: 1936-01-01-None
Categories: ['emigration_transit', 'Zug', 'verkehrsmittel']
Links: ({'www.wikidata.org': 'https://www.wikidata.org/wiki/Q15979', 'www.geonames.org': 'https://www.geonames.org/2891951/kehl.html'}, '')
Payload: {'archive_id': 'Josef Stern_Auswanderung', 'description': 'Auswanderung', 'start_date': '1936-01-01'}
  ✅ Auswanderung → Event #1974
Creating event: Auswanderung
End place: Brücke Kehl–Straßburg (Rheinquerung)
End location: [12] Brücke Kehl–Straßburg (Rheinquerung)
Start location: [11] Kehl am Rhein
Dates: 1936-01-01-None
Categories: ['emigration_transit', 'Zug', 'verkehrsmittel']
Links: ({'www.wikidata.org': 'https://www.wikidata.org/wiki/Q1375288'}, '')
Payload: {'archive_id': 'Josef Stern_Auswanderung', 'description': 'Auswanderung', 'start_date': '1936-01-01'}
  ✅ Auswanderung → Event #1975
Creating event: Auswanderung
End place: Marseille
End location: [13] Marseille
Start location: [12] Brücke Kehl–Straßburg (Rheinquerung)
Dates: 1936-01-01-None
Categories: ['emigration_transit', 'Zug', 'verkehrsmittel']
Links: ({'www.wikidata.org': 'https://www.wikidata.org/wiki/Q23482', 'www.geonames.org': 'https://www.geonames.org/2995469/marseille.html'}, '')
Payload: {'archive_id': 'Josef Stern_Auswanderung', 'description': 'Auswanderung', 'start_date': '1936-01-01'}
  ✅ Auswanderung → Event #1976
Creating event: Auswanderung
End place: Marseille
End location: [13] Marseille
Start location: [None] Marseille
Dates: 1936-01-01-None
Categories: ['emigration', 'Schiff', 'verkehrsmittel']
Links: []
Payload: {'archive_id': 'Josef Stern_Auswanderung', 'description': 'Auswanderung', 'start_date': '1936-01-01'}
  ✅ Auswanderung → Event #1977
Creating event: Neue Heimat
Einwanderung
End place: Kibbuz Rodges, besteht nicht mehr (in der Nähe von Petah Tikva)
End location: [14] Kibbuz Rodges, besteht nicht mehr (in der Nähe von Petah Tikva)
Start location: [13] Marseille
Dates: 1936-01-01-None
Categories: ['immigration', 'neue_heimat']
Links: []
Payload: {'archive_id': 'Josef Stern_Neue_Heimat\nEinwande', 'description': 'Neue Heimat\nEinwanderung', 'start_date': '1936-01-01'}
  ✅ Neue Heimat
Einwanderung → Event #1978
Creating event: Neue Heimat

Reise durchs Land
End place: Ēmeq Yizrəʿēl
End location: [15] Ēmeq Yizrəʿēl
Start location: [14] Kibbuz Rodges, besteht nicht mehr (in der Nähe von Petah Tikva)
Dates: 1937-01-01-None
Categories: ['residence', 'neue_heimat']
Links: ({'www.wikidata.org': 'https://www.wikidata.org/wiki/Q763829', 'www.geonames.org': 'https://www.geonames.org/293165/jezreel-valley.html'}, '')
Payload: {'archive_id': 'Josef Stern_Neue_Heimat\n\nReise_d', 'description': 'Neue Heimat\n\nReise durchs Land', 'start_date': '1937-01-01'}
  ✅ Neue Heimat

Reise durchs Land → Event #1979
Creating event: Neue Heimat
End place: Kibbuz Ein HaNetziv
End location: [16] Kibbuz Ein HaNetziv
Start location: [15] Ēmeq Yizrəʿēl
Dates: 1938-01-01-None
Categories: ['residence', 'neue_heimat']
Links: ({'www.wikidata.org': 'https://www.wikidata.org/wiki/Q2095906', 'www.geonames.org': 'https://www.geonames.org/295211/-en-hanaziv.html'}, '')
Payload: {'archive_id': 'Josef Stern_Neue_Heimat', 'description': 'Neue Heimat', 'start_date': '1938-01-01'}
  ✅ Neue Heimat → Event #1980
Creating event: Neue Heimat
End place: Haifa
End location: [17] Haifa
Start location: [16] Kibbuz Ein HaNetziv
Dates: 1940-01-01-None
Categories: ['residence', 'neue_heimat']
Links: ({'www.geonames.org': 'https://www.geonames.org/294801/haifa.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q41621'}, '')
Payload: {'archive_id': 'Josef Stern_Neue_Heimat', 'description': 'Neue Heimat', 'start_date': '1940-01-01'}
  ✅ Neue Heimat → Event #1981
Creating event: Neue Heimat
End place: Kibbuz Tirat Tsvi
End location: [18] Kibbuz Tirat Tsvi
Start location: [17] Haifa
Dates: 1940-01-01-None
Categories: ['residence', 'neue_heimat']
Links: ({'www.wikidata.org': 'https://www.wikidata.org/wiki/Q550025', 'www.geonames.org': 'https://www.geonames.org/293304/tirat-tsvi.html'}, '')
Payload: {'archive_id': 'Josef Stern_Neue_Heimat', 'description': 'Neue Heimat', 'start_date': '1940-01-01'}
  ✅ Neue Heimat → Event #1982
Creating event: Reise zurück als Soldat
End place: Italien
End location: [19] Italien
Start location: [18] Kibbuz Tirat Tsvi
Dates: 1944-01-01-None
Categories: ['military_service', 'reise_zurueck']
Links: []
Payload: {'archive_id': 'Josef Stern_Reise_zurück_als_Sol', 'description': 'Reise zurück als Soldat', 'start_date': '1944-01-01'}
  ✅ Reise zurück als Soldat → Event #1983
Creating event: Reise zurück als Soldat
End place: Deutschland
End location: [20] Deutschland
Start location: [19] Italien
Dates: 1944-01-01-None
Categories: ['military_service', 'reise_zurueck']
Links: []
Payload: {'archive_id': 'Josef Stern_Reise_zurück_als_Sol', 'description': 'Reise zurück als Soldat', 'start_date': '1944-01-01'}
  ✅ Reise zurück als Soldat → Event #1984
Creating event: Reise zurück als Soldat
End place: Belgien
End location: [21] Belgien
Start location: [20] Deutschland
Dates: 1944-01-01-None
Categories: ['military_service', 'reise_zurueck']
Links: []
Payload: {'archive_id': 'Josef Stern_Reise_zurück_als_Sol', 'description': 'Reise zurück als Soldat', 'start_date': '1944-01-01'}
  ✅ Reise zurück als Soldat → Event #1985
Creating event: Reise zurück als Soldat
End place: Niederlande
End location: [22] Niederlande
Start location: [21] Belgien
Dates: 1944-01-01-None
Categories: ['military_service', 'reise_zurueck']
Links: []
Payload: {'archive_id': 'Josef Stern_Reise_zurück_als_Sol', 'description': 'Reise zurück als Soldat', 'start_date': '1944-01-01'}
  ✅ Reise zurück als Soldat → Event #1986
Creating event: Neue Heimat
Heirat
End place: Haifa
End location: [17] Haifa
Start location: [22] Niederlande
Dates: None-None
Categories: ['marriage', 'neue_heimat']
Links: []
Payload: {'archive_id': 'Josef Stern_Neue_Heimat\nHeirat', 'description': 'Neue Heimat\nHeirat'}
  ✅ Neue Heimat
Heirat → Event #1987
Creating event: Neue Heimat
Haifa
Beruf
End place: Haifa
End location: [23] Haifa (Universität, Bibliothek)
Start location: [17] Haifa
Dates: 1966-01-01-None
Categories: ['work', 'neue_heimat']
Links: []
Payload: {'archive_id': 'Josef Stern_Neue_Heimat\nHaifa\nBe', 'description': 'Neue Heimat\nHaifa\nBeruf', 'start_date': '1966-01-01'}
  ✅ Neue Heimat
Haifa
Beruf → Event #1988
Creating event: Reise zurück
End place: Gießen
End location: [1] Gießen
Start location: [17] Haifa
Dates: 1975-01-01-None
Categories: ['return_visit_transit', 'reise_zurueck']
Links: ({'www.geonames.org': 'https://www.geonames.org/2920512/giessen.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q564579'}, '')
Payload: {'archive_id': 'Josef Stern_Reise_zurück', 'description': 'Reise zurück', 'start_date': '1975-01-01'}
  ✅ Reise zurück → Event #1989
Creating event: Fahrt Frankfurt-Gießen
End place: Frankfurt am Main
End location: [10] Frankfurt am Main
Start location: [1] Gießen
Dates: None-None
Categories: ['return_visit_transit', 'Zug', 'reise_zurueck']
Links: ({'www.wikidata.org': 'https://www.wikidata.org/wiki/Q1794', 'www.geonames.org': 'https://www.geonames.org/6553153/frankfurt-am-main.html'}, '')
Payload: {'archive_id': 'Josef Stern_Fahrt_Frankfurt-Gieß', 'description': 'Fahrt Frankfurt-Gießen'}
  ✅ Fahrt Frankfurt-Gießen → Event #1990
Creating event: Klein Linden
End place: Klein-Linden
End location: [24] Klein-Linden
Start location: [10] Frankfurt am Main
Dates: None-None
Categories: ['return_visit_transit', 'Zug', 'reise_zurueck']
Links: ({'www.wikidata.org': 'https://www.wikidata.org/wiki/Q1571834', 'www.geonames.org': 'https://www.geonames.org/2888549/klein-linden.html'}, '')
Payload: {'archive_id': 'Josef Stern_Klein_Linden', 'description': 'Klein Linden'}
  ✅ Klein Linden → Event #1991
Creating event: Großen-Linden
End place: Großen-Linden
End location: [25] Großen-Linden
Start location: [24] Klein-Linden
Dates: None-None
Categories: ['return_visit', 'Zug', 'reise_zurueck']
Links: ({'www.wikidata.org': 'https://www.wikidata.org/wiki/Q116016915', 'www.geonames.org': 'https://www.geonames.org/11974166/grossen-linden.html'}, '')
Payload: {'archive_id': 'Josef Stern_Großen-Linden', 'description': 'Großen-Linden'}
  ✅ Großen-Linden → Event #1992
Creating event: Geburtshaus Marktplatz 11
End place: Gießen
End location: [3] Gießen (Marktplatz 11)
Start location: [25] Großen-Linden
Dates: None-None
Categories: ['return_visit_transit', 'Zug', 'reise_zurueck']
Links: []
Payload: {'archive_id': 'Josef Stern_Geburtshaus_Marktpla', 'description': 'Geburtshaus Marktplatz 11'}
  ✅ Geburtshaus Marktplatz 11 → Event #1993
Creating event: Geburt
End place: Breidenbach
End location: [27] Breidenbach
Start location: [None] Breidenbach
Dates: 1857-11-05-1857-11-05
Categories: ['birth', 'alte_heimat']
Links: ({'www.geonames.org': 'https://www.geonames.org/2944820/breidenbach.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q564579'}, '')
Payload: {'archive_id': 'Isaak Stern_Geburt', 'description': 'Geburt', 'start_date': '1857-11-05', 'end_date': '1857-11-05'}
  ✅ Geburt → Event #1994
Creating event: Wohnort
End place: Steinstraße 19,
End location: [28] Steinstraße 19, (Gießen)
Start location: [27] Breidenbach
Dates: None-None
Categories: ['residence', 'alte_heimat']
Links: []
Payload: {'archive_id': 'Isaak Stern_Wohnort', 'description': 'Wohnort'}
  ✅ Wohnort → Event #1995
Creating event: Umzug nach Berlin
End place: Wullenweberstraße 11, Berlin-Moabit
End location: [29] Wullenweberstraße 11, Berlin-Moabit (Berlin (Moabit))
Start location: [30] Steinstraße 19,
Dates: 1935-01-01-None
Categories: ['residence_change', 'train']
Links: ({'www.geonames.org': 'https://www.geonames.org/2950159/berlin.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q56161165'}, '')
Payload: {'archive_id': 'Isaak Stern_Umzug_nach_Berlin', 'description': 'Umzug nach Berlin', 'start_date': '1935-01-01'}
  ✅ Umzug nach Berlin → Event #1996
Creating event: Tod
End place: Berlin
End location: [6] Berlin
Start location: [31] Wullenweberstraße 11, Berlin-Moabit
Dates: 1939-01-01-1939-12-31
Categories: ['death', 'alte_heimat']
Links: ({'www.geonames.org': 'https://www.geonames.org/2950159/berlin.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q64'}, '')
Payload: {'archive_id': 'Isaak Stern_Tod', 'description': 'Tod', 'start_date': '1939-01-01', 'end_date': '1939-12-31'}
  ✅ Tod → Event #1997
Creating event: Geburt
End place: Wölfersheim
End location: [32] Wölfersheim
Start location: [None] Wölfersheim
Dates: 1862-05-22-1862-05-22
Categories: ['birth', 'alte_heimat']
Links: ({'www.wikidata.org': 'https://www.wikidata.org/wiki/Q634098', 'www.geonames.org': 'https://www.geonames.org/2806852/woelfersheim.html'}, '')
Payload: {'archive_id': 'Auguste Stern_Geburt', 'description': 'Geburt', 'start_date': '1862-05-22', 'end_date': '1862-05-22'}
  ✅ Geburt → Event #1998
Creating event: Wohnort
End place: Steinstraße 19,
End location: [28] Steinstraße 19, (Gießen)
Start location: [32] Wölfersheim
Dates: 1900-01-01-1934-12-31
Categories: ['residence', 'alte_heimat']
Links: []
Payload: {'archive_id': 'Auguste Stern_Wohnort', 'description': 'Wohnort', 'start_date': '1900-01-01', 'end_date': '1934-12-31'}
  ✅ Wohnort → Event #1999
Creating event: Umzug nach Berlin
End place: Wullenweberstraße 11, Berlin-Moabit
End location: [29] Wullenweberstraße 11, Berlin-Moabit (Berlin (Moabit))
Start location: [30] Steinstraße 19,
Dates: 1935-01-01-None
Categories: ['residence_change', 'train']
Links: ({'www.geonames.org': 'https://www.geonames.org/2950159/berlin.html', 'www.wikidata.org': 'https://www.wikidata.org/wiki/Q56161165'}, '')
Payload: {'archive_id': 'Auguste Stern_Umzug_nach_Berlin', 'description': 'Umzug nach Berlin', 'start_date': '1935-01-01'}
  ✅ Umzug nach Berlin → Event #2000
Creating event: Deportation
End place: Theresienstadt
End location: [33] Theresienstadt (Von Berlin nach Theresienstadt)
Start location: [31] Wullenweberstraße 11, Berlin-Moabit
Dates: 1942-08-27-1942-08-27
Categories: ['deportation', 'train', 'ort_der_zeit']
Links: ({'www.wikidata.org': 'https://www.wikidata.org/wiki/Q160175', 'www.geonames.org': 'https://www.geonames.org/12217751/theresienstadt-concentration-camp-and-ghetto.html'}, '')
Payload: {'archive_id': 'Auguste Stern_Deportation', 'description': 'Deportation', 'start_date': '1942-08-27', 'end_date': '1942-08-27'}
  ✅ Deportation → Event #2001
Creating event: Tod/Ermordung
End place: Theresienstadt
  ⚠️ API Error 400: {"geonames_id":["Ensure this field has no more than 20 characters."]}
      → Skipping location 'Theresienstadt' due to API error
End location: [None] Theresienstadt
Start location: [None] Theresienstadt
Dates: 1942-09-26-1942-09-26
Categories: ['murder', 'ort_der_zeit']
Links: ({'www.wikidata.org': 'https://www.wikidata.org/wiki/Q160175', 'www.geonames.org': 'https://www.geonames.org/12217751/theresienstadt-concentration-camp-and-ghetto.html'}, '')
Payload: {'archive_id': 'Auguste Stern_Tod/Ermordung', 'description': 'Tod/Ermordung', 'start_date': '1942-09-26', 'end_date': '1942-09-26'}
  ✅ Tod/Ermordung → Event #2002
Creating event:

In [ ]:
# create_event_from_row already links timespan, lifecycle, persons, concepts,
# urls and start/end locations for each event, so no further linking is needed.

print("\n📍 Events created and ready for map visualization!")
print(f"   - {len(created_events)} chronotopi events")
print(f"   - {len(set(df['place_name'].dropna()))} locations")
print(f"   - {len(concept_labels)} event concepts")

Linking 119 events with concepts and locations...
✅ Linked 0 concept relationships

📍 Events created and ready for map visualization!
   - 119 chronotopi events
   - 45 locations
   - 34 event concepts