In [1]:
import pandas as pd
from tqdm import tqdm
from locations import (
    extract_geonames_coordinates,
    extract_wikidata_coordinates,
)

In [2]:
import os

if os.path.exists("locations.xlsx"):
    locations = pd.read_excel("locations.xlsx")
    locations = locations.fillna("")
else:
    locations = pd.DataFrame(columns=["location", "lat", "long", "label", "www.geonames.org", "www.wikidata.org", "www.giessen.de"])
locations

,location,lat,long,label,www.geonames.org,www.wikidata.org,www.giessen.de,gedenkbuch.saarbruecken.de,tinyurl.com,www.facebook.com,...,it.wikipedia.org,www.alte-zigarrenfabrik.com,www.museum.de,www.myheritage.it,www.sommer-archive.com,obits.syracuse.com,ballweg.store.helloflowers.com,de.wikipedia.org,www.vrm-trauer.de,www.ajpn.org
0,"Bahnhof, Frankfurt am Main",50.10679,8.66317,"Bahnhof,alte_heimat",https://www.geonames.org/6290300/frankfurt-hau...,https://www.wikidata.org/wiki/Q1794,,,,,...,,,,,,,,,,
1,Belgien,50.5,3.15,reise_zurueck,,,,,,,...,,,,,,,,,,
2,Berlin,52.52437,13.41053,,https://www.geonames.org/2950159,https://www.wikidata.org/wiki/Q64,,,,,...,,,,,,,,,,
3,Brücke Kehl–Straßburg (Rheinquerung),48.5737,7.80194,"Zug,verkehrsmittel",,https://www.wikidata.org/wiki/Q1375288,,,,,...,,,,,,,,,,
4,Deutschland,51.0,5.15,reise_zurueck,,,,,,,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,"Orange - Vaucluse, Frankreich (wh. 32, Bouleva...",,,,,,,https://gedenkbuch.saarbruecken.de/gedenkbuch/...,,,...,,,,,,,,,,
122,Orange (Frankreich),,,,,,,https://gedenkbuch.saarbruecken.de/gedenkbuch/...,,,...,,,,,,,,,,
123,Frankreich,,,,,,,https://gedenkbuch.saarbruecken.de/en/memorial...,,,...,,,,,,,,,,
124,"Avignon (Provence), Frankreich",,,,,,,https://gedenkbuch.saarbruecken.de/gedenkbuch/...,,,...,,,,,,,,,,
125,"Ramat HaSharon, Israel",,,,https://www.geonames.org/294760/hod-hasharon.html,https://www.wikidata.org/wiki/Q152379,,https://gedenkbuch.saarbruecken.de/en/memorial...,,,...,,,,,,,,,,

In [ ]:
# locations["lat", "long"] = locations.apply(
#     lambda row: (
#         extract_geonames_coordicates(row["www.geonames.org"])
#         if row["www.geonames.org"].strip()
#         else (
#             extract_wikidata_coordinates(row["www.wikidata.org"])
#             if row["www.wikidata.org"].strip()
#             else None
#         )
#     )
# )

for idx, row in tqdm(locations.iterrows(), total=locations.shape[0]):
    if row["lat"] and str(row["lat"]).strip():
        continue
    if row["www.geonames.org"].strip():
        coords = extract_geonames_coordinates(row["www.geonames.org"])
    elif row["www.wikidata.org"].strip():
        coords = extract_wikidata_coordinates(row["www.wikidata.org"])
    else:
        coords = query_geocoder(row["location"])

    locations.at[idx, "lat"] = coords["lat"] if coords else None
    locations.at[idx, "long"] = coords["long"] if coords else None
locations = locations.fillna("")
locations

100%|█████████████████████████████████████████████████████| 126/126 [00:36<00:00,  3.41it/s]

,location,lat,long,label,www.geonames.org,www.wikidata.org,www.giessen.de,gedenkbuch.saarbruecken.de,tinyurl.com,www.facebook.com,...,it.wikipedia.org,www.alte-zigarrenfabrik.com,www.museum.de,www.myheritage.it,www.sommer-archive.com,obits.syracuse.com,ballweg.store.helloflowers.com,de.wikipedia.org,www.vrm-trauer.de,www.ajpn.org
0,"Bahnhof, Frankfurt am Main",50.10679,8.66317,"Bahnhof,alte_heimat",https://www.geonames.org/6290300/frankfurt-hau...,https://www.wikidata.org/wiki/Q1794,,,,,...,,,,,,,,,,
1,Belgien,50.5,3.15,reise_zurueck,,,,,,,...,,,,,,,,,,
2,Berlin,52.52437,13.41053,,https://www.geonames.org/2950159,https://www.wikidata.org/wiki/Q64,,,,,...,,,,,,,,,,
3,Brücke Kehl–Straßburg (Rheinquerung),48.5737,7.80194,"Zug,verkehrsmittel",,https://www.wikidata.org/wiki/Q1375288,,,,,...,,,,,,,,,,
4,Deutschland,51.0,5.15,reise_zurueck,,,,,,,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121,"Orange - Vaucluse, Frankreich (wh. 32, Bouleva...",44.14,4.81,,,,,https://gedenkbuch.saarbruecken.de/gedenkbuch/...,,,...,,,,,,,,,,
122,Orange (Frankreich),,,,,,,https://gedenkbuch.saarbruecken.de/gedenkbuch/...,,,...,,,,,,,,,,
123,Frankreich,,,,,,,https://gedenkbuch.saarbruecken.de/en/memorial...,,,...,,,,,,,,,,
124,"Avignon (Provence), Frankreich",43.95,4.81,,,,,https://gedenkbuch.saarbruecken.de/gedenkbuch/...,,,...,,,,,,,,,,
125,"Ramat HaSharon, Israel",32.15934,34.8932,,https://www.geonames.org/294760/hod-hasharon.html,https://www.wikidata.org/wiki/Q152379,,https://gedenkbuch.saarbruecken.de/en/memorial...,,,...,,,,,,,,,,

In [4]:
cols = list(locations.columns)
cols = [cols[0], cols[-2], cols[-1]] + cols[1:-2]
locations = locations[cols]

locations = locations.sort_values("location")
locations

,location,www.vrm-trauer.de,www.ajpn.org,lat,long,label,www.geonames.org,www.wikidata.org,www.giessen.de,gedenkbuch.saarbruecken.de,...,en.wikipedia.org,archiv.schillerschule.de,it.wikipedia.org,www.alte-zigarrenfabrik.com,www.museum.de,www.myheritage.it,www.sommer-archive.com,obits.syracuse.com,ballweg.store.helloflowers.com,de.wikipedia.org
27,Allenstein,,,52.67,13.75,,,,,,...,,,,,,,,,,
85,Argentinien,,,-34.0,-64.0,,https://www.geonames.org/3865483,https://www.wikidata.org/wiki/Q414,,,...,,,,,,,,,,
74,Auschwitz,,,50.03702,19.17612,,https://www.geonames.org/7701596,https://www.wikidata.org/wiki/Q663764,,,...,,,,,,,,,,
63,Australia,,,-25.0,135.0,,https://www.geonames.org/2077456,,,,...,https://en.wikipedia.org/wiki/Herbert_A._David,,,,,,,,,
124,"Avignon (Provence), Frankreich",,,43.95,4.81,,,,,https://gedenkbuch.saarbruecken.de/gedenkbuch/...,...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43,Zürich,,,47.36667,8.55,,https://www.geonames.org/2657896,,,,...,,,,,,,,,,
59,https://www.geonames.org/2643743/london.html,,,51.50853,-0.12574,,https://www.geonames.org/2643743,https://www.wikidata.org/wiki/Q84,,,...,,,,,,,,,,
100,"hôtel Monnier, puis s’installent place de la R...",,,44.36082,5.14052,,https://www.geonames.org/2989819,https://www.wikidata.org/wiki/Q209810,,,...,,,,,,,,,,
46,Ägypten/Irak/Iran,,,35.06,47.26,,,,,,...,,,,,,,,,,
26,Ēmeq Yizrəʿēl,,,32.60417,35.23639,neue_heimat,https://www.geonames.org/293165/jezreel-valley...,https://www.wikidata.org/wiki/Q763829,,,...,,,,,,,,,,

In [5]:
# Merge with existing file: only add new rows and fill empty cells
import os
import re

def _normalize_loc(name):
    """Normalize for matching: lowercase, no punctuation, sorted words."""
    name = str(name).strip().lower()
    name = re.sub(r'[^\w\s]', '', name)
    return ' '.join(sorted(name.split()))

if os.path.exists("locations.xlsx"):
    existing = pd.read_excel("locations.xlsx")
    existing = existing.fillna("")
    existing_idx = {_normalize_loc(n): i for i, n in enumerate(existing["location"])}
    # Add new rows and fill empty cells
    for _, row in locations.iterrows():
        key = _normalize_loc(row["location"])
        if key not in existing_idx:
            existing = pd.concat([existing, row.to_frame().T], ignore_index=True)
            existing_idx[key] = len(existing) - 1
        else:
            # Fill empty cells only
            idx = existing_idx[key]
            for col in locations.columns:
                existing_val = str(existing.at[idx, col]).strip()
                if existing_val in ("", "nan"):
                    new_val = str(row[col]).strip()
                    if new_val not in ("", "nan"):
                        existing.at[idx, col] = row[col]
    existing.to_excel("locations.xlsx", index=False)
else:
    locations.to_excel("locations.xlsx", index=False)