In [1]:
import pandas as pd
from tqdm import tqdm
from locations import (
    extract_geonames_coordinates,
    extract_wikidata_coordinates,
)

In [2]:
locations = pd.read_excel("locations.xlsx")
locations = locations.fillna("")
locations

,location,lat,long,www.geonames.org,www.wikidata.org,www.giessen.de
0,(Ben-Jehuda-Straße),,,,,
1,"(bei Fernayrol, 5 rue Bayard)",,,,,
2,Allenstein,50.35,9.21667,https://www.geonames.org/2958427/allenstein.html,,
3,Allenstein (Ostpreußen),50.35,9.21667,https://www.geonames.org/2958427/allenstein.html,,
4,Amerikanisches Konsulat in Stuttgart,48.78232,9.17702,https://www.geonames.org/2825297/stuttgart.html,https://www.wikidata.org/wiki/Q1022,
...,...,...,...,...,...,...
93,Homburg (Saar),,,,,
94,Homburg (Saar),,,,,
95,Ägypten,,,,,
96,Ēmeq Yizrəʿēl,32.60417,35.23639,https://www.geonames.org/293165/jezreel-valley...,https://www.wikidata.org/wiki/Q763829,
97,"wh. Bne Abarnellstr. 25, Pardess Katz b/Tel-Av...",,,,,

In [3]:
# locations["lat", "long"] = locations.apply(
#     lambda row: (
#         extract_geonames_coordicates(row["www.geonames.org"])
#         if row["www.geonames.org"].strip()
#         else (
#             extract_wikidata_coordinates(row["www.wikidata.org"])
#             if row["www.wikidata.org"].strip()
#             else None
#         )
#     )
# )
for idx, row in tqdm(locations.iterrows(), total=locations.shape[0]):
    if "lat" in row:
        continue
    if row["www.geonames.org"].strip():
        coords = extract_geonames_coordinates(row["www.geonames.org"])
    elif row["www.wikidata.org"].strip():
        coords = extract_wikidata_coordinates(row["www.wikidata.org"])
    else:
        coords = None

    locations.at[idx, "lat"] = coords["lat"] if coords else None
    locations.at[idx, "long"] = coords["long"] if coords else None
locations = locations.fillna("")
locations

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 98/98 [00:00<00:00, 4844.39it/s]

,location,lat,long,www.geonames.org,www.wikidata.org,www.giessen.de
0,(Ben-Jehuda-Straße),,,,,
1,"(bei Fernayrol, 5 rue Bayard)",,,,,
2,Allenstein,50.35,9.21667,https://www.geonames.org/2958427/allenstein.html,,
3,Allenstein (Ostpreußen),50.35,9.21667,https://www.geonames.org/2958427/allenstein.html,,
4,Amerikanisches Konsulat in Stuttgart,48.78232,9.17702,https://www.geonames.org/2825297/stuttgart.html,https://www.wikidata.org/wiki/Q1022,
...,...,...,...,...,...,...
93,Homburg (Saar),,,,,
94,Homburg (Saar),,,,,
95,Ägypten,,,,,
96,Ēmeq Yizrəʿēl,32.60417,35.23639,https://www.geonames.org/293165/jezreel-valley...,https://www.wikidata.org/wiki/Q763829,
97,"wh. Bne Abarnellstr. 25, Pardess Katz b/Tel-Av...",,,,,

In [4]:
cols = list(locations.columns)
cols = [cols[0], cols[-2], cols[-1]] + cols[1:-2]
locations = locations[cols]

locations = locations.sort_values("location")
locations

,location,www.wikidata.org,www.giessen.de,lat,long,www.geonames.org
0,(Ben-Jehuda-Straße),,,,,
1,"(bei Fernayrol, 5 rue Bayard)",,,,,
2,Allenstein,,,50.35,9.21667,https://www.geonames.org/2958427/allenstein.html
3,Allenstein (Ostpreußen),,,50.35,9.21667,https://www.geonames.org/2958427/allenstein.html
4,Amerikanisches Konsulat in Stuttgart,https://www.wikidata.org/wiki/Q1022,,48.78232,9.17702,https://www.geonames.org/2825297/stuttgart.html
...,...,...,...,...,...,...
91,Zürich,,,47.36667,8.55,https://www.geonames.org/2657896/zuerich.html
92,"hôtel Monnier, puis s’installent place de la R...",,,,,
97,"wh. Bne Abarnellstr. 25, Pardess Katz b/Tel-Av...",,,,,
95,Ägypten,,,,,
96,Ēmeq Yizrəʿēl,https://www.wikidata.org/wiki/Q763829,,32.60417,35.23639,https://www.geonames.org/293165/jezreel-valley...

In [5]:
locations.to_excel("locations.xlsx", index=False)